- Dockerfile
- README.md
- prometheus.yml
This PR adds a Dockerfile and Prometheus configuration for M-Lab monitoring.
This configuration should be deployed within a kubernetes cluster. The kubernetes API server, nodes in the kubernetes cluster, as well as other pods and services running in the cluster are automatically discovered and added as targets for monitoring by Prometheus.
This configuration also supports file based service discovery. This will allow us to update the list of monitored legacy targets at run-time by copying a configuration file into the container.
This PR also adds instructions in the README.md for building and deploying the demo prometheus image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/promet …
> Configuration for Prometheus in Kubernetes

- prometheus.yml
Using the previous configuration, Prometheus would try to use port 80 on discovered pod addresses, but we need the flexibility to monitor alternate ports from (possibly) public services.
This PR adds support for monitoring ports declared in kubernetes annotations. For example:
prometheus.io/port=9090
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/2)
> Support monitoring ports declared in kubernetes annotations.

- prometheus.yml
This change updates the regex to match addresses with or without default
ports for pod and service discovery.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/3)
> Correct regex for address and port configuration.

- prometheus.yml
This change corrects a bug introduced by PR: https://github.com/m-lab/prometheus-support/pull/3
The regex uses three groups: the hostname, an optional port, and the
preferred port from a kubernetes annotation.
Previously, the second group should have been ignored if a :port was not
present in the input. However, making the port group optional with the
"?" had the unintended side-effect of allowing the hostname regex "(.+)"
to match greedily, which included the ":port" patterns up to the ";"
separating the hostname from the kubernetes port annotation.
This change updates the regex for the hostname to match any non-":"
characters. This forces the regex to stop if a ":port" is present and
allow the second group to match the optional port.
--- …
> Fix kubernetes host:port relabel regex.

- k8s/mlab-staging/services.yml
This made a copy of mlab-sandbox, was renamed to mlab-staging, and the services.yml file inside was updated to reflect the IP of the instance running in the mlab-staging GCloud project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/6)
> Add k8s/mlab-staging/services.yml with IP of mlab-staging instance

- README.md
- k8s/prometheus.yml
- prometheus/Dockerfile
This PR removes the need to create a custom prometheus docker image by adding a ConfigMap configuration for the prometheus configuration.
Using the ConfigMap, operators can update a configuration file and restart the pod.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/7)
> Add configmap for prometheus.yml config (and use upstream prometheus docker image)

- k8s/prometheus.yml
By default, (afaict) there is no monitoring of disk utilization for mount points of persistent volumes that uses the natural name familiar to operators, e.g. "/prometheus".
So, instead of a label like:
```
{mountpoint="/prometheus"}
```
Default behavior provides inscrutable labels like:
```
{mountpoint="/rootfs/var/lib/kubelet/pods/6950c80b-0b72-11e7-b1f8-42010af0004b/volumes/kubernetes.io~gce-pd/pvc-3e682a5b-f95d-11e6-a30a-42010af0004b"}
```
While the generated name does not change over time, it is a tedious manual process for an operator to translate that label to a human readable one.
This change provides human readable filesystem usage metrics by running a node-exporter within the same pod as the prometheus server. As a result, it has access to the same namespace and mount points as …
> Add disk usage monitoring of /prometheus mount point.

- README.md
- k8s/node-exporter-daemonset.yml
This change adds a DaemonSet configuration for the node-exporter to run on every node in a cluster.
The node-exporter collects [a variety of system metrics][exporter] that we can use to assess whole-cluster health.
[exporter]: https://github.com/prometheus/node_exporter#enabled-by-default
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/11)
> Add a DaemonSet for the node-exporter

- k8s/mlab-sandbox/salarcon-kub-prom-walkthru/services.yml
- prometheus/prometheus.yml
- prometheus/rules.yml
This change adds recording rules to Prometheus.
Recording rules are a form of pre-calculation for expressions that are more expensive to execute at run-time. When active, recording rules can be queried like any other prometheus metric.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/8)
> Add support for recording rules

- README.md
- config/federation/blackbox/config.yml
- config/federation/prometheus/prometheus.yml
- k8s/federation/blackbox.yml
- k8s/federation/prometheus.yml
- k8s/mlab-sandbox/soltesz-test-3/services.yml
This change adds basic configuration for the blackbox exporter as well as changes to the prometheus configuration to take advantage of the blackbox exporter.
With this configuration it will be possible to emulate the nagios `check_tcp`, `check_http`, `check_ssh`, and `check_icmp` plugins (with some caveats).
The changes to the prometheus config can be deployed independently of the blackbox configs.
A working configuration is available temporarily at http://104.197.220.28:9090/targets and:
wget -q -O - 'http://104.197.220.28:9115/probe?target=mlab1.lga02.measurement-lab.org:806&module=ssh_v4_online'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/15)
> Add blackbox exporter monitoring

- config/federation/prometheus/prometheus.yml
- k8s/federation/pushgateway.yml
- k8s/mlab-sandbox/soltesz-test-3/services.yml
This change adds a new service definition for the push gateway, a k8s
config for the pushgateway deployment, and an update to the prometheus server
scrape configuration to collect metrics from the push gateway.
The pushgateway does not need persistent storage with the minimal configuration and it's not clear that we want that ultimately for our use cases anyway.
The configuration changes to the prometheus.yml scrape configuration can be deployed safely without the pushgatway deployment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/17)
> Add basic pushgateway support.

- cmd/mlab_service_discovery/Dockerfile
- cmd/mlab_service_discovery/main.go
This change adds a Dockerfile for `mlab_service_discovery` and allows the process to run continuously.
The intended deployment is within the prometheus pod, so that `mlab_service_discovery` can update the targets file continuously.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/20)
> Run mlab_service_discovery continuously.

- README.md
- config/federation/prometheus/prometheus.yml
- k8s/federation/prometheus.yml
This change includes two updates.
1. The README now includes notes on the pushgateway, since they were not added previously.
2. Add the mlab-service-discovery container to the federation prometheus deployment so that App Engine Flex VMs can be automatically detected continuously and scraped by prometheus.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/21)
> Add App Engine Flex service discovery to Prometheus deployment

- k8s/federation/prometheus.yml
This change increases the resources assigned to Prometheus based on load requirements from work on the ETL pipeline.
As well, this provides a mount point for saving the aeflex service discovery file (accidentally omitted from a previous PR).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/22)
> Increase resources for federated prometheus

- k8s/cluster/prometheus.yml
This change updates the k8s/cluster configuration for prometheus so that the service definition uses an ephemeral IP that can be discovered later by searching for services annotated with the value: "gke-prometheus-federation/scrape: true".
This simplifies cluster deployments by not requiring a static ip allocation before hand and provides a means of discovering the target for "federation" scraping at a later time (likely from another cluster).
> Use ephemeral IP for prometheus cluster service configuration

- config/federation/blackbox/config.yml
This change adds a new module to the blackbox exporter configuration for checking the status of rsyncd servers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/25)
> Add blackbox exporter module for rsyncd.

- config/federation/blackbox/config.yml
- config/federation/prometheus/prometheus.yml
This change includes two fixes to the blackbox configuration.
First, we change all blackbox module timeouts to 5 seconds to guarantee that this timeout is less than the prometheus scrape timeout of 10 seconds. This is necessary to ensure that prometheus receives metrics about the failed probe rather than concluding that the blackbox exporter is down.
Second, we change a regex in the blackbox exporter relabel config to use parentheses so that the group numbers (`${1}`) work as intended. Their original omission was a typo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/27)
> Fix blackbox timeout and prometheus relabel regex for blackbox module label

- k8s/federation/prometheus.yml
This change depends on https://github.com/m-lab/operator/pull/105
This change updates the service discovery image to use gcp-service-discovery. Because gcp-service-discovery supports downloading arbitrary target files, this change also references the three target files generated automatically by https://github.com/m-lab/operator/pull/105
With the combination of https://github.com/m-lab/operator/pull/105 and this change, changes to the operator repo (addition or removal of sites) will automatically be propagated to prometheus services running the gcp-service-discovery image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/28)
> Update prometheus service-discovery 

- k8s/federation/prometheus.yml
This change removes a stray value `- mountPath` that was added accidentally and uses double `--` prefixes for flags, required by the POSIX compatible flag package "github.com/spf13/pflag".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/29)
> Fix typos with flags and stray value.

- cmd/query_tester/README.md
- cmd/query_tester/main.go
- cmd/query_tester/main_test.go
- cmd/query_tester/testdata/inventory.txt
This change adds a command that runs as a golang test and evaluates prometheus queries. The intention is to provide a way of verifying that our alert queries behave correctly with synthetic data.
Currently, Prometheus does not support unit tests on alert rules (though it is desired https://github.com/prometheus/prometheus/issues/1695).
For now, the `query_tester` uses the test framework that prometheus uses to test itself. Note that this syntax is not an officially supported language. But, having the ability to test queries used in our alerts, in some form, is much better than untested (or ad-hoc manual "integration" testing).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/promethe …
> Add framework to implement tests on queries for prometheus alerts

- apply-cluster.sh
- apply-federation.sh
- k8s/mlab-oti/prometheus-federation/alertmanager-public-service.yml
- k8s/mlab-oti/prometheus-federation/blackbox-public-service.yml
- k8s/mlab-oti/prometheus-federation/grafana-public-service.yml
- k8s/mlab-oti/prometheus-federation/prometheus-public-service.yml
- k8s/mlab-oti/prometheus-federation/pushgateway-public-service.yml
This change adds k8s service definitions for the mlab-oti deployment of the prometheus-federation cluster.
As well, we add two `apply-*` scripts that will make it easier to deploy changes in the future.
> Add service definitions for mlab-oti & deploy scripts

- README.md
- k8s/cluster/prometheus.yml
- k8s/federation/prometheus.yml
To better support deployment to scraper, we need to add nodeSelectors so that prometheus only deploys to specific machines (and so scraper instances only deploy to different machines).
As well, this change includes commands for creating a cluster or adding a new node-pool for prometheus.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/33)
> Add nodeSelector for prometheus

- config/federation/prometheus/prometheus.yml
The scrape interval is every 60seconds and the default timeout is 10seconds.
This change increases the scrape timeout to 50s only for federation collection. This is not because collection *should* take that long or even that we want to allow it to take that long, but so that we have more headroom to monitor deployments with longer collection times than the default (10s).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/34)
> Allow longer timeouts for collection from federated clusters.

- .travis.yml
- README.md
This change adds basic travis support for running the query unit tests and applying a rules check with `promtool`.
https://travis-ci.org/stephen-soltesz/prometheus-support
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/35)
> Add basic travis support to prometheus-support

- cmd/query_tester/testdata/machine-slo.txt
- cmd/query_tester/testdata/scraper-slo.txt
- cmd/query_tester/testdata/scraper.txt
- cmd/query_tester/testdata/sidestream.txt
- config/federation/prometheus/alerts.yml
This change includes the remaining "unit tests" for the scraper alerts in the query_tester testdata directory.
As well, this change introduces the initial version of actual alert definitions that depend on the tested queries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/39)
> Add Scraper alert tests & actual alert definitions

- config/cluster/prometheus/prometheus.yml
- k8s/cluster/prometheus.yml
This change updates the pod service discovery behavior to use explicitly declared container ports as a way of identifying targets.
Also, this change updates the labels assigned to discovered k8s pod targets. In particular, the following labels are now assigned to pods:
* container - the container name.
* pod - the pod name.
* deployment - the deployment name (derived from pod name)
* namespace - the k8s namespace.
* cluster - the k8s cluster and node-pool name.
* ready - is the pod ready
TODO: if this works as intended, similar changes are needed to the `config/federation/prometheus` config.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/40)
> Change pod service discovery to include all explicitly declared containerPorts

- config/federation/prometheus/prometheus.yml
- k8s/federation/prometheus.yml
- k8s/mlab-oti/prometheus-federation/prometheus-public-service.yml
- k8s/mlab-sandbox/prometheus-federation/services.yml
- k8s/mlab-staging/prometheus-federation/prometheus-public-service.yml
This change adds the identical relabel config to the federation prometheus configuration.
This is the same as introduced in: https://github.com/m-lab/prometheus-support/pull/40
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/42)
> Add new pod relabel config to config/federation/prometheus/prometheus.yml

- README.md
- k8s/cluster/prometheus.yml
- k8s/persistent-volumes.yml
- k8s/storage-class.yml
To accommodate the load generated by the scraper deployment in mlab-oti we're increasing the RAM used as well as using an SSD for metric storage.
This configuration has run over the weekend with 75% of the scraper instances. It is expected to remain stable at 100%.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/43)
> Use latest Prometheus version with more RAM and SSD

- k8s/kube-state-metrics.yml
By default the built-in scrape targets on the k8s api server does not expose information about the state of the objects known to k8s, e.g. (pod is in an Error, Creating, Pending, or Running state).
This makes it impossible to know or create alerts for certain kinds of failures.  This change adds the kube-state-metrics service that exports metrics in a useful form for Prometheus.
Documentation for kube-state-metrics and the metrics it exports are at: https://github.com/kubernetes/kube-state-metrics
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/44)
> Add new service to export k8s states

- config/cluster/prometheus/prometheus.yml
In practice we've found the creation of new time series to be the most expensive operation for prometheus. This requires creating a new file on disk and adding additional in-memory indexes for all known time series.
At the scale that scraper operates, simply re-deploying all scrapers (3200 x 2) and applying all of them a new pod name creates approximately 1 million new time series (one for every metric exported by every scraper and node-exporter), each with a new pod name.
By removing the pod name, deployments will be identifyable by the "deployment" name, but the change in version will not be evident with the attribute labels.
It's possible we could reserve a single metric for this purpose so pod names are applied to only one or a much smaller sub set rather than all. But, as an …
> Disable adding a pod name label.

- k8s/cluster/prometheus.yml
- k8s/federation/prometheus.yml
Kubernetes normally sends a SIGTERM to pid 1 when shutting down a container, during a pod delete or apply operation. The default timeout of 30s was not sufficient, and would interrupt prometheus during it's clean shutdown process. As a result, the prometheus data volume was left in an inconsistent state that needed a lengthy recovery process on startup.
This longer grace period should allow prometheus to shutdown cleanly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/46)
> Support a longer timeout for graceful shutdown of prometheus.

- k8s/cluster/prometheus.yml
This change reflects new values applied to the instance of prometheus monitoring the scraper cluster in mlab-oti. The net effect of them is to reserve more RAM than the defaults so that prometheus can handle the very large number of metrics collected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/45)
> Update index-cache-size flags and comments.

- config/federation/prometheus/alerts.yml
The `scraper_maxrawfiletimearchived` metric will not be exported for machines that have never uploaded a tarfile (such as those not yet installed for the first time).
This change uses `scraper_lastcollectionattempt` instead which is guaranteed to always be exported and updated as long as the corresponding scraper is running.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/54)
> Update internal consistency checks to use lastcollectionattempt

- config/federation/prometheus/alerts.yml
Since scrapers normally upload tar archives once a day, the `scraper_maxrawfiletimearchived` may not be updated for up to 24 hours.
This change requires that the sidestream process start time (a proxy for system start time) be longer than 24 hours.
TODO: we must replace `process_start_time_seconds` for the actual system uptime.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/57)
> Wait for machines to be online for 24h

- apply-cluster.sh
- apply-global-prometheus.sh
- config/federation/alertmanager/config.yml.template
This change updates the `apply-global-prometheus.sh` and `apply-cluster.sh` scripts in preparation for automated deployment using travis.
apply-global-prometheus uses given parameters to generate the expected URLs and generates a random grafana admin password, which can be recovered manually via k8s if necessary.
Both scripts attempts to reload the prometheus configuration using the public service address.
Finally, this change includes an update to the alertmanager template.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/60)
> Update the prometheus configuration apply scripts

- README.md
- config/federation/alertmanager/config.yml.template
- k8s/mlab-oti/prometheus-federation/deployments/github-receiver.yml
- k8s/mlab-oti/prometheus-federation/services/github-receiver-public-service.yml
This change includes new k8s configuration in the mlab-oti project for the initial version of the github receiver.
> Add k8s configuration to mlab-oti for alertmanager github receiver

- k8s/mlab-oti/prometheus-federation/deployments/prometheus.yml
- k8s/mlab-staging/prometheus-federation/deployments/prometheus.yml
When running batch processing jobs through ETL, we may have up to 50 instances or more.  Prometheus starts choking badly around 20 to 25 instances, when using "increase" queries.  This should provide a bit more headroom.
> better handle jobs with many instances

- config/local/prometheus/README.md
- config/local/prometheus/prometheus.yml
When developing new exporters or experimenting with prometheus settings it can be helpful to do this locally using docker.
This change includes a small README for using the new "local" prometheus config.
> Add a new prometheus "local" config for testing locally

- k8s/mlab-oti/prometheus-federation/deployments/blackbox.yml
- k8s/mlab-oti/prometheus-federation/deployments/prometheus.yml
- k8s/mlab-oti/scraper-cluster/deployments/prometheus.yml
- k8s/mlab-sandbox/prometheus-federation/deployments/blackbox.yml
- k8s/mlab-sandbox/prometheus-federation/deployments/prometheus.yml
- k8s/mlab-sandbox/scraper-cluster/deployments/prometheus.yml
- k8s/mlab-staging/prometheus-federation/deployments/blackbox.yml
- k8s/mlab-staging/prometheus-federation/deployments/prometheus.yml
- k8s/mlab-staging/scraper-cluster/deployments/prometheus.yml
This PR adds the `prometheus.io/scrape: 'true'` to the blackbox service, previously missing. This will allow the prometheus server to scrape metrics about the blackbox service itself.
As well, this PR includes minor comment updates to the prometheus deployment configs, and enables the 'prometheus' service account in mlab-oti (a step that should have been completed already).
> Add scrape annotations for blackbox deployment

- config/federation/blackbox/config.yml
Previously, when the blackbox exporter would probe the rsyncd server, it would drop the connection immediately after getting the greeting from rsyncd. Since this is not how well behaved clients act, rsyncd would log an error like:
```
Sep 10 03:39:30 mlab1 rsyncd[16964]: rsync: connection unexpectedly closed (0 bytes received so far) [receiver]
Sep 10 03:39:30 mlab1 rsyncd[16964]: rsync error: error in rsync protocol data stream (code 12) at io.c(600) [receiver=3.0.6]
```
With this change, the blackbox exporter uses a valid request to list the modules, which causes the rsyncd server to shutdown the connection cleanly. Now logs will contain:
```
Sep 25 18:16:37 mlab2 rsyncd[1051]: connect from 87.93.148.146.bc.googleusercontent.com (146.148.93.87)
Sep 25 18:16:42 mlab2 rsyncd[1051]: …
```
> Simulate a module list command to avoid log errors

- config/local/blackbox/README.md
- config/local/blackbox/config.yml
To test the change to the blackbox exporter rsync module configuration, I setup a local server initially.
This PR adds simple documentation and example configuration for doing this again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/83)
> Add a local blackbox exporter configuration for testing.

- k8s/mlab-sandbox/prometheus-federation/deployments/prometheus.yml
This PR is complementary to [m-lab/operator/pull/152](https://github.com/m-lab/operator/pull/152).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/82)
> Adds snmp_exporter targets to gcp-service-discovery.

- config/federation/prometheus/prometheus.yml
Currently, quite a lot of the snmp-targets are timing out (i.e., taking longer than the 10s global default). 30s should be enough for any of those snmp_exporter requests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/89)
> Sets scrape_timeout for snmp-targets to 30s.

- .travis.yml
- cmd/query_tester/main.go
When attempting to build this repository a while ago the Travis-CI build log reported:
```
$ go test -v github.com/m-lab/prometheus-support/cmd/query_tester -args -log.level warn
flag provided but not defined: -log.level
```
This PR removes `-args -log.level warn` to avoid this error.
After fixing that, builds were still failing with:
```
$ promtool check-rules config/federation/prometheus/rules.yml
promtool: error: expected command but got "check-rules", try --help
```
Not only has `check-rules` changed to `check rules` in the current HEAD of promtools, but the checks were failing our YML files, which apparently no longer conform to the latest format. To get around this, this PR also pins the version of promtool to the latest stable version (as of this writing), which is v1.8.0.
---
This …
> Pins promtool to v1.8.0 and removes unsupported flag from query_tester

- .travis.yml
- cmd/query_tester/main.go
These flags were removed in PR #93.  That PR fixed two issues, and it turns out that the later fix in that PR fixed the previous error. This PR adds those flags back, since they work now, and make Travis build logs less verbose.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/94)
> Adds back the '-args -log.level warn' flag to query_tester

- config/federation/prometheus/alerts.yml
Over time, the ScraperMostRecentArchivedFileTimeIsTooOld has generated over 10
spurious alerts, firing and then resolving automatically within a few hours.
This can happen for example, after a machine restart and before scraper has
completed updating the scraper_maxrawfiletimearchived value for the last day.
By observation, all instances of this alert resolved this is within 1 to 5
hours, so increasing the sidestream threadhold to 30 hours should be adequate
to prevent all of the spurious alerts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/88)
> Increase process start time threshold for ScraperMostRecentArchivedFileTimeIsTooOld

- apply-global-prometheus.sh
- config/federation/grafana/grafana.ini
- k8s/mlab-sandbox/prometheus-federation/deployments/grafana.yml
This change adds support for Grafana login using Google OAuth.
The client secret and client id are stored as secure environment variables in the travis environment and available and deploy time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/95)
> Update Grafana and enable Google OAuth login

- k8s/scraper-cluster/mlab-sandbox.yml
We do not run scraper in sandbox and the previous config was not actually working. This changes the resource utilization so that it can work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/102)
> Reduce resource requirements for scraper-cluster in sandbox

- apply-global-prometheus.sh
- config/federation/alertmanager/config.yml.template
This change generates the alertmanager configuration from a template and environment variables provided by travis.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/105)
> Generate Alertmanager configuration from template

- apply-cluster.sh
- apply-global-prometheus.sh
Now that the transition to using templates for k8s configuration is complete the fallback options to directly apply config files is no longer necessary.
This change removes the alternative configuration commands for applying k8s configuration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/106)
> Always use the template configuration

- config/federation/prometheus/prometheus.yml
In other words, only keep the label if it has a value. The vast majority of `ifAlias` labels will have no value. Don't pollute the datastore with empty labels, but instead just drop empty ones and only keep ones with some value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/107)
> Drops all 'ifAlias' labels that are just empty strings. 

- config/federation/prometheus/prometheus.yml
There are still just a few stragglers that could use a little longer timeout.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/108)
> Increases the timeout for snmp-targets from 30s to 45s

- README.md
- apply-global-prometheus.sh
- k8s/prometheus-federation/deployments/prometheus.yml
These new project subdomains are managed in Google Cloud DNS, where as the old-style ones (e.g., status-mlab-staging.measurementlab.net) are manually managed in the measurementlab.net zonefile in the m-lab/dns-zones repository.  Having this configuration will make managing DNS much easier because we'll be able to use the GCP API for pretty much everything.
**NOTE**: this PR depends on [PR 28 in the m-lab/dns-zones repository](https://github.com/m-lab/dns-zones/pull/28).
I have already created the DNS records that these changes require in the Google Cloud DNS console for each project.
* https://console.cloud.google.com/net-services/dns/zones/mlab-oti-measurementlab-net?project=mlab-oti
* https://console.cloud.google.com/net-services/dns/zones/mlab-staging-measurementlab-net?project=mlab-sta …
> Changes all references to http://status-<project> to http://status.<project>

- apply-global-prometheus.sh
- config/federation/prometheus/prometheus.yml
- config/federation/prometheus/prometheus.yml.template
This will start monitoring our snmp_exporter services, running in GCE VMs. Once in place, we can possibly add rules for the AlertManager to alert on the instances.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/111)
> Adds static scrape configs for the snmp_exporter VMs running in each GCP project.

- config/federation/prometheus/prometheus.yml.template
The path `/metrics` is implied, and is an error when included in the target URL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/112)
> Fixes an invalid scrape target URL for the snmp_exporter. 

- config/federation/prometheus/prometheus.yml.template
- k8s/prometheus-federation/deployments/prometheus.yml
For the bigquery exporter it is helpful to poll the exporter less often than every minute.
This change adds a "slow-5m-targets" job configuration that scrapes targets every 5 min instead of the global 1 min.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/116)
> Add slow-targets configuration

- config/federation/prometheus/alerts.yml
If a node has been put in lame-duck mode, then all bets are off for machine-dependent services. This PR negates an alert condition if the node is in lame-duck mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/118)
> Sets machine-dependent alerts to not alert on nodes in lame-duck mode.

- apply-global-prometheus.sh
- config/federation/bigquery/bq_ipv6_bias.sql
- config/federation/bigquery/bq_ndt_server.sql
- k8s/prometheus-federation/deployments/bigquery-exporter.yml
- k8s/prometheus-federation/deployments/prometheus.yml
This change adds two new standardSQL queries for the bigquery exporter.
* bq_ipv6_bias -- per-machine, per-address-type, and per-window scale metrics for measuring bias introduced by IPv6 configuration on M-Lab servers. This will allow us to safely monitor new deployments.
* bq_ndt_server -- per-machine summary metrics for NDT uploads, downloads, and RTT. This will allow us to observe changes in "normal" behavior over time from NDT server or kernel upgrades.
This change also includes two minor changes to the apply-global-prometheus.sh script to report configs in the event of errors, and an update of the prometheus container version from 1.6.2 to 1.8.2. The 1.8 version includes features for more easily migrating to version 2.0, which uses a different backing store format.
---
This change …
> Add bq_ipv6_bias and bt_ndt_server queries to the bigquery exporter

- config/federation/bigquery/bq_ndt_tests.sql
This change supports more accurate end to end comparisons of the bigquery exporter NDT test counts and the inotify exporter running on M-Lab nodes.
Before this change we observed that low traffic machines or sites had extreme inconsistency between the inotify test counts and the bqe test counts. On low traffic machines, this amounted to a handful of tests, but in aggregate it made the accuracy of the system difficult to assess.
This change revises the ndt test count query to perform two new operations.
1. De-duplicate tests, which have an exaggerated impact on low-traffic sites.
2. Return zero counts, for intervals without tests we want the bqe to return 0 for that interval.
With these changes, the sandbox deployment observed a global improvement in accuracy from low-traffic sites.
--- …
> Fix NDT test counts -- de-dup and zero counts

- config/federation/prometheus/alerts.yml
This change adds a new alert for the M-Lab test parsers.
The alert checks whether today's test volume is less than 20% of yesterday's volume. Since the parser schedule for all test data is periodic this appears to work well for NDT, and paris traceroute parsers. The alert explicitly ignores "batch" jobs which do not necessarily follow a predictable schedule.
This change also includes a complementary change to ScraperMostRecentArchivedFileTimeIsTooOld by extending the threshold to 56hours. This provides enough time for daily configuration jobs to run. And, prevents creation of a redundant alert with ParserDailyVolumeTooLow when many machines are affected.
--- …
> Add ParserDailyVolumeTooLow alert

- k8s/prometheus-federation/deployments/blackbox.yml
We are observing the blackbox probes failing too often and the number of probes that appear to timeout is also too high for the probe_success metric.
This change increases the CPU allocation to 1 CPU based on the belief that the blackbox exporter is simply resource constrained.
http://status.mlab-oti.measurementlab.net:9090/graph?g0.range_input=6h&g0.end_input=2017-11-14+20%3A14&g0.step_input=20&g0.stacked=0&g0.expr=sum+by(container_name)+(rate(container_cpu_usage_seconds_total%7Bcontainer_name%3D%22blackbox-server%22%7D%5B10m%5D))&g0.tab=0&g1.range_input=12h&g1.expr=container_memory_usage_bytes%7Bcontainer_name%3D%22blackbox-server%22%7D&g1.tab=0
--- …
> Increase blackbox exporter CPU alloc to 1 CPU

- config/local/grafana/README.md
- config/local/grafana/dashboards/example.dashboard.py
- config/local/grafana/dashboards/generate.sh
This change adds a "local" configuration example for running Grafana for testing and loading dashboards generated by "grafanalib" from weaveworks. https://www.weave.works/blog/grafana-dashboards-as-code/
This is a precursor to applying this configuration to our production configs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/139)
> Add notes for running Grafana locally and examples of Dashboards-as-code

- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
This change adds the `up{..}` metric to the prometheus federation scrape configuration. This is necessary since the `downloader` runs in a separate cluster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/141)
> Update downloader alert and federation configuration

- k8s/prometheus-federation/deployments/grafana.yml
This upgrades the version of Grafana to use the lastest which includes for graph annotations and better support for loading static dashboards at start time. This is a precursor for static dashboard configs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/142)
> Update grafana version to latest

- config/federation/prometheus/rules.yml
- k8s/prometheus-federation/deployments/prometheus.yml
This change adds four new recording rules to the prometheus configuration for the NDT early warning system.
This change also enables debug logging on the Prometheus server to help locate the source of "dropped metric" errors cited in https://github.com/m-lab/prometheus-support/issues/144
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/145)
> Add recording rules for NDT Early warnings

- k8s/prometheus-federation/deployments/alertmanager.yml
- k8s/prometheus-federation/deployments/github-receiver.yml
This change updates  the alertmanager & github receiver versions to provide new functionality.
In the case of Alertmanager, there are numberous bug fixes as well as UI enhancements. In particular, URLs in alert annotations are auto-linked making it easy to navigate from alertmanager to a dashboard (or other resource) when handling an alert.
In the case of the github receiver, the latest version disables issue closing once an alert is resolved. This will require explicit resolution of alerts with a person evaluating how the alert should be resolved long term.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/147)
> Update Alertmanager & Github Receiver Versions

- config/federation/prometheus/rules.yml
- k8s/prometheus-federation/deployments/prometheus.yml
The original recording rules resulted in a random set of about 20-30 missing switch uplink time series.
After describing my investigation here https://groups.google.com/forum/#!topic/prometheus-users/LVidx6lwwAo I got some very helpful feedback and came to a better solution.
In particular, this change uses `irate` instead of `rate` and a larger range window to guarantee that two points are always available for the `irate` calculation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/148)
> Enable more reliable recording rules using irate

- config/federation/prometheus/rules.yml
This change adds new recording rules that calculate instantaneous violations of 2x site capacity thresholds. With these rules, it will be possible to calculate a percentage over a time range (e.g. day, week, or longer) that the 2x site capacity was violated.
For example, the following would calculate the percentage of time the site had at least 2x headroom:
```
1 - sum_over_time(site:uplink:gt_500mbps{site=~"$site.*"}[24h]) / count_over_time(site:uplink:gt_500mbps{site=~"$site.*"}[24h])
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/150)
> Add new rules for boolean threshold violations

- config/federation/prometheus/alerts.yml
This change updates the condition for ParserDailyVolumeTooLow to improve accuracy. Since deployment, this alert has fired inaccurately about 7 times and accurately 0 times.
This change uses a longer time range (12h instead of 2h) and ignores small values. This new condition applied to historical data correctly detects the outage from Nov 29th and the surge of sidestream and paris-traceroute processing after updating those parsers. As well, it would only fire once in both cases.
Pipeline outage Nov 29th:
http://status.mlab-oti.measurementlab.net:3000/dashboard/db/parserdailyvolumetoolow?orgId=1&from=1511845200000&to=1512277200000
Sidestream & PTR reprocessing:
http://status.mlab-oti.measurementlab.net:3000/dashboard/db/parserdailyvolumetoolow?orgId=1&from=1512579600000&to=1513184400000
--- …
> Increase accuracy of ParserDailyVolumeTooLow

- config/federation/prometheus/prometheus.yml.template
This change will re-label snmp metrics whose ifAlias label is in the form `uplink-<speed>`.
This will allow us to identify 1g vs 10g sites in monitoring and dashboards and alert appropriately.
The rule should have no effect on ifAlias values that do not start with "uplink". The rule should also have no effect on existing ifAlias values of only "uplink".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/151)
> Split uplink and speed labels on snmp metrics.

- config/federation/prometheus/rules.yml
This change adds new candidate recording rules and replaces pre-existing `*:90th_quantile` rules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/153)
> Add 90th and 98th percentile rules for 2h & 6h ranges.

- config/federation/blackbox/config.yml
Intuition would dictate that 5s is more than enough to establish a TCP connection to a remote server, but for some reason a lgood number of the `ndt_ssl` and `ndt_raw` checks are timing out at 5s. In order to find out the depth of this problem, this PR increases the timeout to 10s. If things are still timing out at 10s, then something fundamental must be wrong which will warrant a more in-depth investigation. But currently, we don't know whether the timed-out check would have succeeded a few seconds later, or whether the problem is great enough that it would even timeout at 10s. After this PR we'll be able to assess the situation better.
--- …
> Increases timeout for tcp_v4_[tls_]online modules from 5s to 10s

- config/federation/blackbox/config.yml
- k8s/prometheus-federation/deployments/blackbox.yml
Our currently running version of blackbox_exporter (0.4.0) is "ancient" (2017-01-12). This PR tells k8s to deploy version v0.11.0 instead. It also makes a few small changes to the config file to make it compatible with this newer version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/156)
> Upgrades blackbox_exporter to v0.11.0, and updates config to be compatible.

- config/federation/prometheus/alerts.yml
Today a DNS update resulted in the failure to collect all snmp metrics on all project. While the snmp-exporter itself was still running, no metrics were being collected from it because the target configuration was using a bad hostname.
This change adds an alert on the absence of the `ifHCOutOctets` metric, as a stand-in for all snmp metrics. This metric should always be present.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/157)
> Add new alert for missing SNMP metrics

- apply-global-prometheus.sh
This change sets the GITHUB_RECEIVER_URL unconditionally. Previously, the alertmanager configuration would have an empty url for non-production projects. However, perhaps with the upgrade to v0.11 of the alertmanager, an empty url is now an error, and in mlab-staging the AM was not running.
This change sets GITHUB_RECEIVER_URL unconditionally so that a value is present even if it won't be running in non-production projects. The AM trying to send a message to an absent service should be a no-op.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/158)
> Always set GITHUB_RECEIVER_URL

- k8s/prometheus-federation/deployments/blackbox.yml
This change addresses a performance regression in the blackbox exporter.
We believe that the issue is due to the Go GC as originally reported in https://github.com/prometheus/blackbox_exporter/issues/270
It may be that one day the Go compiler will fix the inefficiency but until then, we can simply provide more resources.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/159)
> Increase resource alloc for blackbox exporter

- config/federation/prometheus/alerts.yml
This change increases the delay threshold for firing the ScraperMostRecentArchivedFileTimeIsTooOld alert.
The delay threshold is set to 2h to prevent false positives. For example, if a machine remains running while it is not network accessible, then the machine will need time for scraper to catch up once it is network accessible again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/162)
> Update alert delay threshold for ScraperMostRecentArchivedFileTimeIsTooOld

- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
We have a secondary, and very small, Nagios instance that runs in a Linode VM whose sole purpose is to monitor critical infrastructure machines and services. For example, this instance monitors to be sure that eb.measurementlab.net is up and that Nagios is running. It monitors that dns.measurementlab.net is up, etc. However, nothing currently monitors whether this instance is running or not. This PR tells Prometheus to scrape the nagios_exporter running on that VM, and to alert if Nagios is not running, or if the `nagios-oam-exporter` job doesn't exist for some reason.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/164)
> Scrape nagios_exporter on nagios-oam, and alert if Nagios is down.

- config/federation/prometheus/alerts.yml
Uses label_replace to properly aggregate across different time periods.
Uses vector(0) to handle startup issues.
Seems to work well for recent alerts, including false positives.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/167)
> Compare larger window to smaller window

- config/federation/prometheus/alerts.yml
The alert is used for both staging and production.  Since staging volume is very low, the moderate constant values are much too high.  Zero works quite well unless the pipeline or scraper is down for multiple days, we just change to zero.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/171)
> set constants to zero

- k8s/scraper-cluster/mlab-oti.yml
- k8s/scraper-cluster/mlab-staging.yml
The servers have 98945476Ki of RAM allocateable, which is less than 96Gi
(100663296Ki) but is more than 96G. So if we drop the i, then then job
will become allocateable on highmem instances.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/172)
> Change the 96Gi request to a 96G request.

- config/federation/grafana/dashboards/Alert_ParserDailyVolumeTooLow.json
- config/federation/grafana/dashboards/NDT_EarlyWarning.json
- config/federation/grafana/dashboards/NDT_GlobalTestRate.json
- config/federation/grafana/dashboards/Prometheus_SelfMonitoring.json
This change imports four dashboards from mlab-oti.
* Alert_ParserDailyVolumeTooLow.json
* NDT_EarlyWarning.json 
* NDT_GlobalTestRate.json
* Prometheus_SelfMonitoring.json
They are currently loaded in mlab-sanbox, and the originals in mlab-sandbox deleted.
This change also updates the dashboard titles to help categorize related dashboards, e.g. prefixing with "Alert: ", "NDT: ", or "Prometheus: ", respectively.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/174)
> Import dashboards as JSON

- README.md
This change updates documentation to enable autorepair and autoupgrade options when creating a new cluster or node pool.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/178)
> Add autorepair and autoupgrade options to examples

- config/federation/grafana/dashboards/Prometheus_SelfMonitoring.json
This change disables unnecessary legends for a number of panels.
The addition of `"format": "time_series",` appears to be due to later grafana verion adding some default values where there were previously none.
This change also adds the `prometheus_local_storage_rushed_mode` metric to the "Chunks in Memory w/ Persistence Urgency" panel to illustrate when Prometheus is behaving differently due to the "urgency score".
In "rushed mode" typically, the server stops scraping and evaluating rules. This leaves gaps in monitoring and alerting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/177)
> Remove unnecessary legends, add rushed_mode

- config/federation/prometheus/alerts.yml
This change is to address false-positives due to cluster node auto upgrades, such as in:
https://github.com/m-lab/scraper/issues/245
The server was down for less than 5m, so a threshold of 10m should be a better threshold that something needs attention.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/180)
> Update delay for firing ClusterDown alert

- config/federation/prometheus/prometheus.yml.template
The ndt_e2e needs a `scrape_interval` of something like 10m, while we want the ndt_queue script to be run minute (the global default). As far as I can tell from the Prom documentation `scrape_interval` is only valid in the global config sections, and once in each `<scrape_config>` (job) section. So, in order to have them use different `scrape_interval`s this splits the old `script-targets` job into two distinct jobs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/183)
> Splits the script-targets job into two distinct jobs

- config/federation/prometheus/prometheus.yml.template
PR #183 split the script-exporter Prom job into two separate jobs because one (the NDT e2e) test needed a `scrape_interval` of 10m. However, we've come to discover that Prometheus doesn't recommend an interval of more than 2m, and if you have one you start running into the [staleness gotcha](https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness).
I've now modified the script-exporter ndt_e2e.sh script to cache results and return the cached result if it is less than 10m old. With this change, Prom can now start polling it every minute, so we don't need to split the jobs apart. This PR essentially undoes #183.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheu …
> Remerges the script-exporter jobs

- k8s/prometheus-federation/deployments/prometheus.yml
This change adds an explicit version to the gcp-service-discovery docker image.
After fixing a bug earlier today, the "latest" tag in dockerhub is replaced with the new "latest" version. This was fine, but it means if the staging or production instances are restarted they will get the updated version without notice.
By adding an explicit version we can prevent unintended side effects on production environments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/189)
> Add explicit version of gcp-service-discovery docker image

- config/federation/prometheus/prometheus.yml.template
* Adds a new target for the `snmp-exporter` job to scrape the node_exporter instance that is running inside each snmp-exporter VM.  Also, moves the entire `snmp-exporter` job so it sits directly above the `snmp-targets` job for easier reading of the config (grouping like configs).
* Add a new job named `script-exporter` with two targets:
* A target to scrape any metrics the script-exporter exports about its own operation
* A target to scrape the node_exporter instance that runs inside of each script-exporter VM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/190)
> Adds node_exporter targets for snmp-exporter and script-exporter jobs

- config/federation/blackbox/config.yml
Many are currently at 5s, which may be too small, especially for sites where the Internet is less reliable and fast.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/197)
> Changes the timeout for all blackbox_exporter modules to 9s 

- config/federation/grafana/dashboards/NDT_EarlyWarning.json
Previously, the NDT early warning dashboard site- switch panel (second row, second column) did not distinguish between 1g and 10g uplinks. As a result, 10g uplinks were highlighted as overutilized based on 1g thresholds. Note: This has only affected the presentation in that panel. The global percentile checks (top row) use the correct thresholds for both cases.
This change adds new queries specifically for 10g uplink speeds. And, adds speed annotations to the legend to easily identify a line as coming from a 1g or 10g switch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/201)
> Add 1g vs 10g indicators to Switch panel

- .travis.yml
- config/federation/blackbox/config.yml
- config/federation/prometheus/prometheus.yml.template
- deploy_bbe_config.sh
- k8s/prometheus-federation/deployments/prometheus.yml
This PR revives the CS from closed PR #198, since it turns out that we do in fact want IPv6 blackbox_exporter changes, just not from our k8s BBE instance. Instead, the checks will be done through BBE instances running on a Linode VM.
Additionally, this PR adds a small new script, and relevant changes to `.travis.yaml`, which will deploy the BBE config to the Linode VM and then HUP the appropriate instance there so it reads in the new configuration.
This PR also incorporates a new Prometheus scrape job named `blackbox-targets-ipv6` for scraping IPv6 targets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/200)
> Adds script to deploy blackbox_exporter config to Linode VM, adds IPv6 BBE modules

- k8s/prometheus-federation/roles/rbac-kube-lego.yml
The kube-lego ServiceAccount is erroneously missing the directive which scopes it to the kube-lego namespace, which keeps the kube-lego pods from being instantiated on a new cluster. This fixes that problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/205)
> Add missing namespace directive to kube-lego ServiceAccount.

- config/federation/prometheus/alerts.yml
This change includes the "main" nagios-exporter instance in alerts.
To do this, the existing NagiosOamDownOrMissing alert is broken into two parts: NagiosExporterDown and NagiosExporterMissing that checks for explicit conditions on both nagios exporter jobs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/209)
> Add alert to include nagios-exporter

- config/federation/prometheus/alerts.yml
Recently, the nagios-exporter was not responding ( `up == 0`) but there was no alert firing.
Previously, the alerts covered two cases:
* `up` is absent
* `nagios_livestatus_available == 0`, the exporter is running but has incomplete data.
The third case:
* `up == 0` when the nagios exporter has an `up` metric but is nonfunctional.
This PR adds an alert for the third case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/214)
> Add alert case for nagios exporter when `up == 0`

- apply-global-prometheus.sh
- config/federation/grafana/dashboards/Ops_PlatformOverview.json
This PR also modifies `apply-global-prometheus.sh`, changing `kubectl create` to `kubectl replace` when creating the grafana-dashboards configmap to get around an error that was being thrown:
```
+kubectl create configmap grafana-dashboards --from-file=config/federation/grafana/dashboards --dry-run -o json
The ConfigMap "grafana-dashboards" is invalid: metadata.annotations: Too long: must have at most 262144 characters
Script failed with status 1
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/217)
> Adds JSON for Ops_PlatformOverview Grafana dashboard.

- config/federation/grafana/dashboards/Ops_PlatformOverview.json
The current Ops_PlatformOverview Grafana dashboard has a bug. The switch metric panels specifically target the "mlab-oti prometheus" datasource, instead of using the dashboard's datasource template value. This PR fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/220)
> Changes switch metric panels to use datasource template value.

- config/federation/prometheus/alerts.yml
Now that mlab-ns can (and shortly will) rely on Prometheus for service status, we should be monitoring the services that it relies on to be sure they actually exist.  This PR (hopefully) resolves this issue:
https://github.com/m-lab/ops-tracker/issues/361
The services which are getting alerts should match the ones that mlab-ns uses:
https://github.com/m-lab/mlab-ns/blob/master/server/mlabns/util/prometheus_status.py#L12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/221)
> Adds alerts for Prometheus metrics that mlab-ns relies on for service status.

- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
node_exporter was installed on EB via the system package manager. It's a pretty old version (0.13), but sufficient for monitoring basic memory, load and disk usage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/222)
> Adds a scrape job for the node_exporter running on eb.measurementlab.net

- apply-global-prometheus.sh
- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
- k8s/prometheus-federation/deployments/blackbox.yml
In PR #222 I attempted to add alerting for all of our Prometheus blackbox_exporter instances. But what I inadvertently did was to add alerting for individual BBE probes, not the services themselves. This PR should resolve that error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/223)
> Alerting for BBE when the BBE service itself is down, not just probes.

- config/federation/prometheus/alerts.yml
The `count()` function wasn't adding anything useful, was actually totally superfluous, and more importantly was causing needed labels to not be part of the alert.
This should resolve these issues:
https://github.com/m-lab/prometheus-support/issues/227
https://github.com/m-lab/ops-tracker/issues/387
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/229)
> Removes the count() function from the LameDuckMtericMissingForNode alert

- apply-global-prometheus.sh
- k8s/prometheus-federation/deployments/github-receiver.yml
This PR changes the target repo used by the github-receiver when creating github issues for alerts. Rather than creating issues in the "scraper" repo, we will now create alerts in the "dev-tracker" repo.
This resolves issues:
https://github.com/m-lab/prometheus-support/issues/231
https://github.com/m-lab/prometheus-support/issues/129
These changes are prerequisites for enabling routing of issues to either the "dev-tracker" or "ops-tracker" repos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/232)
> Create github issues for alerts in dev-tracker

- apply-global-prometheus.sh
- config/federation/alertmanager/config.yml.template
This change adds a "text" message to slack messages that contains a link to search github issues for open alerts.
This should help responders find the correct issue quickly to update and resolve.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/235)
> Add a link to slack messages with a link to open github alerts

- config/federation/grafana/dashboards/NDT_GlobalTestRate.json
This PR adds a new panel to the NDT: Global Test Rate dashboard that contrasts the "total" NDT tests in a week-over-week format. This makes it easier to see trends over longer periods of time in a single place.
https://grafana.mlab-sandbox.measurementlab.net/dashboard/file/NDT_GlobalTestRate.json?orgId=1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/237)
> Add week-over-week panel for global ndt test rate

- config/federation/prometheus/alerts.yml
- k8s/prometheus-federation/deployments/github-receiver.yml
This change updates the version of the github receiver to enable support for alert routing.
As well, this change adds a `repo=` label to all alert definitions. Initially all repos are set to "dev-tracker" to preserve default behavior. Default behavior should remain unchanged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/238)
> Update version of github receiver to support alert routing

- config/federation/prometheus/alerts.yml
* mlab-ns relies on three specific metrics from the node_exporter instance running on each node: `vdlimit_used`, `vdlimit_total`, `lame_duck_experiment`. There is already an alert for `lame_duck_experiment`. This PR adds an alert for both of the vdlimit_* metrics.
* If SNMP scraping of a switch is failing, we will now get an alert. Currently, we only get an alert if snmp_exporter is down or if an entire metric is missing from all switches.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/239)
> Adds two new alerts: vdlimit_* metrics and SNMP scraping

- config/federation/grafana/dashboards/Ops_PlatformOverview.json
- config/federation/grafana/dashboards/Ops_SwitchOverview.json
* [Fixes a bug in the Ops_PlatformOverview dashboard](https://github.com/m-lab/ops-tracker/issues/373) where the Load15 panels were getting metrics from node_exporters other than the ones running on platform nodes, skewing results.
* Fixes a bug in the Ops_SwitchOverview dashboard where a switch that was missing SNMP metrics would not show up in the Site selectbox.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/240)
> Fixes two smallish bugs in two Ops dashboards

- config/federation/grafana/dashboards/Ops_SwitchOverview.json
Resolves https://github.com/m-lab/ops-tracker/issues/325
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/242)
> Sets the Ops_SwitchOverview dashboard to UTC instead of localtime.

- k8s/prometheus-federation/deployments/node-exporter.yml
This change adds a new DaemonSet for the node-exporter to the prometheus cluster.
With this change it should be possible to get detailed monitoring of whole-node resource utilization. And, with the addition of the `node=` label to pods from https://github.com/m-lab/prometheus-support/pull/248 it should now be possible to discover the history and environment of pod migrations through a k8s cluster over time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/250)
> Add the node-exporter DaemonSet to prometheus cluster

- k8s/prometheus-federation/deployments/github-receiver.yml
An oversight from https://github.com/m-lab/prometheus-support/pull/247 -- the github receiver v0.4 now includes native prometheus metrics, so we want to tell prometheus to scrape this pod.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/251)
> Scrape the github receiver

- config/federation/prometheus/prometheus.yml.template
- k8s/prometheus-federation/deployments/kube-state-metrics.yml
- k8s/prometheus-federation/services/kube-state-metrics-service.yml
This PR updates the kube-state-metrics deployment to the latest version. As well, we define a static config target for the kube-state-metrics-service. We use a service definition to create a cluster-local DNS name. And, we disable service-discovery for the pod as well as the service because kube-state-metric adds labels to metrics that conflict with the labels added automatically by service discovery, e.g. "pod=", "node=", etc.
With this change we will be able to monitor the deployment status of various services, as well as alert on error states such as OOM. https://github.com/m-lab/prometheus-support/issues/213
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/252) …
> Update kube-state-metrics service

- apply-global-prometheus.sh
- k8s/prometheus-federation/deployments/mlabns-stackdriver.yml
This change adds a new deployment specifically for collecting metrics about mlab-ns.
Because mlab-ns is in a separate project from the rest of the prometheus stack we must create a k8s secret used by the stackdriver exporter to authenticate with the mlab-ns project.
The list of `--monitoring.metrics-type-prefixes` is not exhaustive, but represent the ones that look useful and whose values could represent significant shifts due to usage spikes or drops, or internal bugs.
```
logging.googleapis.com/log_entry_count
appengine.googleapis.com/system/network/sent_bytes_count
appengine.googleapis.com/system/instance_count
appengine.googleapis.com/system/cpu/usage
appengine.googleapis.com/memcache/operation_count
appengine.googleapis.com/http/server/response_count …
```
> Add stackdriver exporter for mlab-ns

- config/federation/prometheus/prometheus.yml.template
Scrape metrics from the script-exporter VM using its internal VPC domain name. This PR depends on this PR:
https://github.com/m-lab/prometheus-script-exporter/pull/15
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/254)
> Configures Prom to communicate with the script-exporter using its internal DNS name.

- config/federation/prometheus/prometheus.yml.template
Scrape metrics from the snmp-exporter VM using its internal VPC domain name. This PR depends on this PR:
https://github.com/m-lab/prometheus-snmp-exporter/pull/11
Noteworthy: this also changes one of the label rewrite rules for the snmp-targets job. The old rule was created before we had templated promtheus.yaml.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/255)
> Configures Prom to communicate with the snmp-exporter using its internal DNS name.

- config/federation/grafana/dashboards/Ops_PlatformOverview.json
- config/federation/grafana/dashboards/Ops_PodOverview.json
[Ops_PlatformOverview](https://grafana.mlab-sandbox.measurementlab.net/dashboard/file/Ops_PlatformOverview.json?orgId=1):
* The NDT root filesystem panels was still using nagios_exporter metrics. This PR switches that panel to start using node_exporter metrics.
* I've added a new panel for NDT global test rates. I've set the resolution to 1/10 to speed it up, and it's purpose is just to give the operator a rough idea of major traffic events.
[Ops_PodOverview](https://grafana.mlab-sandbox.measurementlab.net/dashboard/file/Ops_PodOverview.json?orgId=1&var-datasource=mlab-oti%20prometheus&var-pod=ams01&var-node=All):
* This is a new JSON dashboard that has been in development for some months. At a glance, it lets an operator know what is up and down through color coding.
---
This change …
> Fixes Ops_PlatformOverview dashboard and adds Ops_PodOverview

- k8s/prometheus-federation/deployments/grafana.yml
- k8s/prometheus-federation/deployments/prometheus.yml
This PR upgrades Grafana to v5.1.4. Because the [default Grafana Docker images now specify a UID of 472 (instead of 104)](http://docs.grafana.org/installation/docker/#user-id-changes) the permissions of existing files in GKE persistent storage are wrong, meaning that you can either figure out how to change the permissions all those files, or you can simply run the container as UID 104. This PR takes the latter approach, since it seemed much easier, but does mean that we will be carrying forward some non-default configuration baggage for the Grafana container.
This PR also adds a new set of Prom targets to the `gcp-discovery-service` config: `switches_ping.json`. These new targets are use the `icmp` module of blackbox_exporter.
--- …
> Upgrade Grafana to v5.1.4 + adds GCP discovery for switch ping  BBE probes.

- config/federation/grafana/dashboards/Alert_ParserDailyVolumeTooLow.json
- config/federation/grafana/dashboards/MLABNS_Stackdriver.json
- config/federation/grafana/dashboards/NDT_EarlyWarning.json
- config/federation/grafana/dashboards/NDT_GlobalTestRate.json
- config/federation/grafana/dashboards/Ops_PlatformOverview.json
- config/federation/grafana/dashboards/Ops_PodOverview.json
- config/federation/grafana/dashboards/Ops_SwitchOverview.json
- config/federation/grafana/dashboards/Pipeline_Embargo.json
- config/federation/grafana/dashboards/Pipeline_PT.json
- config/federation/grafana/dashboards/Prometheus_SelfMonitoring.json
- config/federation/grafana/grafana.ini
- config/federation/prometheus/alerts.yml
- k8s/prometheus-federation/deployments/grafana.yml
Currently, all of the Grafana dashboard URLs in alerts.yaml are using an old v4.x format, but we are now running v5.x which has a different URL format for resources. This PR fixes that. It also updates several other URLs which were broken or non-standard in some way e.g., using http instead of https, using `status.<url>` URLs instead of `prometheus.<url>`.
Additionally, with v5.x, Grafana now formats the JSON for a dashboard significantly different. This PR updates the format. This was done by simply opening the dashboard JSON in Grafana and pasting it into the JSON file in clone of the repo. The diffs are large, but the dashboards should be functionally and visually the same. The only dashboard which I altered was Ops_PodOverview, and this was to take advantage of the new layout …
> Fix dashboard URLs in alerts.yaml + updates JSON dashboards to use 5.x formatting

- apply-global-prometheus.sh
- k8s/prometheus-federation/deployments/prometheus.yml
I recreated this branch and pull request in order to clean it up after getting a little too much cruft in my private development fork. This adds the configmap-reload service to the Prometheus deployment, and integrates the feedback from https://github.com/m-lab/prometheus-support/pull/228.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/264)
> Add configmap-reload to Prometheus deployment.

- config/federation/alertmanager/config.yml.template
NDT health checks depend on the script-exporter. If the script-exporter is down, then all NDT health checks will report as down too. Don't alert on NDT when the script-exporter is down.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/266)
> New AlertManager inhibit rule for TooManyNdtServersDown

- config/federation/bigquery/bq_ndt_worldmap.sql
- config/local/grafana/SETUP_WORLDMAP.md
- k8s/prometheus-federation/deployments/bigquery-exporter.yml
This change adds a new bigquery exporter query that calculates the median upload and download rates for a day based on client lat/lon locations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/267)
> Add median metrics for Grafana WorldMap plugin 

- config/federation/alertmanager/config.yml.template
If the script-exporter is down, then there is no point in alerting on missing script-exporter metrics, nor on things that rely on the script-exporter.  Same with the snmp-exporter. My syntax here is based on my reading of the [AlertManager documentation](https://prometheus.io/docs/alerting/configuration/#inhibit_rule).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/269)
> SNMP inhibit rule + additional script-exporter inhibit rule

- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
We don't rely on Nagios for much any longer (only ReBot still uses it for anything and that is minimal), so we don't need to be scraping the nagios-exporter on either eb.measurementlab.net or nagios-oam.measurementlab.net. 
Additionally, we don't even need to be running the nagios-oam VM any longer. All it does is monitor eb.measurementlab.net, mirror.measurementlab.net and dns.measuremenlab.net, and very basically. EB was already running Prometheus node_exporter and being scraped. I have installed node_exporter on both  DNS and MIRROR as well. This PR adds scrape jobs for those node_exporters.
This PR also adds alerts for those new node_exporter scrape jobs.
--- …
> Removes scrape jobs for the nagios-exporter, adds new node-exporter scrape jobs.

- apply-global-prometheus.sh
- config/federation/prometheus/prometheus.yml.template
This change adds metric_relabel_config rules to the legacy-targets job so that sidestream metrics convert experiment indexes from the numeric value to human readable values while taking into account the legacy network remapping applied to some machines.
The relabel rules were created using the patch in https://github.com/m-lab/operator/pull/244
The prometheus-federation-config must now be created using `kubectl replace` for the same reason that we use `replace` on the Grafana dashboards -- the size of this file is now large enough to prevent storage backups in the configmap annotation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/278)
> Add metric_relabel_configs for sidestream exporter labels

- config/federation/vms/legacy-targets/vms_ndt_cloud.json
For now we will use explicit monitoring configs for the TYO & demo VMs.
This PR adds a new legacy-targets vms_ndt_cloud.json file for ndt-cloud targets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/280)
> Add monitoring targets for ndt-cloud VMs

- config/federation/vms/legacy-targets/vms_ndt_cloud.json
Right now we only have ad-hoc monitoring of the ndt-cloud prometheus metrics.
Ultimately, NDT-cloud instances will be auto discovered using prometheus service discovery. However, until we advance the networking to the prometheus instance running on the k8s platform cluster, we will rely on external and static target configs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/285)
> Add ad-hoc monitoring of demo machines

- config/federation/vms/legacy-targets/vms_ndt_cloud.json
It turns out that lga02 is not suitable for the demo due to legacy network remap configuration. We've replaced it with mlab3.lga03.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/286)
> Update demo site to lga03

- config/federation/alertmanager/config.yml.template
There were two likely issues:
* Using a list instead of a map
* Using the same key (`alertname`) twice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/292)
> Fixes a bug in the AM configuration that was causing it to crash loop.

- config/federation/grafana/dashboards/Prometheus_SelfMonitoring.json
This adds new panels to display metrics for:
prometheus_engine_query_duration_seconds
prometheus_local_storage_indexing_queue_length
prometheus_local_storage_indexing_batch_duration_seconds
And removes the panel for prometheus_local_storage_memory_series
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/296)
> Update self-monitoring dashboard

- config/federation/prometheus/alerts.yml
This change increases the timeout for the SnmpScrapingDownAtSite alert. It produces too many false positives.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/298)
> Increase delay before firing alert

- config/federation/prometheus/alerts.yml
This change adds a new alert for ETL_ParserPanicNonZero. All panics are due to bugs that should be fixed. A small number of panics could go unnoticed without an active alert.
As well, this change increases the timeout for SnmpScrapingDownAtSite to reduce false positives.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/301)
> Alert for ETL panics & increase timeout for SnmpScrapingDownAtSite

- config/federation/prometheus/alerts.yml
This alert adds a basic check to assert that the annotator service is known to prometheus and online.
A future change will add a BQ exporter query and new alert to verify that the annotator is working correctly according to BQ data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/302)
> Add new alert for the annotator

- config/federation/bigquery/bq_ndt_annotation.sql
- config/federation/prometheus/alerts.yml
- k8s/prometheus-federation/deployments/bigquery-exporter.yml
This change adds a new BQ exporter query to measure the percentage of NDT tests successfully  annotated with latitude and longitude.
The typical value for this is around 0.9994. The alert fires when the value is less than 0.99.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/303)
> Add bq_ndt_annotation query and alert

- k8s/data-processing-cluster/deployments/prometheus.yml
This pull request updates the Prometheus instance on the dataprocessing cluster from v1.8.2 to v2.3.2. It also revises the command-line arguments to Prometheus to bring them in line with changes to the new version (including the removal of most storage-related options) and mounts a new directory in the prometheus-storage volume to the new default location for the time-series database.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/304)
> Sandbox prometheus 2.x dataprocessing upgrade

- config/federation/prometheus/alerts.yml
Now that the GMX is working, this PR adds machine and site state metrics as conditions to a number of alerts. Specifically, the condition was added to any alert that already had a `lame_duck_node` condition. It was also added to two other alerts where it would be useful: `SwitchDownAtSite` and `CoreServices_CollectdMlabDown`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/307)
> Adds a gmx_machine_state{}==1 condition to a number of alerts.

- config/federation/prometheus/alerts.yml
It doesn't really belong there. And the change I made in a previous PR setting the condition to `lame_duck_node == 1` was wrong too, since the purpose was to return not just ones where it was 1, but all instances where it was set at all.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/311)
> Removes gmx_machine_maintenance condition from LameDuckMetricMissingForNode alert.

- k8s/prometheus-federation/deployments/kube-lego.yml
- k8s/prometheus-federation/deployments/nginx.yml
- k8s/prometheus-federation/roles/rbac-external-dns.yml
- k8s/prometheus-federation/roles/rbac-kube-lego.yml
- k8s/prometheus-federation/roles/rbac-nginx.yml
- k8s/prometheus-federation/services/nginx.yml
The prometheus-federation cluster doesn't currently have enough resources to make it worth fragmenting the namespace, and having it fragmented at this point makes working with it a bit more tedious.
The impetus behind making this change is that the external-dns deployment is in the default namespace while the rbac role for it is in the external-dns namespace, causing the deployment to fail because of a permission issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/312)
> Moves all resources into the default namespace in the prometheus-federation cluster.

- config/cluster/prometheus/prometheus.yml
- config/federation/prometheus/prometheus.yml.template
With the 1.x series, prometheus provided no hints about whether the pod was part of a DaemonSet or ReplicaSet. The 2.x series does.
This change uses this feature to provide more reliable relabel rules for extracting the deployment name for all pods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/320)
> Update deployment relabel rule to distinguish DaemonSet & ReplicaSet

- config/federation/grafana/dashboards/Prometheus_SelfMonitoring.json
This change adds initial panels for prometheus2, specifically, CPU & RAM. We can improve this over time. But this is sufficient for observing the resource utilization of the new configuration before & after production release.
Changed dashboard:
https://grafana.mlab-sandbox.measurementlab.net/d/sVklmeHik/prometheus-self-monitoring?orgId=1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/321)
> Add prometheus2 metrics to self-monitoring dashboards

- config/federation/prometheus/prometheus.yml.template
Yeah, looks like the auto-discovery won't just work on its own. I added a parameter to send the alerts to the internal cluster address of the alertmanager instance, an approach which seems to work just fine on sandbox.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/322)
> Add static config for sending alerts from Prometheus to Alertmanager.

- k8s/data-processing-cluster/deployments/prometheus.yml
Evidently the last PR to update the DPC prometheus config was never reloaded. This change adds the reload-config sidecar to the DPC prometheus instance so that this doesn't happen again.
As well, the change includes a longer default retention time and enables the "lifecycle" option, required for the "/-/reload" operation to be enabled.
Finally, this change specifies the data path to the locally data volume so that data is persisted across restarts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/324)
> Add configmap-reload sidecar for data-processing-cluster prometheus instance

- config/federation/grafana/dashboards/Ops_PlatformOverview.json
- config/federation/grafana/dashboards/Ops_PodOverview.json
- config/federation/grafana/dashboards/Ops_SwitchOverview.json
I'm not sure what happened along the way, but apparently `label_values(hostname)` stopped working at some point, breaking the variables in several Ops dashboards. This PR replaces that with `label_values(site)`, which is more efficient anyway, since it will return the site name (e.g., abc01) without having to apply a regex to it to get the value we want.
While I was at it, I noticed that the OpsSwitchOverview dashboard had no datasource select box, which is a standard now, so I added it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/326)
> Updates dashboards to use label_values(site) instead of broken hostname value.

- k8s/prometheus-federation/deployments/prometheus.yml
This modifies the reset-perms initcontainer to only run `chmod` on the targets, and not on the data directory, in order to cut down on execution time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/327)
> Sandbox initcontainer improvements

- apply-cluster.sh
- k8s/prometheus-federation/deployments/prometheus.yml
Previously it was using the public URL, and for reasons that we don't understand yet was receiving a 504 Gateway Timeout error. Apparently using the internal service URL gets around this issue.
It also removes some obsolete commented-out code that previously reloaded Prom through the public URL. This isn't necessary now that we have the configmap-reload sidecar container, which does this automatically.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/328)
> Changes the configmap-reload container to use the internal service URL.

- apply-global-prometheus.sh
- config/federation/blackbox/config.yml.template
- config/federation/grafana/grafana.ini
- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
This PR adds basic HTTP Prometheus blackbox_exporter checks for the services running in the prometheus-federation k8s cluster. It also adds an alert for when one of them goes down for more than 30m.
*Note*: I disabled HTTP Basic Auth for Grafana so that probes would work to `/login` without receiving a 401 reply. I don't think we are using Basic Auth for anything in Grafana, but mention this change here just in case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/329)
> Adds BBE checks, and alerts, for core services running behind our nginx load balancer.

- config/federation/grafana/dashboards/Alert_DownloaderIsFailingToUpdate.json
- config/federation/prometheus/alerts.yml
This change adds a new, simple dashboard for the DownloaderIsFailingToUpdate alert.
The source was generated from the version currently running in mlab-oti:
https://grafana.mlab-oti.measurementlab.net/d/ZGuYht1mk/alert-downloaderisfailingtoupdate
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/330)
> Add downloader dashboard

- config/federation/grafana/dashboards/NDT_EarlyWarning.json
- config/federation/grafana/dashboards/Pipeline_Gardener.json
- config/federation/grafana/dashboards/Pipeline_Parser.json
This change adds two new dashboards and fixes another.
* Adds a generic parser dashboard for multiple parsers.
* Adds an initial Gardener dashboard for the various gardener instances.
* Fixes the use of label_values to use a label that's still in our dataset
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/331)
> Add dashboards for Gardner & Parsers

- config/federation/grafana/dashboards/Pipeline_Gardener.json
This change adds a new panel to the Gardener dashboard for the daily reprocessing SLO: Tasks/Day. This also changes the query used by the Tasks/Hour panel to average over a single hour. And, in both cases the rates are aggregated by the deployment name to create consistent numbers across re-deployments.
https://grafana.mlab-sandbox.measurementlab.net/d/eBbUW6oik/pipeline-gardener?orgId=1&from=now-7d&to=now&var-datasource=Data%20Proc%20(mlab-oti)&var-deployment=All
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/336)
> Add SLO panel to Gardener, use increase for hourly and daily

- apply-global-prometheus.sh
- config/federation/alertmanager/config.yml.template
- config/federation/bigquery/bq_gardener_parse_time.sql.template
- config/federation/prometheus/alerts.yml
- k8s/prometheus-federation/deployments/bigquery-exporter.yml
This change adds a BQ exporter query (bq_gardener_parse_time.sql.template) to define the metric used by a new alert  Gardener_ParseTimeDifferenceTooOld. As well, this change adds additional metadata to the alertmanager messages sent to slack.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/338)
>  Add Gardener_ParseTimeDifferenceTooOld alert

- k8s/prometheus-federation/deployments/cadvisor.yml
kube-state-metrics provides static information about containers, e.g. resources allocated, restart counts, pending or available.
And, while early versions of the GKE kubelet appeared to include container resource metrics, over time that functionality has been removed or otherwise made unavailable.
This change adds the cAdvisor container to the prometheus federation cluster to collect per-container resource utilization metrics such as:
* container_cpu_usage_seconds_total
* container_memory_usage_bytes
* container_network_{receive,transmit}_bytes_total
* container_fs_{reads,writes}_bytes_total
* and others.
With these it will be possible to build richer dashboards inspecting the resource utilization of individual containers, aggregate pods, or all pods on a node.
--- …
> Add cadvisor for per-container or per-pod resource utilization

- config/federation/alertmanager/config.yml.template
- config/federation/prometheus/alerts.yml
- k8s/prometheus-federation/deployments/alertmanager.yml
This change includes significant updates to the alertmanager (version upgrade), the alert definitions by providing a standard set of alert annotations: "summary", "description" and optional "dashboard". In turn, these standard annotations are used in a new alertmanager configuration, and we now define slack "actions" to create buttons on alerts that link to helpful actions: Dashboard or "Create Dashboard", Github, and "Add Silence" for firing alerts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/345)
> Upgrade Alertmanager, Add Slack buttons, normalize Alert annotations

- k8s/prometheus-federation/deployments/alertmanager.yml
Correct a typo missed in https://github.com/m-lab/prometheus-support/pull/345
I failed to verify behavior in sandbox. All my testing from #345  was done from a local deployment. The new version of alertmanager requires double `--` prefix before long options.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/346)
> Add long flags

- config/federation/alertmanager/config.yml.template
Evidently, alertmanager was failing to parse the yaml due to:
```
level=error ts=2018-10-23T19:34:22.591921967Z caller=main.go:325 msg="Loading configuration file failed" file=/etc/alertmanager/config.yml err="yaml: line 101: found character that cannot start any token"
```
And,
```
level=error ts=2018-10-23T19:43:04.394886283Z caller=main.go:325 msg="Loading configuration file failed" file=/etc/alertmanager/config.yml err="yaml: line 102: did not find expected key"
```
I've tried removing all tabs and guaranteeing that an extra space is in the github url. This does seem to work in sandbox now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/347)
> Remove all tabs and extra new lines.

- config/federation/alertmanager/config.yml.template
This change updates the alertmanager slack alert format to remove unnecessary text and better place and format the summary and description text.
As well, the description text includes a static link to edit the alerts.yaml file via github.
Buttons are ordered so that their position is consistent between "FIRING" and "RESOLVED" states.
The template logic for construction of the "Add Silence" button is much clearer.
Example image:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/351)
> Update format and make templates more readable

- config/federation/grafana/dashboards/Pipeline_Gardener.json
This introduces a panel that shows the submission rate, in bytes/hour, and the average filesize in bytes.
There is also now a file count metric, which I will add in a future PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/353)
> Add byte-rate panel

- config/federation/grafana/dashboards/Pipeline_Gardener.json
This change updates the Gardener dashboard to include:
* Reprocessing period bar chart (based on BQ metrics)
* Simpler datasource selection based on 'Project'
* Threshold lines at 12hr on the "Time in State" panel
* Completes changes recommended in https://reviewable.io/reviews/m-lab/prometheus-support/353
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/357)
> Add reprocessing period bar chart - update byte & file rate panels

- config/federation/prometheus/alerts.yml
We observed these three alerts to fire on nodes booted from ePoxy, but which hadn't yet been configured to export the necessary metrics. We don't want these firing when the nodes/site are in maintenance mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/360)
> Adds GMX condition on three alerts.

- config/federation/bigquery/bq_gardener_parse_time.sql.template
This change updates the calculation on the max-min `parse_time` to return a fractional number of days.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/361)
> Change difference_days to fractional value

- README.md
- config/federation/kubeip/roles.yml
- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
- k8s/prometheus-federation/deployments/kubeip.yml
- k8s/prometheus-federation/deployments/snmp-exporter.yml
- k8s/prometheus-federation/roles/rbac-kubeip.yml
- k8s/prometheus-federation/services/snmp-exporter-service.yml
This pull request adds the Prometheus snmp_exporter as a Kubernetes deployment. It also includes a gcp-service-discovery sidecar to automatically pull down the SNMP config from the switch-config bucket, and a configmap-reload sidecar to watch for changes and reload the exporter.
In order to facilitate static outbound IPs for switch whitelisting, it is necessary to create a new nodepool and assign static IPs to it. This pull request also includes a kubeIP deployment (which runs separately on the main nodepool) to monitor the nodes of the static nodepool and assign them IPs. Because setting up the nodepool and the necessary credentials for kubeip is outside the scope of Kubernetes, instructions on doing so via gcloud have been added to the README.
As currently running, before switching over …
> snmp_exporter w/ static outbound IP

- config/federation/kubeip/roles.yml
This change adds an additional permission needed by kubeip for some network configurations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/374)
> Add new kubeip permission compute.networks.useExternalIp

- config/federation/prometheus/prometheus.yml.template
TBR -- until all switches are updated with the new IP whitelist, we should continue to use the snmp-exporter VMs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/376)
> Use snmp exporter VM until all VMs are updated

- config/federation/bigquery/bq_gardener_parse_time.sql.template
Before starting the long term plan for the traceroute parser (https://github.com/m-lab/etl/issues/590), we are disabling the etl gardener instance for traceroute (https://github.com/m-lab/etl-gardener/pull/119). This change removes traceroute from the metrics that we alert on for the gardener SLO.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/378)
> Disable collection of gardener traceroute metrics

- config/federation/prometheus/alerts.yml
This change updates the repo that alerts are routed to to better match the actual owners.
This change also modifies some yaml line continuation characters from `|` to `>` to better integrate with slack markdown.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/377)
> Align alert repos with actual owners

- config/federation/prometheus/alerts.yml
This change updates the ETL panic alert to use a rate rather than the absolute count so that an instance can continue running without firing an alert if it only ever experiences a finite number of panics.
With this change the instance would have to have a non-zero increase in panics for more than 5m. So, this would not alert on isolated panics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/379)
> Change condition to use rates

- config/federation/prometheus/prometheus.yml.template
After updating all switches with the new kubeip static IPs, https://github.com/m-lab/ops-tracker/issues/551 this change modifies the default prometheus configuration to scrape the local snmp exporter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/380)
> Use snmp service running on GKE cluster

- config/federation/prometheus/alerts.yml
This change adds two new alerts to address and prevent issues encountered during a recent outage at mlab1.nuq03 - https://github.com/m-lab/prometheus-support/issues/382
`Scraper_InconsistentDeployment` checks for machines that have an inconsistent number of deployments (corresponding to the number of rsync_modules that should be found on every machine).
`NPAD_VdlimitTooMuchUsedDisk` checks whether NPAD has more disk used than scraper could collect in the worst case for paris-traceroute.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/384)
> Add new alerts for recent scraper outage

- README.md
A project must be selected explicitly before running kubectl, or it will run in the previously selected project (which may or may not be the one we want to operate on).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/389)
> Add instructions to select project before running kubectl to README.md.

- config/federation/grafana/dashboards/Ops_PlatformOverview.json
In addition to this, this commit also makes sure that GMX status is taken into
account when displaying the list of nodes and sites that are down right now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/388)
> Add GMX maintenance mode and Rebot metrics to Platform Overview dashboard.

- config/federation/prometheus/prometheus.yml.template
This will make Prometheus scrape SNMP metrics from the instance deployed on GKE again.
It was originally reverted because the snmp-exporter service was failing to start, thus metrics could not be collected yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/391)
> Revert "Revert "Use snmp service running on gke cluster""

- config/federation/grafana/dashboards/Pipeline_Batch.json
This adds request status counts from the v2 GetAnnotations api to the annotator error panel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/383)
> Add v2 status counts

- config/federation/grafana/dashboards/Ops_RebotMonitoring.json
This dashboard contains the following Rebot metrics:
- Total rebooted nodes
- Rebooted in the last 24 hours
- Offline nodes chart
- Offline nodes list
- Offline sites list
Additionally, since I thought it would be useful to have them in one
place, it includes Nodes and Sites currently in GMX maintenance mode.
Possible ideas for further metrics to show:
- Failed DRAC operations
- Most frequently rebooted nodes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/390)
> Create dashboard "Ops: Rebot Monitoring". 

- config/federation/prometheus/alerts.yml
This PR updates alerts.yml to change the disk usage threshold from 3.5GB to 9GB, since the condition which previously led us to set it to 3.5GB just happened once and on a different slice.
It also adds a mention of the `paris-traceroute.log` files which keeps growing indefinitely.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/394)
> Change high disk usage threshold for NPAD to 9GB

- config/federation/grafana/provisioning/datasources/k8s-platform_mlab-oti.yml.template
- config/federation/grafana/provisioning/datasources/k8s-platform_mlab-sandbox.yml.template
- config/federation/grafana/provisioning/datasources/k8s-platform_mlab-staging.yml.template
This change adds pre-defined data sources for the k8s platform instances of  prometheus.
This change includes a definition for mlab-oti for convenience even though that deployment does not yet exist.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/395)
> Add k8s-platform data sources

- k8s/prometheus-federation/deployments/gmx.yml
There was [a bug in GMX](https://github.com/m-lab/github-maintenance-exporter/issues/15), which has since been resolved, so we need a new version of the GMX image deployed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/396)
> Bumps GMX image tag from v0.1 to v0.1.2, which is a bugfix version.

- config/federation/grafana/dashboards/K8s_MasterCluster.json
- config/federation/grafana/dashboards/K8s_NodeOverview.json
- config/federation/grafana/dashboards/Ops_PlatformOverview.json
The tweaks to the Ops_PlatformOverview are mostly formatting. The 2nd row was getting rather crowded, and the reboot time of nodes booted in the last 24h was a timestamp. This PR moves most of the singlestat metrics to the first rows, spreads out the second row and changes the timestamp to a human-readable date.
There are two new k8s platform dashboards, which are both still works in progress, but this is a start for something in version control. One is for [monitoring the master nodes](https://grafana.mlab-sandbox.measurementlab.net/d/Uu56HtIfb/k8s-master-cluster?orgId=1&var-datasource=k8s%20platform%20(mlab-staging)&var-master=All), and the other is for [monitoring regular cluster nodes](https://grafana.mlab-sandbox.measurementlab.net/d/oOu1IUlmz/k8s-node-overview?orgId=1&var-datasource= …
> Smalls tweaks to Ops_PlatformOverview, plus two new k8s dashboards.

- config/federation/grafana/dashboards/Ops_PlatformOverview.json
A recent update I made to the Ops_PlatformOverview dashboard mistakenly placed a table panel in the top single-stat row, which is ugly and doesn't really fit. This PR fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/401)
> Removing a table panel from the single-stat row

- config/federation/prometheus/prometheus.yml.template
This change adds a new job to scrape the epoxy-boot-api server.
This change is necessary because the epoxy server no longer runs in AppEngine and gcp-service-discovery will no longer automatically discover it. We could one day enable GCE service discovery (natively supported by prometheus) if that is better.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/404)
> Add job to scrape the GCE VM epoxy-boot-api target

- k8s/prometheus-federation/deployments/prometheus.yml
This change includes a new version of the gcp-service-discovery, which now collects and exports Prometheus metrics related to it's behavior and environment. This also increases the CPU alloc for that container to make sure it is not CPU starved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/397)
> Update version of gcp-service-discovery and increase CPU alloc

- config/federation/grafana/dashboards/Cloud_AppEngine.json
- config/federation/prometheus/alerts.yml
This change adds two new alerts and a dashboard for the number of AppEngine versions (which are limited to 210 per project) or too many instances running but not serving and wasting resources.
These alerts will continue to verify correct behavior once we handle these cases with automation.
Dashboard in sanadbox: https://grafana.mlab-sandbox.measurementlab.net/d/Yor77urmk/cloud-appengine?orgId=1&var-datasource=Prometheus%20(mlab-sandbox)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/407)
> Add alerts and dashboard for excessive AppEngine versions or inactive instances

- config/federation/grafana/dashboards/Boot_Machines.json
- config/federation/grafana/dashboards/Boot_ePoxy_Server.json
- config/federation/prometheus/alerts.yml
This change adds a new alert for the epoxy server itself to make sure that it is online and metrics exist.
This also includes a basic target dashboard for the alert.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/413)
> Add alert and dashboard for the epoxy server.

- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
This change adds a static target to the prometheus config to monitor the prometheus instance running in the k8s platform master cluster.
Ultimately, we should remove this static config in favor of the `federation-targets` monitoring once we trust that the shorter wait time in the `ClusterDown` alert is safe.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/416)
> Add monitoring and alert for prometheus in cluster master

- config/federation/prometheus/alerts.yml
The previous expression did not work correctly.
This change uses the more common pattern in our alerts to check for 'down or missing' condition.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/417)
> Fix down or missing alert for k8s prometheus

- config/federation/prometheus/alerts.yml
Machines with known issues should not cause this alert to fire.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/418)
> Make epoxy machine boot failure GMX aware

- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
This PR aims to at least partially resolve issue m-lab/k8s-support#142. It expands the scrape job that currently exists for the k8s-prometheus instances by using a new `/federate` metrics path and selecting information about all jobs.
This PR also adds three new alerts for jobs that may be down or missing:
* node-exporter
* cadvisor
* ndt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/420)
> Expands k8s-prometheus scrape job and adds three new k8s-platform alerts

- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
This fixes a bug in the previous alerts which were looking for a `job="platform-cluster`, which didn't exist for the specified metrics. This PR adds back the `cluster=platform-cluster` label to all metrics scraped from the k8s platform cluster Prometheus instance so that we can reliably select for them and only them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/421)
> Readds the cluster=platform-cluster label to all federates metrics from k8s cluster

- .travis.yml
This change adds support for the more common release version tags matching patterns like `^v[0-9]+.[0-9]+.[0-9]+`. We've accidentally used this form for recent releases and failed because later stages depended on earlier stages that were skipped.
Now, all production conditions are identical.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/425)
> Support simple style version tags for prod releases

- config/federation/prometheus/prometheus.yml.template
mlab-ns needs `lame_duck_experiment` metrics, but on the platform-cluster, that metric currently only exists as a fake metric that will always be 0 in order to avoid alerts. These days experiments will natively export metrics, one of which will be `lame_duck_experiment`, as does the ndt-server running on the platform cluster. This PR adds that metric to the platform-cluster scrape job.
Additionally, a new label of `experiment=ndt.iupui` is added, since current mlab-ns queries used that label.
This PR should resolve m-lab/k8s-support#169.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/427)
> Scrape lame_duck_experiment metrics from the platform cluster

- config/federation/prometheus/prometheus.yml.template
This will allow mlab-ns, and other things, to query the lame-duck status of a k8s platform node.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/435)
> Scrapes kube_node_spec_taint metric from platform cluster federation job.

- config/federation/prometheus/prometheus.yml.template
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/436)
> Scrapes kube_node_spec_taint{key='lame-duck'} instead of the value.

- config/federation/prometheus/alerts.yml
Another possible place to fix this would be in the operator repo by simply not [generating rsyncd blackbox targets for staging patterns](https://github.com/m-lab/operator/blob/master/generate_prometheus_targets.sh#L46). The reason I'm not choosing that alternative is because it will become tedious to unworkable as we incrementally start transitioning the production platform. It's probably best to modify the alerts themselves.
This PR works around the fact that mlab4s no longer have scraper instances and don't run rsyncd either. Previously, the (very reasonable) assumption for the alert `RsyncRunningWithoutScraper` was that all nodes should be running rsyncd for all experiments. Our Prometheus instance is still monitoring for rsyncd on mlab4, even though it doesn't exists there. This …
> Make sure that rsyncd is up before firing alert RsyncRunningWithoutScraper

- .travis.yml
- apply-grafana-dashboards.sh
- config/federation/grafana/dashboards/K8s_EtcdOverview.json
- config/federation/grafana/dashboards/K8s_SiteOverview.json
- config/federation/grafana/dashboards/Pipeline_Batch.json
The main intention of this PR is to introduce a new dashboard for monitoring the status and health of our etcd cluster: K8s_EtcdOverview.
This PR also makes a couple of small fixes and improvements to the existing K8s_SiteOverview dashboard.
Along the way, adding the dashboard [once again threw us up against the 1MB size limit of a ConfigMap](https://github.com/m-lab/prometheus-support/issues/218) object in k8s (apparently an etcd limitation, not a k8s one). This PR implements another mitigation, not a solution, by minifying the JSON dashboards. This reduces the size of the current ConfigMap from around 1.1MB to around 650KB. This will buy us more time.
This PR also standardizes how Travis deployments are are triggered by modifying the `on:` configuration. In the past @stephen-soltesz had …
> Adds new K8s_EtcdOverview dashboard + fixes K8s:SiteOverview dashboard

- config/federation/grafana/dashboards/K8s_SiteOverview.json
Previously it was using the old label 'app'. Also updates the 'pod' template variable to use that label too.
Additionally, fixes a few queries to not use regexes, but instead use FQDNs when matching node names.
Related to PR m-lab/k8s-support#187.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/441)
> Modifies K8s:SiteOverview dashboard to use the new label 'workload'

- config/federation/grafana/dashboards/K8s_WorkloadOverview.json
- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
- config/federation/prometheus/rules.yml
This PR implements a number of, hopefully, useful etcd alerts for the platform cluster. In order to make these alerts possible, some additional metrics were added to the `platform-cluster` federation scrape job.
This PR also adds a new Grafana dashboard, "K8s: Workload Overview", which gives fairly high level view of pods and container resource utilization (currently CPU, memory, network). It also includes some information about desired vs current pods for a workload.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/442)
> Platform cluster etcd alerts + new WorkloadOverview dashboard

- config/federation/prometheus/prometheus.yml.template
This PR removes the Rebot instance on EB from the scraping targets list since Rebot is being migrated to GKE.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/449)
> Stop scraping Rebot instance on EB.

- k8s/prometheus-federation/deployments/reboot-api.yml
This PR adds the `prometheus.io/scrape` annotation to `deployments/reboot-api.yml` and exposes the relevant containerPort.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/448)
> Add Prometheus metrics scraping for Reboot API.

- config/federation/prometheus/alerts.yml
There is no job='rebot' anymore, but we can check if metrics are being scraped with run='rebot'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/454)
> Change Rebot_MissingMetrics to use run='rebot'

- config/federation/prometheus/alerts.yml
This PR replaces the NPAD-specific alert with a generic alert on disk usage > 80% for a given vserver.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/456)
> Replace NPAD_VdlimitTooMuchUsedDisk with a more generic alert.

- config/federation/grafana/dashboards/Ops_RebotMonitoring.json
The query has been updated to the current version used by Rebot and
the explicit datasource definition has been removed, since now there's
a Rebot instance for each environment - thus "default" is the right choice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/457)
> Update Ops_RebotMonitoring dashboard to reflect reality

- k8s/prometheus-federation/deployments/reboot-api.yml
This PR makes sure the Reboot API will only run on nodes with `outbound-ip: static` - i.e. nodes that have a static IP, managed by `kubeip`. This is necessary so we can enable source IP-based firewall rules on switches.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/458)
> Make sure reboot-api will only be deployed on nodes with a static IP.

- k8s/prometheus-federation/deployments/snmp-exporter.yml
Currently, fetching the snmp-exporter config file from GCS is implemented in a very hackish manner which mostly works, but is overly complicated. This PR uses the new gcs-downloader Docker container that @stephen-soltesz created to fetch the config file from GCS periodically.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/459)
> Use new gcs-downloader container to fetch snmp-exporter config file

- k8s/prometheus-federation/deployments/snmp-exporter.yml
This PR applies the same configuration used in `blackbox-server` to avoid that two pods are scheduled to run on the same node.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/460)
> Prevent two snmp-exporter pods running on the same node.

- config/federation/grafana/dashboards/K8s_MasterCluster.json
The load average singlestat panels were not instant values, causing multiple series errors in some cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/461)
> Fixes a small bug in k8s:MasterCluster dashboard

- config/federation/prometheus/alerts.yml
Currently, alerts for down pods are hard coded for a few specific Deployments and DaemonSets. This is not idea, since it requires adding a new alert rule every time we deploy a new Deployment of DaemonSet, or rename an existing one. This PR removes the hard coded alerts and replaces it with a new alert that will fire if _any_ pod is down from any Deployment of DaemonSet for a configured period of time (currently 1h).
Additionally, new alerts were added for missing DaemonSets and Deployments. These are hard coded, since you can't ask if `.+' is absent. There is now an alert of this type for all currently deployed DaemonSets.
This PR should resolve issue m-lab/k8s-support#192.
--- …
> Adds more alerts for missing workloads + makes down pod alert generic 

- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
This PR adds two new alerts for the cases where a Deployment has fewer replicas than desired, or where a DaemonSet has fewer pods scheduled than the number desired. In addition to the new alert rules, the metrics necessary for these alerts has to be added to the platform-cluster federation scrape job.
This PR should resolve issue m-lab/k8s-support#192.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/464)
> Adds new alerts for the condition where desired pods != current number scheduled

- config/federation/prometheus/prometheus.yml.template
This PR adds the "site" label to all the `blackbox-exporter` targets, extracting that from "machine" with a regex. This allows us to simplify several queries where to get the site we have been using `label_replace`.
Tested in sandbox, `probe_success{job="blackbox-targets",site=""}` gives an empty result set - all the metrics have the `site` label.
Related to https://github.com/m-lab/prometheus-support/issues/92 but I'm not sure this would close that issue since it's limited to blackbox-exporter targets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/466)
> Add "site" label to blackbox-exporter targets

- k8s/prometheus-federation/deployments/rebot.yml
This PR updates the Rebot image to v0.1.1. The only difference is that now Rebot takes advantage of the recently added "site" label instead of using `label_replace`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/469)
> Update Rebot image to v0.1.1

- config/federation/grafana/dashboards/Ops_Tactical_SRE_Overview.json
This PR adds the Tactical/SRE Overview dashboard to Grafana.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/468)
> Create Ops: Tactical & SRE Overview dashboard

- config/federation/prometheus/alerts.yml
The old `nodeinfo` DaemonSet was subsumed and superseded by the new `host` one, but this alert did not get updated to reflect that. The naming convention of `HostExperimentMissing` is a little non-standard, at least compared to other similar alerts. To me, `HostMissing` was too ambiguous.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/473)
> PlatformCluster_NodeinfoMissing alerts is now PlatformCluster_HostExperimentMissing

- IPV6_MONITORING.md
We have discovered that the latest release (v0.14.0) is not compatible with our configuration file format.
Also, this PR adds a note about `pwd` that must be `/home/mlab` for the containers to start.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/482)
> Change blackbox-exporter version to v0.12.0

- IPV6_MONITORING.md
- config/federation/prometheus/prometheus.yml.template
The Linode VM we use for monitoring IPv6 on the platform is a critical piece of our overall monitoring configuration, but we are not currently scraping any metrics from it for basic resource monitoring. This PR addresses that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/487)
> Adds scraping of the Linode VM for IPv6 monitoring.

- config/federation/grafana/dashboards/Ops_OamOverview.json
This PR adds the blackbox-exporter-ipv6 VM to the "Ops: OA&M dashboard".
The `instance="$vm.measurementlab.net"` condition has been replaced with a pattern matching to account for instance names containing the project name (such as blackbox-exporter-ipv6).
As discussed in a previous PR, I've left this dashboard `editable` as it makes making future changes easier and we cannot save provisioned dashboards anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/488)
> Add blackbox-exporter-ipv6 vm to Ops_OamOverview dashboard

- config/federation/prometheus/alerts.yml
We don't care about legacy alerts on machines that have migrated to the platform cluster. Adding a platform cluster metric to the `unless` clauses should cause them to not fire on machines that have been migrated.  The choice of `node_filesystem_size_bytes{}` is somewhat arbitrary. It contains a `machine=` label, which is all we need for this purpose.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/490)
> Adds k8s-specific metrics to unless clauses on legacy alerts

- k8s/prometheus-federation/deployments/github-receiver.yml
This PR adds a `containerPort: 9990` to the YAML deployment configuration for `github-receiver`. 
Prometheus metrics for this receiver are available at `<receiver-url>:9990/metrics`, while the HTTP server serving the webhook listens on port 9393. Since only port 9393 was exposed, Prometheus could not scrape the github-receiver metrics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/492)
> Add containerPort:9990 to expose Prometheus metrics

- config/federation/grafana/provisioning/datasources/platform-cluster_mlab-oti.yml.template
We migrated the mlab-oti platform cluster to use the new GCP object/resource names and domain names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/499)
> Changes the platform cluster datasource URL for mlab-oti

- config/federation/prometheus/alerts.yml
The new criteria should effectively exclude nodes where a certain metric exists that is only present on the platform cluster. This PR should resolve issue https://github.com/m-lab/k8s-support/issues/122, and should allow us to retire the synthetic node_exporter metrics on the platform cluster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/506)
> Adds an additional criteria to legacy collectd, lameduck and vdlimit alerts.

- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
The current `PlatformCluster_PodDown` actually alerts on containers being down, and if an entire pod with 6 containers is down the we'll get 6 alerts, rather than the single one we want. This hopefully resolves issue #489.
Also in this PR, we remove the check on the `lame_duck_node` metric, which is a legacy metric that no longer exists on the platform cluster, and replaces it with a metric from our new way of lame-ducking a node (adding a taint with a key of `lame-duck`).
Additionally, currently GMX does not export a `node` label, so we add one using `label_replace` so that we can match all criteria `on(node)`.  I have opened an issue on the [an issue on the GMX repo](https://github.com/m-lab/github-maintenance-exporter/issues/22) to add a `node` label to all metrics to avoid this ugly …
> Modifies the PlatformCluster_PodDown alert to actually alert on pod failures

- .travis.yml
We no longer use scraper in those projects, so let's not setup anything to do with scraper in those projects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/508)
> Removes anything to do with the scraper-cluster in .travis.yml for sandbox and staging

- config/federation/grafana/dashboards/K8s_SiteOverview.json
[A recent change that was made to `relabel_configs` in the platform cluster](https://github.com/m-lab/k8s-support/pull/239) instance of Prometheus caused all the pod resource utilization panels to stop working. This PR fixes those panels by selecting on `machine` instead of `node`.
This PR also improves the quality of the `Pod status` panel by selecting on pods that are actually `Ready`, and not just `Running`, since a "running" pod may not actually be "ready".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/509)
> Fixes K8s:SiteOverview dashboard and also improves the 'Pod status' panel

- config/federation/grafana/dashboards/K8s_MasterCluster.json
- config/federation/grafana/dashboards/K8s_SiteOverview.json
- config/federation/grafana/dashboards/NDT_EarlyWarning.json
- config/federation/prometheus/prometheus.yml.template
- config/federation/prometheus/rules.yml
This change consists of new recording rules and updates to the NDT:Early Warning dashboard.
Unfortunately, right now all sandbox nodes are new-stack, which means the changes to the vdlimit metrics are unverified for now.
The Early Warning dashboard panels now include "vserver" and "k8s" queries.
The prometheus server configuration template includes new metrics from the platform-cluster used by the recording rules that define the metrics below.
New metrics for vservers to report space used as a ratio 0-1 (as the k8s nodes now do):
- ndt:vdlimit_used_bytes:ratio
- ndt:vdlimit_used_ratio:predict_linear3h_12h (replaces ndt:vdlimit_used:predict_linear3h_12h)
New metrics for k8s nodes:
- machine:ndt_test:rpm2m - ndt test count
- machine:node_disk_io_time_seconds:max2m - disk io utilization
- …
> Update NDT: Early warning to support k8s platform nodes

- config/federation/grafana/dashboards/K8s_EtcdOverview.json
- config/federation/grafana/dashboards/K8s_MasterCluster.json
- config/federation/grafana/dashboards/K8s_WorkloadOverview.json
Three separate K8s dashboards were broken by the recent modification of the platform cluster master nodes names. This PR should fix all the dashboards.
For a complete fix, this PR will also rely on PR https://github.com/m-lab/k8s-support/pull/243.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/511)
> Fixes three broken k8s dashboards due to platform cluster master node renames

- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
This PR adds two new alerts to monitor changes in RAM on a machine. Mike Millner has been pressing us to check this sort of thing, because in his experience hardware goes bad all the time when you run enough of it. 
This PR is intended to resolve issue https://github.com/m-lab/ops-tracker/issues/523. That issue was opened thinking that we would monitor all sorts of things, but after considering, I couldn't think of anything else that is easily monitorable that we could alert on other than RAM.
**Note**: I'm a little unsure if the `PlatformHardware_RamAmountChanged` alert is implemented in the best way. Currently, I have it configured to look at changes in reported RAM over the past day, but to only tolerate those changes for 1m. The intention is that changes in RAM do no slip out of the …
> Adds two new alerts for changed for lower-than-expected RAM.

- config/federation/grafana/dashboards/K8s_WorkloadOverview.json
This PR, leverages a number of new recording rules in the m-lab/k8s-support repository to change all panels to aggregate on DaemonSet, not container.
The dashboard loads much more quickly, but for some reason it is still very sluggish... seemingly because of the "Container restarts" panel, but that can be fixed later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/519)
> Aggregates WorkloadOverview panels at the DaemonSet level, not container

- config/federation/grafana/dashboards/NDT_EarlyWarning.json
- config/federation/prometheus/prometheus.yml.template
- config/federation/prometheus/rules.yml
This change updates the recording rules that previously used the new deprecated `ndt_test_total` metric in favor of the `ndt5_client_test_results_total` metric. This change is a consequence of https://github.com/m-lab/ndt-server/pull/169 which retired the `ndt_test_total` metric due to needing more visibility into client successes / errors before deciding how to actually count `ndt_test_total`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/520)
> Update ndt test results recording rule

- config/federation/prometheus/alerts.yml
We've had an a monitoring problem with NDT SSL over IPv6 for the past couple months, but nobody noticed. Silently, pretty much every `ndt_ssl_ipv6` blackbox_exporter probe was failing because siteinfo was not creating protocol-decorated, flattened DNS records.
This PR creates 4 new alerts using the identical queries that mlab-ns runs for the same services. For IPv4 services the toleration is anything above 90%, for IPv6 anything above 75%.  
Note: The ndt_ssl_ipv6 alert may fire if this is merged and tagged, since the outage is still resolving itself, apparently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/521)
> Adds NDT alerts based on mlab-ns queries.

- config/federation/grafana/dashboards/Ops_RebootAPIMonitoring.json
This PR adds the "Ops: Reboot API monitoring" Grafana dashboard, showing:
- Memory usage for the reboot-api deployment
- Reboot rate
- Response time for reboot operations
- Failed E2E tests over time
- Currently failing E2E tests
This dashboard is visible on sandbox [here](https://grafana.mlab-sandbox.measurementlab.net/d/aOLG3CDWk/ops-reboot-api-monitoring?orgId=1).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/518)
> Create Reboot API monitoring dashboard

- config/federation/prometheus/rules.yml
Now that tests have additional, protocol, direction, and result labels, the remaining (protocol, result) labels added too many timeseries to the dashboard.
This change actually groups by machine -- which is both how it's named and used in the dashboards.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/523)
> Actually aggregate by machine

- config/federation/grafana/dashboards/K8s_WorkloadOverview.json
- config/federation/prometheus/alerts.yml
Several recording rules were changed which drive the K8s:WorkloadOverview dashboard. This PR updates the panels to use the updated and renamed recording rules. It also removes a couple of unused panels, and improves the "Pod container restarts" panel to:
* Not drag down the entire dashboard
* Display more useful values. It now only displays containers where the restart count is > 10
This PR also fixes the `Hardware_RamBelowExpected` alert to not alert on cloud or testings nodes, both of which might be below the 16GB threshold.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/525)
> Improves and fixes K8s:WorkloadOverview dashboard + fixes RamBelowExpected alert

- config/federation/grafana/dashboards/NDT_GlobalTestRate.json
This change adds the ndt5 metrics to the Global Test Rate dashboard. The data just before the upgrade and just after the metrics change are a little wobbly but mostly complete. The apparent loss of traffic is in fact a loss of monitoring fidelity.
This change also adds a datasource selector.
https://grafana.mlab-sandbox.measurementlab.net/d/Cyq7WeNiz/ndt-global-test-rate?orgId=1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/524)
> Add ndt5 metrics to Global Test Rate

- config/federation/grafana/dashboards/Ops_RebootAPIMonitoring.json
- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
This PR adds two new alerts:
- `BMC_CredentialsNotFound`: when credentials for a BMC are not available at all in Datastore, fires after 5m.
- `BMC_ConnectionFailed`: when connection to the BMC fails, fires after 24 hours as this may be a temporary condition
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/522)
> Add alerts in case of BMC E2E test failures

- config/federation/grafana/dashboards/Ops_Tactical_SRE_Overview.json
This PR replaces the (maybe broken) `alertmanager_alerts` metric with `rate(alertmanager_alerts_received_total{status="firing"}[5m])`, which seems to give a correct representation of how many alerts are actually firing in AM.
Preview here: https://grafana.mlab-sandbox.measurementlab.net/d/_fugwnWZk/ops-tactical-and-sre-overview?orgId=1&from=now-7d&to=now
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/529)
> Fix alert count graph (SRE overview)

- config/federation/prometheus/alerts.yml
This PR adds `-n namespace` to `kubectl describe daemonset` in the alert description.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/530)
> Specify DS namespace when providing an example command

- k8s/prometheus-federation/deployments/mlabns-stackdriver.yml
This PR adds the user-defined `user/reverse-proxy-counter` metric to the list of metrics that the stackdriver-exporter will fetch from stackdriver.
After merging this, the metric can be queried as `stackdriver_gae_app_logging_googleapis_com_user_reverse_proxy_counter`. 
https://grafana.mlab-sandbox.measurementlab.net/explore?left=%5B"now-30m","now","Prometheus%20(mlab-sandbox)",%7B"expr":"stackdriver_gae_app_logging_googleapis_com_user_reverse_proxy_counter"%7D,%7B"ui":%5Btrue,true,true,"none"%5D%7D%5D
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/532)
> Get user/reverse-proxy-counter custom metric from Stackdriver

- config/federation/prometheus/alerts.yml
This PR adds an alert that fires immediately in case more than 20% _of the pingable switches_ stop providing SNMP data.
While this does not mean there is an outage on the platform switches (since they are pingable), it almost surely means something is wrong with snmp_exporter or its configuration.
I believe this closes https://github.com/m-lab/prometheus-support/issues/393.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/533)
> Add TooManySnmpMetricsMissing alert

- k8s/prometheus-federation/deployments/reboot-api.yml
This PR updates reboot-api to v0.3.0, which introduces Datastore connection reuse.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/536)
> Update reboot-api to v0.3.0

- config/federation/prometheus/alerts.yml
- k8s/prometheus-federation/deployments/mlabns-stackdriver.yml
This PR adds an alert that checks if mlab-ns redirected any traffic to staging over the past 24h. This is not very fine-grained as it does not differentiate among experiments (we don't have that information in the metric) but should at least tell us if the proxying is entirely broken. 
Please note that the counter in question is actually a gauge: https://grafana.mlab-sandbox.measurementlab.net/explore?left=%5B"now-24h","now","Prometheus%20(mlab-sandbox)",%7B"expr":"stackdriver_gae_app_logging_googleapis_com_user_reverse_proxy_counter"%7D,%7B"ui":%5Btrue,true,true,"none"%5D%7D%5D
Assuming we don't want to keep this redirection indefinitely (e.g. are we going to remove it after the k8s migration has been completed?) we'll need to remove this alert at some point.
I believe it closes …
> Add MlabNSReverseProxyNotWorking alert

- k8s/prometheus-federation/deployments/mlabns-stackdriver.yml
This PR adds the `user/requests-by-resource` metric to the list of metrics exported by the stackdriver-exporter container. This new metric counts the requests received by mlab-ns and has a `resource` label that can be `ndt7` or `ndt_ssl`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/540)
> Fetch user/requests-by-resource metric from Stackdriver

- config/federation/grafana/dashboards/K8s_SiteOverview.json
- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
This PR has two unrelated changes:
1) A new alert for the case where a node is in a NotReady state for too long. Additionally, now the PodDown alert will not fire if the node is NotReady.
1) A small update and improvement to the SiteOverview dashboard, which now uses the metric `container_memory_working_set_bytes` instead of `container_memory_usage_bytes`. The former does  not include cached and buffered memory, both of which can be evicted under memory pressure, but instead gives active memory usage (RSS?). This is also the metric that the WorkloadOverview dashboard uses, so this change will make the two dashboards more consistent with one another.
--- …
> New NodeNotReady alert + small improvement to K8s:SiteOverview dashboard

- config/federation/grafana/dashboards/Ops_OamOverview.json
After updating OA&M machines (dsn, mirror, eb, etc.) to Debian Buster, this dashboard broke because metric names had changed in the newer version of Prometheus. This PR uses updated Prometheus metric names, and sets rootfs singlestat panel to instant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/543)
> Fixes Ops:OamOverview dashboard

- k8s/prometheus-federation/deployments/mlabns-stackdriver.yml
This PR changes the stackdriver-exporter configuration to:
- Export the new `user/requests_counter`, counting the number of mlab-ns requests by resource (experiment)
- Use the latest version of stackdriver-exporter, which seems to solve some issues I've seen with the `/metrics` endpoint returning 500 and nothing being written in the logs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/542)
> Export user/requests_counter and update stackdriver-exporter

- config/federation/prometheus/alerts.yml
This alert was incorrectly firing due to multiple time series with different url labels, some of them being sometimes zero. A better way to write the query is summing them together, since they all refer to the same resource (ndt_ssl). 
With this revised query, the metric value has almost never gone under 30 in the past week, and has never been zero.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/544)
> Fix MlabNSNdtSslReverseProxyNotWorking alert firing too often

- config/federation/grafana/dashboards/MLABNS_ReverseProxying.json
- k8s/prometheus-federation/deployments/mlabns-stackdriver.yml
This PR adds the `MLABNS-Reverse Proxying`  dashboard, showing:
1. Requests per experiment
2. Reverse proxied requests per experiment
3. Reverse proxying rate per experiment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/545)
> Add MLABNS_ReverseProxying dashboard

- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
This PR is meant to resolve this issue: https://github.com/m-lab/k8s-support/issues/281
This PR conservatively considers that if at least 2 pods have not updated in the last hour that something is wrong. The alert looks for the `delta()` of `kube_daemonset_updated_number_scheduled` over the last hour and if the number is less than 2 for 5m, an alert will fire. The reasoning for the small toleration window (5m) is that the query is already looking back over the past hour. So by the time the query is true, the issue has already been present for an hour. The alert will then only tolerate this condition for ~5 scrape cycles after that.
I've requested a review of this PR from @gfr10598, but want to also flag @pboothe and @robertodauria, in case either of them has any concerns about the …
> Adds an alert to notify us if a DaemonSet rollout is stuck

- config/federation/prometheus/alerts.yml
Upgraded pod counts apparently become flaky when you are down to around less than `maxUnavailable` pods remaining to be upgraded. All of the following commands were run within minutes of each other.
```
daemon set "host" successfully rolled out
Waiting for daemon set "host" rollout to finish: 121 out of 122 new pods have been updated...
Waiting for daemon set "host" rollout to finish: 121 out of 123 new pods have been updated...
Waiting for daemon set "host" rollout to finish: 120 out of 122 new pods have been updated...
Waiting for daemon set "host" rollout to finish: 120 out of 121 new pods have been updated...
daemon set "host" successfully rolled out
Waiting for daemon set "host" rollout to finish: 121 out of 122 new pods have been updated...
Waiting for daemon set "host" rollout to …
```
> Tweaks RolloutTooSlowOrStuck alert to be less chatty

- config/federation/prometheus/alerts.yml
Sometimes there are transient errors (e.g. a timeout in the BQ query)
and we do not want to immediately alert on those. This change makes
this alert a bit more forgiving by setting the threshold to > 2 err/day.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/549)
> Tolerate one transient error in RateLimiter alert

- config/federation/prometheus/alerts.yml
[Apparently it can take more than 5m to ramp up a rollout](https://grafana.mlab-staging.measurementlab.net/explore?orgId=1&left=%5B%221569357775368%22,%221569362136906%22,%22Platform%20Cluster%20(mlab-staging)%22,%7B%22expr%22:%22%20%20%20%20%20%20delta(kube_daemonset_updated_number_scheduled%5B1h%5D)%20%3C%202%20unless%20(%5Cn%20%20%20%20%20%20%20%20(kube_daemonset_status_desired_number_scheduled%20-%20kube_daemonset_updated_number_scheduled)%20%3C%204%5Cn%20%20%20%20%20%20)%22,%22context%22:%22explore%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D). Tolerating this condition for only 5m doesn't take into account the 55m before the rollout starts. This PR just tolerates the condition for a bit longer. Hopefully this will be enough.
---
This change …
> Tolerates PlatformCluster_RolloutTooSlowOrStuck for 30m instead of just 5m

- k8s/prometheus-federation/deployments/snmp-exporter.yml
This PR, along with https://github.com/m-lab/switch-config/pull/165, should resolve issue https://github.com/m-lab/switch-config/issues/148.
Since the config is now a ConfigMap, there is also no longer a need for the gcs-downloader sidecar container.
This PR also update the version of configmap-reload to the latest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/551)
> Sets volume for snmp-exporter as a ConfigMap

- config/federation/prometheus/alerts.yml
The previous query was just outright wrong and bad, not taking into account the fact `delta(kube_daemonset_updated_number_scheduled[1h])` will be a negative number for a good chunk of a rollout.
The current query takes the present value of `kube_daemonset_updated_number_scheduled` and then subtracts the value for that same metric an hour ago. If that number is less than 2 for an hour, then fire the alert. It needs to be true or tolerated for at least an hour (70m in this PR), since `kube_daemonset_updated_number_scheduled - (kube_daemonset_updated_number_scheduled offset 1h)` will evaluate to a negative number until our measurement window is near equivalent to the time in the past the rollout began.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> Modifies the RolloutTooSlowOrStuck alert to actually work as expected.

- config/federation/prometheus/alerts.yml
For example, the Bismark experiment caused this alert to fire because we have a nodeSelector on those pods that will only schedule them on sandbox nodes, so the alert thought it was stuck when 0 - 0 was < 2 for 70m. This PR should fix this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/554)
> Omits DaemonSets in RolloutTooSlowOrStuck that a desired_scheduled of 0.

- config/federation/grafana/dashboards/Ops_Tactical_SRE_Overview.json
This PR changes the datasource for the "Rebooted nodes" panel to `$datasource` and (hopefully) makes the "Nodes GMX maintenance" panel's title and description clearer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/556)
> Fix datasource and panel title

- config/federation/grafana/dashboards/K8s_MasterCluster.json
- config/federation/grafana/dashboards/K8s_WorkloadOverview.json
* k8s:MasterCluster: Fixes the CPU panel to give a more accurate representation of %CPU used. Currently, it sums the CPU usage across all 4 CPUs and uses that number as a % of CPU usage. This is misleading because it will give an exaggerated view of how much CPU is actually used. For example, if each CPU is 20% over a 5m average, the current panel will show an 80% CPU usage, when in actuality the usage across all 4 is only about 20%.
* k8s:WorkloadOverview: Removes an unneeded, bulky legend from the aggregate CPU usage panel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/557)
> Two small Grafana dashboard fixes

- config/federation/prometheus/alerts.yml
We have discovered that two transient errors when accessing BigQuery over a period of 24 hours is not uncommon. This change makes the corresponding alert a bit more forgiving, changing the threshold to 6 errors (corresponding to an error rate of 12.5%)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/559)
> Make the RateLimiterTooManyServerSideErrors more tolerant

- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
This change adds a new alert that fires whenever total pusher daily data volume drops below 70% of normal.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/567)
> Add new alert: PlatformCluster_PusherDailyDataVolumeTooLow

- k8s/prometheus-federation/deployments/bigquery-exporter.yml
This change removes bigquery exporter queries that we no longer use.
Four queries "bq_ndt_tests.sql", "bq_ndt_annotation.sql", "bq_gardener_parse_time.sql", "bq_ndt_server.sql" should be updated to use the new ndt5, tcpinfo and/or traceroute tables.
Only the gardener parse times and ndt_annotation rates have alerts that depend on them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/568)
> Remove unused bqx queries

- generate-prometheus-targets.sh
We decided that it would be easiest to only have `/neubot` and `/neubot_ipv6` mlab-ns tools. However, we still want to check whether the TLS port (443) is listening to verify the health of these paths. In order to do this we need a separate, distinct service name for each type of target.
This PR is related to PR https://github.com/m-lab/mlab-ns/pull/214.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/573)
> Modifies neubot target service names so there is a distinct service name for each target

- generate-prometheus-targets.sh
This PR adds the blackbox-exporter port explicitly to the neubot IPv6 targets. It's currently using port 80 and failing to connect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/578)
> Add BBE port explicitly on neubot ipv6 targets

- config/federation/prometheus/prometheus.yml.template
This PR reads some additional systemd-related metrics from the Platform Cluster Prometheus instance so we can alert on them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/583)
> Import node_systemd_* metrics from platform cluster prometheus

- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
We just had a scenario where the PD on the production platform cluster instance of Prometheus filled up and started causing the prometheus pod to crash loop. We didn't know until it became obvious when others things we used started failing. This PR adds a new alerts to warn us when the PD on a platform cluster instance of Prometheus has less than 5% free.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/581)
> New alert for when the persistent disk on platform cluster Prometheus gets too full

- config/federation/grafana/dashboards/K8s_WorkloadOverview.json
This change adds a new panel to the k8s: Workload Overview dashboard to observe rollouts progress.
To support viewing individual rollouts this change adds two new variables for "workload" and "container", with default values of "All".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/582)
> Add rollout panel for standard containers

- config/federation/grafana/dashboards/NDT_GlobalTestRate.json
This change fixes the queries that rely on now-obsolete metrics causing the graph to render incompletely. As well, this change updates the colors to avoid confusion between the upper and lower panels.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/587)
> Fix queries used by NDT Global dashboard

- config/federation/alertmanager/config.yml.template
- config/federation/prometheus/alerts.yml
Also, split alert `PlastformCluster_DownOrMissing` into two separate alerts, each with more descriptive alert names. `PlatformCluster_DownOrMissing` makes it sound like something is wrong with the actual cluster, and not just with a federated scrape job.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/590)
> Inhibit missing metrics alerts if platform cluster scrape job is down.

- config/federation/grafana/dashboards/Ops_Tactical_SRE_Overview.json
This PR attempts to create visibility of overly busy 10g sites, just as we currently do for 1g sites, per the [specification laid out in the Data Quality meeting today](https://docs.google.com/document/d/1KG_GR67-F7aRGv-kXPK7q10QeB2e5ZwUV5r6X8SvDQ4/edit#heading=h.tbvy00pw7ocl):
> 50% of 9.4Gbps (the rest should mirror the conditions set up in the early warning dashboard)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/591)
> Modifies SRE Overview dashboard to include 10g sites over 50% utilization.

- config/federation/prometheus/prometheus.yml.template
This PR further reduces the number of metrics we collect from the Platform Cluster Prometheus by filtering for `{state="failed"}`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/588)
> Filter systemd units with state="failed"

- config/federation/grafana/dashboards/Prometheus_SelfMonitoring.json
- k8s/data-processing-cluster/deployments/prometheus.yml
This change removes support for the 1.x versions of Prometheus from the dashboard. And, clearer calculations for estimated "consumption rate" and "usage estimate" panels. As well, this change updates the version of prometheus & node-exporter in the data processing cluster configs to support subqueries and the same bytes available metric as other clusters.
Dashboard should be visible here: https://grafana.mlab-sandbox.measurementlab.net/d/sVklmeHik/prometheus-self-monitoring?orgId=1&var-datasource=Platform%20Cluster%20(mlab-staging)&from=now-7d&to=now
NB: the downloader cluster uses prometheus v1.6 -- this change breaks support for that configuration. That cluster should be retired in favor of migration to the new data-processing cluster.
--- …
> Update Prometheus: Self Monitoring dashboard

- apply-global-prometheus.sh
- config/federation/alertmanager/config.yml.template
- config/federation/prometheus/alerts.yml
We've all agreed that we are at the point of needing some sort of paging with regard to the most severe problems that can occur on the platform. This PR is a first test at implementing this using a service called [PagerDuty](https://www.pagerduty.com/). One nice thing about PagerDuty is that [support of it is already built into AlertManager](https://prometheus.io/docs/alerting/configuration/#pagerduty_config).
It appears that PagerDuty is flexible enough to allow us to be sure that only the Google person on call for a given week would receive pages.
This PR also more appropriately sets the `severity` label for alerts to only have a value of `page` for the alerts that are the most serious. With this PR the only alerts with a severity=page are:
```
ClusterDown
MlabNSServiceUnavailable …
```
> Adds configs for PagerDuty to AM, and appropriately sets alert severity label

- config/federation/prometheus/alerts.yml
This alert takes advantage of [a new bq-exporter query](https://github.com/m-lab/prometheus-support/blob/master/config/federation/bigquery/bq_ndt_s2c.sql) that looks for NDT S2C tests affected by switch discards in a 24h period.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/598)
> Adds a new alerts for when more than 5% of NDT S2C tests have discards.

- config/federation/bigquery/bq_ndt_s2c.sql
- k8s/prometheus-federation/deployments/bigquery-exporter.yml
This change includes a fix to the bq_ndt_s2c query and an upgrade of the bqx container version.
The bq_ndt_s2c query used a `DECLARE` statement which evidently isn't supported by default by either the older or newer versions of bqx. This change replaces is it with a function instead.
The version of bqx is updated to v1.0.0. This includes flag changes and use of the canonical port.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/600)
> Update bigquery exporter version and bq_ndt_s2c query

- k8s/prometheus-federation/deployments/bigquery-exporter.yml
Evidently something is off about the v1.0.0 version -- it repeatedly logs that it's Registering the queries instead of updating them. As a result, the metrics collected end up with gaps.
This change rollsback the bqx version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/601)
> Rollback bqx version

- config/federation/prometheus/alerts.yml
This further reduces the alerts with `severity=page` to:
- ClusterDown
- TooManyNdtSslIpv4ServersDown
- MlabNSServiceUnavailable
- PlatformCluster_NdtMissing (No metrics at all for deployment="ndt")
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/602)
> Further reduce number of alerts with severity=page

- k8s/prometheus-federation/deployments/gcs-exporter.yml
This change adds the gcs-exporter to the federation cluster to monitor daily archive transfers as part of the "Codified Daily Archive Transfers" design.
The exporter scans the named buckets every day at 04:30:00 UTC. This time corresponds to the schedules defined in https://github.com/m-lab/gcp-config/blob/master/daily-archive-transfers.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/606)
> Add gcs-exporter deployment

- config/federation/prometheus/prometheus.yml.template
This PR is intended to resolve issue #607.
In summary, in the case where a metric has a `node` label, then the `machine` label should be overwritten with the `node` label's value.
NOTE: I've attempted to spot check this for sanity, and I _believe_ it is the correct thing to do and safe, but a second set of eyes will be good. Hence this  PR, I guess.
An an indirect way this PR is part of PR https://github.com/m-lab/mlab-ns/pull/216, which attempts to resolve https://github.com/m-lab/mlab-ns/issues/215
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/608)
> Set the 'machine' label equal to the 'node' label, if the label 'node' label exists.

- config/federation/prometheus/alerts.yml
Additionally, I've taken some existing alerts prefixed like `MlabNSMyAlert` and formatted it like `MlabNS_MyAlert` to conform with other uses of prefixes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/610)
> Adds new alert for missing "generic" mlab-ns metrics

- config/federation/prometheus/alerts.yml
The metric `kube_node_spec_taint` will only exist if a node has been tainted. In many cases no nodes will have taints, and this metric will not exist, causing a false positing on the `MlabNS_GenericMetricsMissing` alerts. This PR also removes the `absent()` check on `gmx_machine_maintenance`, since that metric could also reasonably be missing if there are no active GMX entries and the pod was recently restarted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/611)
> Removes metrics from mlab-ns generic query that might reasonably not exist

- .travis.yml
- config/federation/grafana/dashboards/K8s_WorkloadOverview.json
Currently, there are a number of panels in the k8s:WorkloadOverview dashboard that are almost always empty (e.g., Daemonset pods desired != current) and therefore not very useful. Also, the panel that displays pods with a Ready condition == false was just noisy and not useful because a single down node would populate that panel with a dozen pods.
This PR removes those somewhat useless panels and replaced them with other panels that are hopefully more useful. Two new panels:
* "Node Ready condition status". This new panel should resolve issue #605.
* "Cluster versions" display k8s and kernel version distribution in the cluster. It could be updated to display other versions like CoreOS version, or kubeproxy version... possibly others.
This PR also makes some small modification to some other …
> Overhauls the k8s:WorkloadOverview dashboard

- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
- k8s/prometheus-federation/deployments/gcs-exporter.yml
This change includes two updates:
* Update the version of gcs-exporter to support multiple bucket times
* Add a new Pusher SLO alert using the new metric available in pusher:v1.14.
The Pusher SLO expects `pusher_finder_mtime_lower_bound` to be less than 24h.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/618)
> Update gcs-exporter & Add pusher SLO alert

- config/federation/prometheus/alerts.yml
The query in this alert was tested like this in mlab-sandbox:
1. Login to mlab4.lga0t and `systemctl stop kubelet`.
2. When the node becomes `NotReady` in k8s, delete the node.
3. Verify that this query returns mlab4.lga0t.
4. Reboot mlab4.lga0t and verify that the query returns nothing.
I chose to use `service="ndt_ssl"` under the assumption that that is a blackbox_exporter probe service that should always exist on the platform, though it is mildly arbitrary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/623)
> A new alert to detect 'zombie' nodes. Intended to resolve issue #620.

- config/federation/prometheus/alerts.yml
The old alert was spammy. 
finder (the thing that does a cleanup job if inotify events were missed) runs every hour in expectation. But it could be arbitrarily far in the future with ever-decreasing likelihood.  Also, it will only trigger on files that are at least 4 hours old. Also, it will only update the metrics when it runs.  This means that the following sequence of events could occur:
1. An inotify event was missed. Wait 4 hours before finder could even possibly find the file.
2. Now that the file is eligible for upload, wait up to 1-4 or more hours for finder to run.
3. Now wait until the file is actually uploaded and removed, up to 2 hours.
4. Now wait 1-4 or more hours for finder to run again to notice that the file has been removed.
Our alert is firing spam because 4 + …
> Make the pusher alert less spammy

- apply-global-prometheus.sh
- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
This PR changes the Prometheus configuration to scrape the platform-cluster Prometheus over HTTPS and by authenticating via HTTP Basic Authentication.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/626)
> Use HTTPS and basic authentication to scrape platform-cluster Prometheus

- config/federation/grafana/dashboards/K8s_SiteOverview.json
- config/federation/grafana/dashboards/K8s_WorkloadOverview.json
This change includes update to:
* add distinct physical & virtual counts to the k8s Workload dashboard 
* add pid-count, goroutine count, and container rss panels to the k8s Site dashboard
These changes have been used in ad-hoc dashboards for sometime. This change adds them to canonical dashboards for broader benefit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/629)
> Updates to k8s Workload and k8s Site overview dashbaords

- config/federation/prometheus/prometheus.yml.template
- k8s/prometheus-federation/deployments/reboot-api.yml
This PR updates the reboot-api version to v0.4.0, which changes the `/v1/e2e` endpoint to cache results for an hour. That makes it possible to set the `scrape_interval` for the bmc-targets to the default (1m). 
Closes https://github.com/m-lab/prometheus-support/issues/630.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/631)
> Update reboot-api deployment to v0.4.0 and change scrape_interval

- config/federation/grafana/dashboards/K8s_SiteOverview.json
This changes enables the "shared crosshair" option for the dashboard and changes the Go RSS Memory panel to use `sum by(container) (...)` to list one timeseries per container across deployments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/633)
> Shared cross hairs and normalize RSS panel

- config/federation/prometheus/alerts.yml
We will alert on `ifInErrors` on a switch uplink if the increase in errors is more than 100/day for more than 7d. Note that even though the net "increase" for a day may be negative, this will still fire if the total is over 100, I believe.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/635)
> Adds a new alert for when there are too many ifInErrors on a switch uplink.

- config/federation/prometheus/alerts.yml
The threshold is being increased from 4m to 10m. This PR also increases the threshold for missing workloads to 15m so that a failing/absent scrape job doesn't allow a bunch of missing DaemonSet alerts to fire (they are inhibited by Alertmanager).
10m seems like a bit longer than I'd like to allow for the platform cluster scrape job to down, but I'm not sure what else to do here.
This is a workaround (fix?) for m-lab/k8s-support/issues/371.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/636)
> Increases threshold for platform cluster scrape job failing/absent.

- config/federation/alertmanager/config.yml.template
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/641)
> Runs slack-alerts-ticket receiver even if PagerDuty receiver fires first

- apply-global-prometheus.sh
- config/federation/alertmanager/config.yml.template
- config/federation/prometheus/alerts.yml
This is achieved by modifying the AlertManager config for the PagerDuty receiver to insert a 'match' selector for a non-existent label, which should effectively prevent the receive from ever matching, hence it should be skipped.
This is intended to resolve #642.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/643)
> Prevents AM from sending staging alerts to PagerDuty

- config/federation/grafana/dashboards/K8s_SiteOverview.json
It was broken by our shift from platform/cloud labels to physical/virtual node labels.
I'm not 100% sure why the diff is so large. But the view in mlab-sandbox is what we/I want, so I think it's okay, whatever the big change is.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/649)
> Fixes the 'Pod status' panel of the k8s_SiteOverview dashboard

- config/federation/prometheus/alerts.yml
After downloader restarts and before a successful download, the LastSuccessTime metric is initialized to zero and the alert using that metric can fire when it does not need to.
A pod restart can occur as a result of normal k8s node restarts and pod migration between nodes.
1h should allow enough time for the download to attempt and succeed after a restart.
Fixes https://github.com/m-lab/dev-tracker/issues/571
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/654)
> Change downloader alert wait threshold

- apply-global-prometheus.sh
- config/federation/grafana/dashboards/K8s_SiteOverview.json
- k8s/prometheus-federation/deployments/switch-monitoring.yml
Deployment YAML + k8s secret creation from a Travis CI secret.
switch-monitoring will listen on the pod's private IP only, thus no HTTP authentication is needed.
Closes https://github.com/m-lab/prometheus-support/issues/651.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/655)
> Deploy switch-monitoring on the prometheus-support GKE cluster

- config/federation/grafana/dashboards/K8s_WorkloadOverview.json
This change adds a new panel to the workload overview to highlight probable OOM events on the platform using the `dmesg_logs` metric.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/656)
> Add new panel for probable OOMs

- apply-global-prometheus.sh
- config/federation/prometheus/prometheus.yml.template
- config/federation/script-exporter/script_exporter.yml
- generate-prometheus-targets.sh
- k8s/prometheus-federation/deployments/prometheus.yml
- k8s/prometheus-federation/deployments/script-exporter.yml
- k8s/prometheus-federation/services/script-exporter.yml
This PR adds several changes to the prometheus federation cluster to support access-token enabled e2e monitoring using the locate service.
This change adds a new script exporter deployment with configuration to target ndt5 servers using the ndt5-client. When ndt5-client runs it is invoked by the monitoring-token command, which uses the LOCATE_URL and MONITOR_SIGNING_KEY from the environment to request a valid monitoring token from the locate service in the current project. (projects mlab-oti/mlab-ns are not yet supported).
We are adding a second script exporter. Normally target files are read from a directory `/script-targets/*.json`. Because the config also targets a static script exporter, this PR adds a second directory `/script-targets-federation/*.json` and script exporter target …
> Add script-exporter to federation cluster with access-token e2e monitoring

- k8s/prometheus-federation/services/switch-monitoring-service.yml
Creates the switch-monitoring service so that switch-monitoring can be reached via the cluster DNS on the cluster IP.
This change is propaedeutic (!) to monitoring switch-monitoring.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/661)
> Add switch-monitoring-service.yml

- config/federation/prometheus/alerts.yml
E2E targets are currently all down, but there is nothing alerting us that this is happening. This PR adds an alert for such a case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/664)
> Add alert if metrics from the BMC E2E test are missing

- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
- generate-prometheus-targets.sh
- k8s/prometheus-federation/deployments/prometheus.yml
This PR adds scraping and alerting for switch-monitoring.
In particular, it adds a new switch-monitoring-targets list of targets and a corresponding scraping job targeted at switch-monitoring's internal IP address.
The targets are scraped every minute, but switch-monitoring will return a result cached for 24 hours.
The alerts are for the following conditions:
- Configuration file not found on GCS
- Configuration file not found on the switch (connection failed or wrong permissions)
- The config on the switch and the one in GCS are not the same
They all ignore sites in GMX.
Closes https://github.com/m-lab/prometheus-support/issues/652.
--- …
> Add switch-monitoring scraping and alerts

- config/federation/prometheus/alerts.yml
The name was previously incorrect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/666)
> Fix job name in SwitchMonitoring_DownOrMissing alert

- config/federation/prometheus/prometheus.yml.template
NOTE: I don't think there is a need to match on the entire FQDN. If the `node` label begins with a short node name, then we can safely assume the value is what we want in the `machine` label too.
Fixes #665.
Fixes #667.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/668)
> Makes regexp used to populate the machine label be v2-name-compatible.

- k8s/prometheus-federation/deployments/reboot-api.yml
This fixes the failures we've been seeing on the platform since we started using the V2 hostnames.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/669)
> Bump reboot-service to v0.5.0

- config/federation/prometheus/prometheus.yml.template
- generate-prometheus-targets.sh
This PR configures the `generate_prometheus_targets.sh` script to use v2 site.json file for all project (including mlab-oti).
Additionally, to help us migrate the platform cluster to v2 node names, this PR introduces a change which should cause all auto-discovered metric node names to wind up with v2 node names in Prometheus, even when the underlying node still knows itself by a v1 name.
This change would need to be applied in conjunction with  with updating mlab-ns to use v2 FQDNs.
**NOTE**: This commit should not be sent to production without a coordination the mlab-ns change mentioned above.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/671)
> v2 Prom targets for mlab-oti + force node and machine labels to v2 node names.

- config/federation/prometheus/prometheus.yml.template
The replacement was using only the first matching group of the regex. This PR puts the parenthesis around the entire regex so that the full node name is put into the machine label.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/672)
> Adjusts the parentheses in the regex to include whole matching pattern

- apply-global-prometheus.sh
This change enables deployment of the ndt5_client script exporter configuration in production.
Now that the locate/v2 api is running in production as a result of https://github.com/m-lab/dev-tracker/issues/587 and k8s-support includes a new version of the ndt-server which increases the success rate of the e2e monitoring, this should be safe to deploy now.
Part of https://github.com/m-lab/dev-tracker/issues/574
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/673)
> Deploy script-exporter in production

- k8s/prometheus-federation/deployments/script-exporter.yml
- k8s/prometheus-federation/mlab-oti.yml
- k8s/prometheus-federation/mlab-sandbox.yml
- k8s/prometheus-federation/mlab-staging.yml
The locate service is deployed to App Engine in the mlab-ns project. This change adds a new template variable for the LOCATE_PROJECT to distinguish it from the GCLOUD_PROJECT in which the GKE cluster runs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/676)
> Specify LOCATE_PROJECT for correct app engine URL

- config/federation/grafana/dashboards/K8s_Topk_Machine_Pod_Resources.json
This change updates the query filters for metrics about containers in the host context.
Pods with `hostNetwork:true` create sidecar containers with modified names, prefixed with `'kube-rbac-proxy-*`. This change adds a wildcard filter to the front of container names.
As well, when `hostNetwork:true` the pod network is visible as `eth0` instead of `net1`. This change includes eth0 in the pod network query.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/677)
> Fix: Match labels for `hostNetwork: true` pods

- config/federation/grafana/dashboards/Ops_Tactical_SRE_Overview.json
This PR updates the `label_replace` that extracts the site name from the machine name so that machines in sites that are in GMX already can be filtered out. 
You'll notice that due to the fact GMX currently exports both v1 and v2 names, the v1 names are still displayed in the table. This will eventually go away when the migration is completed, and at that point this updated regex is all we need.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/680)
> Update label_replace regex to extract site from v2 machine names

- generate-prometheus-targets.sh
This change adds the ndt `experiment=ndt.iupui` label needed for the [mlab-ns promql query][prom] to work as intended.
[prom]: https://github.com/m-lab/mlab-ns/blob/master/server/mlabns/util/prometheus_status.py#L33
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/682)
> Add experiment label to ndt5_client metrics

- k8s/prometheus-federation/deployments/script-exporter.yml
This change updates the script-exporter image built by the script-exporter-support repo to include recent improvements to the cache mtime randomization to be resilient to accidental sychronization. The result of that change is that the expected frequency of ndt measurements is every 5min rather than 10min.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/684)
> Update sx to include random mtime change

- config/federation/prometheus/prometheus.yml.template
v1 names no longer exist on the platform in any project!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/685)
> Removes relabel_config forcing all v1 names to v2 names

- k8s/prometheus-federation/deployments/gmx.yml
This deploys the version of GMX with the v1->v2 name logic removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/686)
> Updates the GMX image to v1.3.2.

- config/federation/grafana/dashboards/Ops_PlatformOverview.json
- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
- generate-prometheus-targets.sh
- k8s/prometheus-federation/deployments/prometheus.yml
This change removes the script-exporter VM configurations and targets from the prometheus deployment.
Locations found using `grep ndt_e2e` and `grep script-exporter`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/688)
> Retire script-exporter VM configurations

- config/federation/prometheus/alerts.yml
Currently, the so-called "mlab-ns" queries are including sites that don't yet physically exist in the denominator of the expression, causing the result to always be lower than it should be, and to hover not much above the alert threshold. This PR attempts to not include nodes in the denominator if they are in GMX mode _and_ do not exist in the cluster. This is pretty close, but perhaps not 100% precise, since it's possible that we could have a node that physically exists, but is not the cluster and is in GMX mode. As I write this, this is true for mlab2.iad03, [a node that has been down for months](https://github.com/m-lab/ops-tracker/issues/1013). However, I think that situation will be sufficiently rare that it won't be material for the purposes of these alerts, and that the benefits of …
> Modifies 'mlab-ns' alerts to try to not factor in nodes at sites that don't exist

- config/federation/prometheus/prometheus.yml.template
This change is related to this one: https://github.com/m-lab/switch-config/pull/203
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/691)
> Increases scrape_timeout for the snmp_exporter scrape job from 45s to 56s.

- config/federation/prometheus/alerts.yml
We don't alert for an entire switch being down for 24h, so alerting when SNMP scraping is down for only 2h seems too soon, especially considering that we have identified that SNMP scraping can sometimes (though not often) be flaky  for short intervals and sometimes slightly more extended stretches.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/692)
> Increases alert threshold for SnmpScrapingDownAtSite from 2h to 12h.

- k8s/prometheus-federation/deployments/switch-monitoring.yml
This release includes the fix at https://github.com/m-lab/switch-monitoring/pull/19 and no other changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/693)
> Bump switch-monitoring version to v0.1.2

- config/federation/prometheus/alerts.yml
This PR changes how long a switch can be unreachable by switch-monitoring before the alert is triggered. This prevents `ConfigNotFoundSwitch` from notifying us too soon -- and before the `SwitchDownAtSite` alert is triggered.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/694)
> Update ConfigNotFoundSwitch's "for" value

- generate-prometheus-targets.sh
This was an oversight in the migration process.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/695)
> Generate switch-targets using v2 names (e.g., s1-den04)

- config/federation/prometheus/alerts.yml
Ubuntu apparently reports memory slightly differently than CoreOS, and the value ends up being ~15938, instead of the ~16005 that CoreOS reports through node_exporter.
I think this change should be safe. The R630s have 16G of RAM comprised of 4 4G modules. Modules are not likely to fail partially, meaning that if a module failed, the RAM should dip to around 12G.
There is currently an alert in mlab-oti for mlab3.lga08, which I converted to Ubuntu yesterday.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/697)
> Lowers lower bound of reported sysmtem RAM to 15000MB.

- k8s/prometheus-federation/deployments/switch-monitoring.yml
This updates the switch-monitoring deployment to v0.1.3, which accepts the v2 hostname format.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/700)
> Update switch-monitoring to v0.1.3

- generate-prometheus-targets.sh
This PR updates the `switch-monitoring-targets` to use the new v2 hostname format.
I've noticed the ICMP probes were still using the v1 formats, too, and I've updated them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/698)
> Use v2 names for switch-monitoring-targets.

- config/federation/prometheus/alerts.yml
This should prevent the alert from firing on transient network issues like we're seeing at TPE01.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/699)
> Change ConfigNotFoundSwitch's "for" value to 5d

- config/federation/alertmanager/config.yml.template
- config/federation/prometheus/alerts.yml
Additionally, removes two query criteria that did not make sense: metric `reboot_e2e_result` has no label `site`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/701)
> Inhibit BMC_ConnectionFailed alerts if switch is down at site.

- config/federation/bigquery/bq_billing_hourly.sql
- k8s/prometheus-federation/deployments/bigquery-exporter.yml
This change introduces a new bigquery-exporter query to report service-level aggregate GCP billing and credit usage.
Because data exported to bigquery may be delayed for up to 1.6days (by observation) and because prometheus can only report "current" values, this change exports the hourly billing from two day prior to the current hour.
As well, this query uses a manually created view that unifies the staging and oti tables. There may be permission adjustments necessary to the default GKE user so that it can query that view in staging and oti projects.
I am also considering one or two additional queries that would aggregate by day, and another that would export only by GCE VMs, because there is machine type information that could help identify unnecessary costs. …
> Add basic bq billing information

- config/federation/bigquery/bq_billing_hourly.sql
Separating the service and product labels is much better for aggregating values in prometheus.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/704)
> Separate service and product labels

- config/federation/grafana/dashboards/NDT_GlobalTestRate.json
- config/federation/prometheus/prometheus.yml.template
- config/federation/prometheus/rules.yml
The Global Test rate dashboard is self-contained.
The recording rules make it possible to additionally update the Early Warning dashboard with ndt7 metrics once the new metrics are available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/706)
> Update recording rules & global dashboard with ndt7 metrics

- config/federation/prometheus/alerts.yml
This is intended to partially resolve https://github.com/m-lab/ops-tracker/issues/1117
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/705)
> Adds a new alert for when a TLS cert in use by NDT is nearing expiry.

- config/federation/grafana/dashboards/NDT_EarlyWarning.json
This change updates the NDT Early Warning dashboard to include ndt7 metrics.
The recording rules for ndt7 metrics were only recently added in https://github.com/m-lab/prometheus-support/pull/706 as a result most of current historical data does not include these. This means that sum operations `+` would return no metrics until there were both ndt5 and ndt7 metrics available. To work around this, and provide an easy way to clean up in the future, every ndt5+ndt7 query has a complementary query that matches a pattern like:
```
1st query: (ndt5 + ndt7)
2nd query: ndt5 unless ndt7
```
These two queries provide timeseries before (2nd) and after (1st) the ndt7 metrics are available. As well, the "unless" queries can be removed all at once in the future easily.
As well, this change removes some …
> Update NDT:EarlyWarning with ndt7 metrics

- config/federation/alertmanager/config.yml.template
This is intended to resolve #683
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/708)
> Inhibits alert MachineRunningWithoutK8sNode if the platform cluster scrape job is down

- config/federation/grafana/dashboards/NDT_Download_Speeds.json
This change updates the "NDT: Download Speeds" dashboard with the new metrics for ndt7 and consistent protocol names now used by ndt5.
This change also updates all panels to use the configured `$datasource`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/710)
> Update NDT: Download Speeds dashboard

- config/federation/prometheus/alerts.yml
Also replaces 'Ssl' in two alert names with 'Tls', which is more accurate, despite the fact that "ssl" still appears in the "tool" name.
This PR should resolve one of the actions items in https://github.com/m-lab/ops-tracker/issues/1123. Specifically, it should address the reason why none of the `TooManyNdt.*Down` alerts fire when we expect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/711)
> Adds experiment=ndt.iupui label to all lame-duck (by taint) metrics.

- config/federation/prometheus/alerts.yml
This is a case where the metric used by mlab-ns was update and is correct but the alert metric was never updated to query the same/correct metric.
This should resolve one of the action items on https://github.com/m-lab/ops-tracker/issues/1123.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/712)
> Changes metric node_filesystem_free_bytes to node_filesystem_avail_bytes

- config/federation/prometheus/prometheus.yml.template
This PR fixes the incorrect generation of the `site` label due to an old regex. I believe this fixes https://github.com/m-lab/rebot/issues/30 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/713)
> Update metrics relabeling to the v2 hostname format.

- k8s/prometheus-federation/deployments/script-exporter.yml
This change updates the script-exporter service address used to allocate monitoring access tokens.
This change is the second step of https://github.com/m-lab/dev-tracker/issues/600
While the service specifies locate-platform-* the `/v2/platform/*` URL will be routed to the locate-* service until the mlab-ns [dispatch.yaml file](https://github.com/m-lab/mlab-ns/blob/master/dispatch.yaml) is updated (3rd step).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/714)
> Use locate v2 "platform" target

- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
Also removes the alert for when scraping of that instance of node_exporter is down.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/716)
> Removes scraping of node_exporter on dns.measurementlab.net

- config/federation/bigquery/bq_ndt_s2c.sql
The combination of these two PRs move the expected data availability time 4-6 hours later than previously assumed by the `bq_ndt_s2c.sql` query. This change delays using the disco data by 18hrs rather than 12 to adjust to this later data availability.
* https://github.com/m-lab/gcp-config/pull/33
* https://github.com/m-lab/etl-gardener/pull/299
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/717)
> Delay daily discard calculation to 6 hours later

- config/federation/bigquery/bq_ndt_s2c.sql
Evidently the discard slo stopped working because of the v1 v2 node name migration around May 15th.
This change adds hostname normalization to the switch and ndt5 data so that the join continues to work as intended.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/718)
> Normalize disco node name for join

- k8s/prometheus-federation/deployments/gcs-exporter.yml
This change updates the gcs-exporter scan times to correspond to the expected end times of the GCS transfers from the daily-archive-transfer config in gcp-config. https://github.com/m-lab/gcp-config/blob/master/daily-archive-transfers.yaml#L48
We expect new archives to stop uploading to a date at 02:30. That the archive-mlab-oti transfer will be complete by 06:30, and the archive-measurement-lab transfer will be complete by 10:30 (which is when gardener is scheduled to begin the daily reprocessing).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/719)
> Update scan times to correspond to new daily archive transfers

- config/federation/prometheus/alerts.yml
Modifies `GCSTransfers_ArchiveFilesDoNotMatchOrMissing` alert to sum difference so that we don't get separate alerts for every experiment/datatype combination, but instead one lump sum indicating a non-zero value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/720)
> Sums archive file count increase differences

- config/federation/grafana/dashboards/Ops_Tactical_SRE_Overview.json
Reloader is a service that watches the TLS secret (certificate) for change. When the certificate change it will trigger a rolling update of any DaemonSets that mount the secret. This PR adds a new panel to give us some insight into when Reloader has triggered rolling updates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/721)
> Adds a new panel to display when Reloader has triggered a rolling update of  a DaemonSet

- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
We had a situation recently where we _thought_ that our staging and production clusters were upgraded from 1.15.10 to 1.16.7. `kubectl get nodes` showed 1.16.7, but while the kubelet, kubeadm, CNI plugins, and crictl were all the version we expected, under the hood the core k8s components (kube-apiserver, kube-controller-manager, kube-scheduler) were all still running 1.15.10. This situation did not become apparent until we went to upgrade the cluster to 1.17.8 and discovered that kubeadm was unhappy with the cluster state.
This PR attempts to add an alert that will notify us of version skew in the API cluster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/725)
> Adds a new alert for version skew in the API cluster.

- config/federation/prometheus/alerts.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/727)
> Adds a new alert for when the token-server cluster is not accessible.

- config/federation/bigquery/bq_gardener_parse_time.sql.template
The travis build triggered one deployment, but looking at BQ logs, it doesn't seem to have changed the query that was run.
https://pantheon.corp.google.com/bigquery?project=mlab-sandbox&page=queries&queryFilter=%255B%257B_22k_22_3A_22_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22union_5C_22_22%257D%255D
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/732)
> add ndt7 and annotation to bq_gardener_parse_time

- config/federation/prometheus/prometheus.yml.template
To match the change from https://github.com/m-lab/prometheus-support/pull/739 this change makes a similar change to the prometheus-federation configuration. The original cluster+nodepool value is set to "nodepool=" and a static "cluster=prometheus-federation" is now set for all pod metrics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/740)
> Add default cluster label to pod metrics in federation cluster

- config/federation/prometheus/alerts.yml
Fluentd is being replaced by Vector. This PR modifies the previous `PlatformCluster_FluentdMissing` alert to work for Vector.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/741)
> Replaces the FluentdMissing alert with a VectorMissing alert.

- config/federation/prometheus/alerts.yml
Resolves m-lab/prometheus-support#742.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/744)
> Uses SSH probes to determine 'zombie' nodes. 

- config/federation/grafana/dashboards/NDT_EarlyWarning.json
- config/federation/grafana/dashboards/Ops_SwitchOverview.json
- k8s/data-processing/deployments/kube-state-metrics.yml
- k8s/data-processing/deployments/prometheus.yml
- k8s/prometheus-federation/deployments/bigquery-exporter.yml
- k8s/prometheus-federation/deployments/github-receiver.yml
- k8s/prometheus-federation/deployments/mlabns-stackdriver.yml
- k8s/prometheus-federation/deployments/pushgateway.yml
Now that DISCOv2 is in production we can start making arrangements to retire snmp_exporter. Before doing that, however, we need to modify any dashboards that are currently using metrics from the snmp_exporter. This PR migrates two dashboards to use DISCOv2 metrics.
For the NDT:EarlyWarning dashboard all that was required was to migrate all the custom recording rules from the prometheus-federation cluster and to change the dashboard's datasources to Platform Cluster ones.
For Ops:SwitchOverview the principle change is adding a `machine=~"mlab2.*"` modifier to all queries. The use of mlab2 is arbitrary, as uplink metrics are collected by all 4 machines at a site. The datasources were also changed from prometheus-federation to Platform Cluster. Two panels were outright removed because they …
> Updates SwitchOverview and NDT:EarlyWarning dashboards to use DISCOv2 data

- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
This PR updates, removes and adds various alerts having to do with DISCO and SNMP scraping of switches. Currently, we use snmp_exporter to get switch metrics for use in Prometheus and Grafana. Now that DISCOv2 is deployed to production, and exports all those metrics, we can retire snmp_exporter and start using DISCOv2 metrics. This PR is part of that transition.
Old collectd alerts were removed. One new alert for DISCOv2 was added. Various existing alerts for collectd were modified to be appropriate for DISCOv2.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/747)
> Converts/updates alerts for collectd to DISCOv2.

- IPV6_MONITORING.md
Linode will soon no longer support /116 IPv6 prefixes in their Atlanta datacenter. We have to migrate to a /64, which turns out to be much easier to configure... just give the whole prefix to Docker. This PR updates the readme file for setting up the IPv6 monitoring VM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/748)
> Updates instructions on setting up the IPv6 monitoring VM.

- config/federation/prometheus/alerts.yml
Today I discovered that mlab3-bcn01 has been down for a week or so, and we didn't know about it. We have a `PlatformCluster_NodeNotReady` alert that is supposed to alert of us these things, but it didn't. I can't recall why now, but when I originally wrote the alert I added an exception for when "the scrape job for the entire node is down". For mlab3-bcn01, we didn't get an alert because the scrape job for the entire node was down, because the layer2 link to the switch is down. We need to know about these conditions. This PR modifies the alert removing the condition that the scrape job to the node be up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/750)
> Fixes the NodeNotReady alert

- config/federation/bigquery/bq_ndt_s2c.sql
Currently, the bigquery-exporter query used for detecting NDT download test that may have been coincident with switch discards only looks at NDT5 tests. This is a problem, since the vast majority of NDT tests against the platform are NDT7 (from Onebox). This PR adds NDT7 test results to the query.
_NOTE_: some of the changes in this PR are the result of me using the auto-format feature in the BigQuery Web UI. However, the principal changes (`UNION ALL` query additions) should be pretty easy to pick out.
This PR is intended to resolve #749.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/752)
> Adds NDT7 test results to bq_ndt_s2c.sql query

- config/federation/prometheus/alerts.yml
I thought that the recent PR #750 fixed the `NodeNotReady` alert, but it didn't. It fixed one deficiency, but I just discovered another... that in many (probably most) cases the `status` label for down nodes will be `unknown`, not `false`. This PR causes the alert to consider either status.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/754)
> Fixes NodeNotReady alert to also consider a status of 'unknown'

- config/federation/prometheus/alerts.yml
If a switch down (not pingable), then nothing behind it can be working either, so don't fire the `NodeNotReady` alert if the switch is not pingable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/757)
> Adds a condition that the switch is pingable for NodeNotReady alert.

- k8s/prometheus-federation/deployments/stackdriver.yml
The Vector DaemonSet in the platform cluster is now pushing kernel log messages to Google Logging. I have created new log-based metrics named `platform_cluster_kernel_logs` in each project. This PR deploys a new stackdriver-exporter Deployment to prometheus-federation that will scrape all user-defined metrics. In the future it could scrape other things, but for now it is only scraping this one thing.
_NOTE_: There is already another stackdriver-exporter Deployment in prometheus-federation named `mlabns-stackdriver`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/763)
> Adds new stackdriver-exporter deployment for projects.

- k8s/prometheus-federation/deployments/reboot-api.yml
This PR explicitly sets the `-reboot.bmcport` command-line flag for the reboot-service container.
This change is related to fully automating the DRAC configuration during stage1/2 (https://github.com/m-lab/epoxy/issues/94)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/764)
> Explicitly set -reboot.bmcport for reboot-service

- config/federation/grafana/dashboards/KeepThePlatformRunning.json
This is a start to a high-level summary dashboard that verifies that the platform is still running end to end.
The initial set of panels include aggregate network usage, total ndt measurements, bytes uploaded to GCS, and rows processed by the batch ETL pipeline.
The panels are oriented left to right to mirror the path of data through the system.
Possibilities for future refinements include:
* request rates to Locate API
* metrics from the ETL pipeline corresponding only to the current day rather than batch
* 24h summaries using recording rules for faster loading
* BQ metrics like bytes queries, number of queries, or users accessing our data.
--- …
> Add a high-level summary dashboard

- config/federation/grafana/dashboards/KeepThePlatformRunning.json
This fix only uses one "uplink" metric from each site.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/766)
> Use max uplink from each site

- config/federation/prometheus/alerts.yml
The E2E test results are cached for an hour. If credentials are created and then the site is immediately taken out of GMX, this alert would fire because credentials weren't there when the last check happened, then clear itself at the next check.
By requiring that the condition is true for `1h` before the alert fires we prevent this.
Not sure if this also closes https://github.com/m-lab/reboot-service/issues/40 as it's a workaround. @nkinkade what do you think?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/767)
> Change BMC_CredentialsNotFound to only fire after 1h

- k8s/prometheus-federation/deployments/reboot-api.yml
This PR updates reboot-api to v0.6.0, which supports the `keyboard-interactive` SSH authentication method. This version hasn't been tagged yet, but will be in a while. I'll make sure to merge it only after reboot-api:v0.6.0 becomes available on Docker Hub.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/768)
> Bump reboot-api to v0.6.0

- config/federation/grafana/grafana.ini
- k8s/prometheus-federation/deployments/grafana.yml
Currently, anyone with a Google account can login to our Grafana instance. This PR limits the Google account domains to `measurementlab.net` and `google.com`. It also updates Grafana to essentially the latest version.
I verified that the login restriction is minimally working by trying to login with a personal Gmail account and got:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/772)
> Updates Grafana and limits Google OAuth login to measurementlab.net and google.com

- config/federation/prometheus/alerts.yml
Limits query to only use the `ssh_v4_online` probe to eliminate duplicate results for both IPv4 and IPv6 probes, making the problem seem worse than it is (by double). This should cause the query to only ever return a single result per node where the problem exists, instead of 2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/773)
> Limits MachineRunningWithoutK8sNode to only ssh IPv4 probes.

- config/federation/prometheus/prometheus.yml.template
This change updates the blackbox exporter relabel_config rules to create "target=" parameters that include hostnames with a trailing "." to optimize DNS lookups within GKE.
This change only modifies the target parameter sent to the blackbox exporter and preserves all other labels used on prometheus metrics. There should be no observable change to metrics.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/774)
> Add trailing . for DNS lookups by blackbox exporter targets

- config/federation/grafana/dashboards/Wehe_access_envelope.json
This change adds a new dashboard for the Wehe service on M-Lab. It includes panels for the access envelope, the wehe service itself, as well as total files saved according to pusher.
Review should include in person talk-through.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/776)
> Add wehe dashboard

- config/federation/grafana/dashboards/NDT_AccessControl.json
This change adds a simple dashboard for the NDT access control package. It includes metrics for the TX, Token, and ndt server, mirroring the stages of access control enforced by the NDT server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/778)
> Add NDT Access Control dashboard

- delete-grafana-ds.sh
Currently Grafana does not seem to be updating provisioned datasource. A workaround which we documented in this repository's README is to remove them via the Grafana APIs and then restart the pod.
Since we added an OAuth proxy in front of Grafana, there is an additional step which is grabbing a valid session cookie from a browser and pass it via curl when making requests to the API.
This PR adds a script to try to make the process (slightly) less cumbersome.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/781)
> Add script to delete Grafana datasources

- config/federation/prometheus/prometheus.yml.template
- k8s/prometheus-federation/deployments/oauth2-proxy.yml
Today, the production alert `PlatformCluster_NodeNotReady` fired for mlab{1,2,3}-lis01. However, the switch was down too, and NodeNotReady alerts should not fire when the switch is down. Investigation revealed that ICMP switch probes have been broken for the past couple weeks in all project, apparently the result of this change:
https://github.com/m-lab/prometheus-support/commit/3a2f404b1a5ca4ccce46143792dfc2418403d733
This PR should fix that issue by making an explicit port specification to target machines optional.
Additionally, this PR adds the domain northeastern.edu to the list of permitted email domains for oauth2-proxy, as we try to figure out a way to get the Wehe team access to the Granfa.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> Fixes blackbox-exporter scrapes for targets without port specifications

- config/federation/prometheus/prometheus.yml.template
We got a ` TooManyNdtTlsIpv4ServersDown` down alert in staging not too long after I merged #782. Closer inspection revealed that the issue had something to do with a greedy regexp pattern which was gobbling up the entire string before it got to the second matching group. This PR should fix that by more appropriately scoping the matching so that grouping works as expected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/783)
> Fixes greedy regexp matching

- k8s/prometheus-federation/deployments/oauth2-proxy.yml
oauth2-proxy does not seem to automatically authorize subdomains, so `neu.edu` does not allow `husky.neu.edu` to log in. This change explicitly allows `husky.neu.edu`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/785)
> Enabled husky.neu.edu in oauth2-proxy.yml

- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
This PR adds a new alert which fires when a machine hasn't been rebooted in more than 90d. It builds on the [recent work to cause all platform nodes to get rebooted when up for more than 60d](https://github.com/m-lab/epoxy-images/pull/200).
It also adds a new `relabel_config` config for the kubernetes-pods job which will cause the job to look for the `prometheus.io/port` annotation on a pod, and if it exists, to only scrape the pod on that port.
This PR is expected to resolve #786.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/787)
> Adds new alert for machine uptime + only scrape annotation port

- config/federation/prometheus/prometheus.yml.template
This list is statically defined and didn't include the new -basicauth URL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/790)
> Add prometheus-basicauth URL to the list of monitored ingresses

- k8s/data-processing/deployments/node-exporter.yml
This PR copies the node-exporter DaemonSet into the data-processing cluster. I mostly wanted this so I could check network utilization on the stats-pipeline node.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/789)
> Add node-exporter DS to the data-processing cluster

- config/federation/prometheus/prometheus.yml.template
Step 2/3: Change the prometheus-federation config to scrape the -basicauth domain for platform-cluster prometheus.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/791)
> Scrape platform-cluster prometheus on the -basicauth domain

- config/federation/prometheus/alerts.yml
- k8s/prometheus-federation/deployments/reboot-api.yml
This PR bumps the reboot-api version to v0.6.1, which includes the fixes to issue https://github.com/m-lab/reboot-service/issues/39.
This PR also updates the alerts that were based on the old `reboot_e2e_result` metric. The new metric name `reboot_e2e_success`, and with these changes there will only be a single alert for any E2E test failure. It will be up to the operator to look at the alert and inspect the `reason` label of the alert to find out what may have caused the failure.
Additionally, the PR removes the `description` annotation of the new `BMC_E2eTestFailed` alert to only point to the new [documentation for the alert](https://github.com/m-lab/ops-tracker/wiki/Alerts-&-Troubleshooting#bmc_e2etestfailed).
---
This change is [<img src="https://reviewable.io/review_button.svg" …
> Bumps reboot-api version and adjusts reboot e2e test alerts

- k8s/prometheus-federation/deployments/oauth2-proxy.yml
Following up to https://github.com/m-lab/k8s-support/pull/559, this PR allows the "redirect URL" to be different from the domain where the authentication request originated. Specifically, it can be anything ending in `.measurementlab.net`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/793)
> Allow redirection to all .measurementlab.net domains

- config/federation/grafana/dashboards/Stats_Pipeline_Monitoring.json
This PR adds a new Grafana dashboard to monitor the status of the stats-pipeline service.
It can be seen at https://grafana.mlab-sandbox.measurementlab.net/d/07rwXefMz/stats-pipeline-monitoring?orgId=1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/794)
> Add Stats Pipeline Monitoring Grafana dashboard

- config/federation/alertmanager/config.yml.template
Alert names changed over time, but this inhibit rule did not. This PR updates the inhibit rule to match the current alert names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/796)
> Fixes broken inhibit rule

- k8s/prometheus-federation/deployments/bigquery-exporter-3h.yml
- k8s/prometheus-federation/deployments/bigquery-exporter-5m.yml
This change updates to the latest version of the prometheus-bigquery-exporter v1.1.0 that includes bug fixes that prevented our update until now.
With this change, the bqx should automatically discover and reload query changes in the configmap. Previously this was a manual step.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/799)
> Update to latest version of bqx

- config/federation/prometheus/alerts.yml
- config/federation/prometheus/rules.yml
This change adds a new recording rule and new alert based on the GCS exporter and the BQ exporter metrics. The new alert  verifies that archives found in GCS for ndt7 have been processed by ETL and found in BigQuery.
The pieces of our pipeline: pusher -> gcs transfers -> archives parsed -> table availability
To date, we have alerts for pusher, gcs transfers, and table availability. However, if archives are missed, we would not know.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/800)
> Add recording rule for daily gcs archive counts

- config/federation/grafana/dashboards/MLABNS_PrometheusQueries.json
- config/federation/prometheus/alerts.yml
Currently, we have alerts for when too many ndt5 services are down, but none for ndt7, even though the vast majority the platform's traffic comes from ndt7 test. This PR attempts to rectify that issue. I have also renamed the alerts to indicate whether we are talking about ndt5 or ndt7, and uses all caps for acronyms too.
Additionally, a [new alert description has been added to the ops-tracker Alerts & Troubleshooting wiki page](https://github.com/m-lab/ops-tracker/wiki/Alerts-&-Troubleshooting#PlatformCluster_TooManyNDTServersDown) for this class of alert.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/802)
> Adds alerts for ndt7 mlab-ns queries

- k8s/prometheus-federation/deployments/bigquery-exporter-3h.yml
- k8s/prometheus-federation/deployments/bigquery-exporter-5m.yml
This change updates the version of the bigquery exporter to prevent persistent failures in response to a collector registration error. This kind of error can occur during a k8s maintenance event that restarts a pod container but during a transient credential failure for the BQX on startup.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/803)
> Update bigquery-exporter version

- config/federation/prometheus/alerts.yml
This change updates the GCSTransfers_ArchiveFilesDoNotMatchOrMissing firing threshold to prevent false positives from expected variance from the GCS Transfer service.
This change is in response to the alert https://github.com/m-lab/dev-tracker/issues/664
This change moves the alert description to our alerts Wiki.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/804)
> Increase pending delay & move description to wiki

- config/federation/grafana/dashboards/K8s_WorkloadOverview.json
- config/federation/grafana/dashboards/Ops_Tactical_SRE_Overview.json
**SRE Overview dashboard**
* "Pod container restarts" is no longer an absolute number, but the 1d increase.
* The "probable container OOM" panel now displays `sum by (machine, priority)` for the new custom logs-based metrics in each project. Kernel log messages are uploaded to Monitoring by the Vector DaemonSet.
* "Rolling updates triggered by Reloader" is no longer an absolute number, but instead the 1d increase.
* Adds new "Cluster versions" panel (also on the WorkloadOverview dashboard)
* Small updates to the Alerts panel:
* Hides the "Time" column, which was always the current time.
* Replaces static `[7d]` range for the variable `$__range` so that the panel follows the selected time frame.
**WorkloadOverview dashboard**
* Removes "Probable container OOMs" (can't be on this dashboard …
> Improves SRE Overview and Workload Overview dashboards

- k8s/prometheus-federation/deployments/script-exporter.yml
This should resolve the long-standing bug we have had in the script_exporter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/809)
> Bumps script-exporter-support image version to v0.2.3

- config/federation/grafana/dashboards/MLABNS_PrometheusQueries.json
- config/federation/prometheus/alerts.yml
There is [an open PR in the mlab-ns repo](https://github.com/m-lab/mlab-ns/pull/251) which will cause mlab-ns to ignore monitoring data (i.e., leave datastore stale) when too large a percent of a service appears to be offline. It is important that an alert fires whenever this occurs, else mlab-ns will be serving stale data without anyone knowing. We already have alerts for various NDT services, but are currently lacking Neubot alerts. This PR adds alerts for Neubot to avoid the case where mlab-ns ignores monitoring data, and we get no alert.
This PR also updates the `PrometheusQueries` dashboard, adding panels for Neubot.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-su …
> Adds two new "mlab-ns" alerts for Neubot

- k8s/prometheus-federation/deployments/node-exporter.yml
Currently, our node-exporter DaemonSet in prometheus-federation does not deploy pods to the `static-outbound-ip` node pool nodes in GKE due to the taint `outbound-ip=static:NoSchedule` on those nodes. This small PR simply adds a toleration to the node-exporter DaemonSet so that it will deploy to those nodes too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/811)
> Configures node-exporter to tolerate outbound-ip nodes

- k8s/prometheus-federation/deployments/cadvisor.yml
- k8s/prometheus-federation/deployments/node-exporter.yml
- k8s/prometheus-federation/deployments/script-exporter.yml
This PR:
* updates the script_exporter image to v0.2.4, [bringing in some bug fixes](https://github.com/m-lab/script_exporter/pull/7)
* adds a toleration to the CAdvisor pod so that it will deploy to the static-outbound-ip nodes
* Enables the `processes` node_exporter collector so that we can look for runaway PID issues
* Updates the updateStrategy for node-exporter so that it rolls out automatically (was `OnDelete` before for some reason)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/812)
> Updates script_exporter + pins node_exporter version

- README.md
It was discovered today that perhaps the default VM auth scopes have changed since the `static-outbound-ip` node pools were first set up some time ago. I recreated all of them in the past couple days to modify the underlying node machine types (more CPU), and the reboot-api started throwing errors that it couldn't read credentials from Datastore. I recreated the node pools in all project with an explicit scope of `datastore`, which resolved the issue. This PR just updates the documentation to reflect the new requirement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/816)
> Updates README for "Static outbound IP pinning"

- k8s/prometheus-federation/services/script-exporter.yml
The impetus for this change is how our e2e test caching works. The caching is machine-local, but the script-exporter Deployment has two replicas. You never know which replica is going to get the request from Prometheus. This means that an e2e test for a given machine is going to happen at least twice as often as we expect, and not just roughly once every 5 minutes or so. This change should cause all tests, or at least a majority, to go to one machine, allowing the caching to work more as intended. The default session affinity timeout is 10800 (3h), which means that the bulk of tests should occasionally flip flop back and forth between the replicas in the Deployment.
--- …
> Sets sessionAffinity=ClientIP for script-exporter service

- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
We have [an alert for when switch errors exceed a certain threshold](https://github.com/m-lab/prometheus-support/blob/master/config/federation/prometheus/alerts.yml#L763). However, the alert cannot currently ever fire because we do not scrape the `ifInErrors` metric from the platform-cluster. This PR should resolve that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/821)
> Scrapes ifInErrors from platform-cluster

- k8s/prometheus-federation/deployments/script-exporter.yml
The only change is the image should be that it has pulled in the latest changes from the [wehe-cmdline repo](https://github.com/NEU-SNS/wehe-cmdline), and the only change there is the addition of a `@` prefix to the username for the cli client so that they can identify it in the data and filter it out. Currently, the e2e monitoring is polluting their data, with no clear way to filter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/822)
> Bumps script-exporter-support image to v0.2.8

- config/federation/prometheus/prometheus.yml.template
With the move of platform alerts to the platform cluster, I also did some relabeling working. Previously, all metrics scraped from the platform clusters were given a label of `cluster="platform-cluster"`. Now that we have alerts coming from multiple clusters, alerts have a new label named `cluster` so you know where the alert originated. Presently the possible values are `prometheus-federation` and `platform`. This PR removes the redundant `-cluster` from the value of the `cluster` label so that it is more clean looking. It also fixes at least one firing alert that expects to find a label of only `cluster="platform"`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-suppor …
> Fixes the 'cluster' label value for platform scrape job

- config/federation/grafana/dashboards/NDT_CanaryReleaseMonitoring.json
This PR adds a new Grafana dashboard to monitor ndt-server canary releases.
https://grafana.mlab-sandbox.measurementlab.net/d/kk1Zukz7k/ndt-canary-release-monitoring?orgId=1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/830)
> Add "NDT: Canary Release Monitoring" dashboard.

- generate-prometheus-targets.sh
The current blackbox-exporter module (tcp_{v4,v6}_online) will probe
port 443 only to verify that it is listening, but does do the TLS
handshake. This change will cause it to additionally do a TLS handshake,
more fully verifying the "upness" and proper configuration of the
target.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/835)
> Configures BBE to probe ndt7 using TLS

- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
- k8s/prometheus-federation/deployments/gmx.yml
This commit should resolve the case where IPv6 is down for one or all machines at a site without anyone knowing about it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/836)
> Adds new alert for when IPv6 is down for too long

- config/federation/grafana/dashboards/MLABNS_PrometheusQueries.json
A couple months ago we modified the value of the `cluster` label from `cluster="platform-cluster"` (redundant use of "cluster"), to just `cluster="platform"`. These dashboards were never updated after that change happened.
TODO: These "mlab-ns" queries are triplicated between the mlab-ns repository, the prometheus-support alerts.yml file, and this dashboard. We need to find a way to have a single source for the queries to avoid synchronization issues like these.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/837)
> Fixes "cluster" label values in MLABNS_PrometheusQueries dashboard

- config/federation/prometheus/alerts.yml
This change updates the `PlatformCluster_IPv6AtSiteDownForTooLong` alert query to use the `unless on(machine)` operator for all conditions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/838)
> Use unless on() for all conditions of ipv6 alert query

- k8s/prometheus-federation/deployments/grafana.yml
This PR updates our Grafana version to 8.1.1
This version now needs plugins to be signed. Our two plugins in sandbox were quite outdated and not signed:
- grafana-worldmap-panel
- camptocamp-prometheus-alertmanager-datasource (_I suspect we're not using this anywhere_)
Since they were manually installed (according to the README), I've also manually updated them from within the grafana-server container:
```
$ grafana-cli plugins update grafana-worldmap-panel
$ grafana-cli plugins update camptocamp-prometheus-alertmanager-datasource
```
This also removed an initContainer that was used to fix some permission issue, resolving a TODO. Grafana's data disk is permanent, so (as the TODO mentioned) there should be no reason to keep running `chown` every time Grafana starts.
---
This change …
> Update Grafana to version 8.1.1

- config/federation/grafana/dashboards/Stats_Pipeline_AnnotationExportMonitoring.json
This change adds a new Grafana dashboard based on the Stats Pipeline Monitoring dashboard modified to specifically monitor the [Annotation Export process][1].
Dashboard visible here:
https://grafana.mlab-sandbox.measurementlab.net/d/XokjBPKnj/annotation-export-monitoring?orgId=1&refresh=1m
[1]: https://github.com/m-lab/stats-pipeline/blob/master/k8s/data-processing/deployments/annotation-export-template.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/850)
> Add Annotation Export Monitoring dashboard

- k8s/prometheus-federation/deployments/external-dns.yml
- k8s/prometheus-federation/deployments/kubeip.yml
- k8s/prometheus-federation/roles/rbac-kubeip.yml
Additionally, the PR moves the kubeip deployment, and related resources, to the kube-system namespace, resolving this issue: https://github.com/m-lab/prometheus-support/issues/824
**NOTE**: Changing the namespace of the kubeip deployment and related resources requires recreating the GCP service account key Secret in the kube-system namespace:
```
kubectl get secret kubeip-key -o jsonpath='{.data.key\.json}' | base64 --decode > key.json
kubectl create secret generic kubeip-key --namespace kube-system --from-file key.json
```
... and also deleting the resources in the default namespace:
```
kubectl delete deployment kubeip
kubectl delete secrets kubeip-key
kubectl delete serviceaccount kubeip
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> Updates container image versions for external-dns and kubeip deployments

- config/federation/grafana/dashboards/NDT_CanaryValidation.json
This updates the dashboard variables in the Canary Validation dashboard to be sourced from the mlab-oti BQ datasource by default.
Additionally, it sets the default project to mlab-oti.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/854)
> Update default BQ DS for Canary Validation dashboard

- config/federation/grafana/dashboards/NDT_CanaryValidation.json
This PR adds an additional `$datasource` variable to the Canary Validation dashboard and makes every panel in the dashboard use it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/855)
> Make every panel's datasource configurable

- config/federation/grafana/dashboards/NDT_Client_Rates_Quantiles_Heatmaps.json
This change adds a new dashboard that provides multiple different views on NDT measurements in one dashboard. This dashboards includes panels that:
For the selected protocols:
* Test volume per metro, globally.
For all selected sites and protocols:
* test rate (volume)
* client performance quantiles over the last week
* client median performance over the last three weeks
* client performance heatmap (how many measurements were within a performance window)
* test count histograms for total client measurements
This combination of panels is helpful for noticing and investigating regional changes. e.g. more tests by protocol in a particular region, then to select only sites in that region to look at performance over time. This view can also provide qualitative hints about common service tiers …
> Add a new dashboard for novel windows on NDT measurements

- config/federation/grafana/dashboards/NDT_Client_Rates_Quantiles_Heatmaps.json
Previously this dashboard reserved the upper-right panel to show all metros. But, I kept editing it to use only the selected metros. Since "all metros" is an option I think this panel should use the `$site` variable as all the other panels do. This change makes this modification.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/863)
> Update per-metro query to only use specified sites

- k8s/data-processing/deployments/prometheus.yml
- k8s/prometheus-federation/deployments/prometheus.yml
This is an experimental feature which is supposed to make startups
faster. This is running in the platform cluster and seems to work as
advertised.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/864)
> Adds flag --enable-feature=memory-snapshot-on-shutdown

- k8s/data-processing/deployments/kube-state-metrics.yml
- k8s/prometheus-federation/deployments/kube-state-metrics.yml
This PR updates kube-state-metrics in both the prometheus-federation and data-processing clusters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/865)
> Updates kube-state-metrics to v2.2.4

- config/federation/prometheus/alerts.yml
The alert started misfiring in staging. 
On further inspection, this is because the Gardener self-reported throughput the alert is looking at is from 48h to 24h ago, while the throughput detected in BQ is from the last 24h until now.
With this change, they are both looking at the last 24h period.
We can observe that they line up for that time period in the Throughput section of the dashboard (where there is no offset in the query).
https://grafana.mlab-sandbox.measurementlab.net/d/q4MrNzh7k/pipeline-slis?orgId=1&var-project=mlab-staging&var-PrometheusDS=Prometheus%20(mlab-staging)&var-Gardener2_DS=Data%20Processing%20(mlab-staging)
We can also see that the alert gets resolved with the modified query.
https://prometheus.mlab-staging.measurementlab.net/graph?g0.expr=increase(gardener_jobs_to …
> Remove offset from throughput alert

- config/federation/prometheus/alerts.yml
Fix alert misfire.
Before: https://prometheus.mlab-oti.measurementlab.net/graph?g0.expr=up%7Bservice%3D%22annotator%22%7D%20%3D%3D%200%20or%20absent(up%7Bservice%3D%22annotator%22%7D)&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=4d
After: https://prometheus.mlab-oti.measurementlab.net/graph?g0.expr=sum(up%7Bservice%3D%22annotator%22%7D)%20%3D%3D%200%20or%20absent(up%7Bservice%3D%22annotator%22%7D)&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=4d
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/872)
> Make annotation service alert fire only when all instances are down

- k8s/data-processing/deployments/prometheus.yml
This is part of the larger project to pin and/or update container image version in our clusters.l
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/874)
> Pins busybox in data-processing to version 1.34.1

- config/federation/prometheus/alerts.yml
The ` bq_gardener_historical_throughput` query is run every 3h.
The current threshold for the alerts that use this query is 3h and 10mins. T
he GardenerHistoricalThroughputIsStalled alert fired because it took BQ Exporter 3h and 13mins to report the new throughput.
This PR is adjusting the threshold to 4h.
Example:
Alert condition became true at 18:15 and resolved itself at 21:28 (3h and 13mins later).
https://prometheus.mlab-oti.measurementlab.net/graph?g0.expr=increase(gardener_jobs_total%7Bdaily%3D%22false%22%2Cstatus%3D%22success%22%7D%5B1d%5D)%20%3E%200%20unless%20on(datatype)%20bq_gardener_historical_throughput%20%3E%200&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=3h28m21s591ms&g0.end_input=2022-02-03%2021%3A40%3A04&g0.moment_input=2022-02-03%2021%3A40%3A04
---
This …
> Relax threshold for bq_gardener_historical_throughput alerts

- config/federation/grafana/dashboards/Alert_ParserDailyVolumeTooLow.json
- config/federation/grafana/dashboards/KeepMLabRunning.json
- config/federation/prometheus/alerts.yml
- config/federation/prometheus/rules.yml
The `etl_test_count` metric has been renamed to `etl_test_total` in https://github.com/m-lab/etl/pull/1053. 
Its references in prometheus-support need to be updated.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/879)
> Update etl_test_count references

- config/federation/prometheus/alerts.yml
- k8s/prometheus-federation/deployments/mlabns-stackdriver.yml
This PR adds a new alert which aims to give us some confidence that Vector in the platform clusters is working as intended. A new logs-based metric named platform-cluster-container-logs was created, and we query this new metric to determine if Vector is pushing container logs to Stackdriver. The new metric is a count of log entries on a per-node basis. When the sum of that count over an hour is equal to 0 for 24h, then this alert should fire.
This PR also updates the mlab-ns instance of stackdriver_exporter to v0.11.0, and moves to using the proper Docker repository.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/881)
> Adds new alert to monitor Vector functionality

- config/federation/bigquery/bq_gardener_historical.sql.template
This name should match the name in Gardener, to prevent an inventory alert from firing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/884)
> Change datatype name in bq_gardener_historical query to "switch".

- config/federation/prometheus/alerts.yml
- k8s/prometheus-federation/deployments/github-receiver.yml
The current alert is based on a misunderstanding I had about how metrics from Stackdriver work. This updated alert should warn us when a node's status is "Ready=True", but there is no stackdriver metric indicating that any log entries were received by Stackdriver for a node.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/883)
> Updates alert for when Stackdriver is missing container logs for a node

- config/federation/grafana/dashboards/K8s_SiteOverview.json
The diff is pretty large for this PR, apparently mostly containing changes that Grafana automatically added in the exported JSON due to this dashboard having been created with some older version of Grafana.
There are only two changes I made:
* Update the host network panel to look for data for both `eth0` _and_ `ens4` (virtual nodes).
* Updates the "Data partition" singlestat panel to display the usage of the root device (/dev/root) for virtual nodes. This will yield the same value as the "Rootfs" panel, but may(?) reduce confusion, since virtual nodes do everything on a single disk. That is, the rootfs and the "data partition" are one and the same.
--- …
> Updates to SiteOverview to better represent virtual sites

- config/federation/bigquery/bq_ndt_s2c.sql
This PR reintroduces the query change that was excluded from https://github.com/m-lab/prometheus-support/pull/880 so that we could release prometheus-support. This change should not be merged until etl-schema is released, since the `measurement-lab.utilization.switch` view won't exist until then.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/885)
> Update bq_ndt_s2c.sql to use v2 datatype schema

- config/federation/bigquery/bq_gardener.sql.template
- config/federation/bigquery/bq_gardener_historical.sql.template
- config/federation/bigquery/bq_gardener_parse_time.sql.template
This change replaces parse time monitoring of `tcpinfo_legacy` with `ndt_raw.tcpinfo` to complement the new v2 tcpinfo parser. This change also adds tcpinfo to the `bq_gardener_historical_*` for the inventory alert.
This change does not yet pdate `bq_annotation.sql` since it references `measurement-lab`, which depends on a production deployment of the new parser.
Part of:
* https://github.com/m-lab/etl/issues/1066
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/888)
> Check parsetime for raw_ndt.tcpinfo

- config/federation/bigquery/bq_annotation.sql
The BQ Exporter is generating this error `2022/04/04 20:11:43 collector.go:81: googleapi: Error 400: Invalid project ID '{{PROJECT}}'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash., invalid` because the sql file is not a template.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/893)
> Change {{PROJECT}} back to 'measurement-lab'

- config/federation/bigquery/bq_daily_discuss.sql
Due to daily processing delays between UTC 00:00:00 and 10:30:00 UTC, `>` will briefly exclude all dates with rows, yielding a false counts of zero. This change adds `>=`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/897)
> Use greater than or equal to include previous day

- config/federation/prometheus/alerts.yml
This change adds a new alert based on the metrics produced by https://github.com/m-lab/prometheus-support/pull/895
This alert should fire when queries fail (for one reason or another) when run by a service account with the same permissions as users of the discuss@measurementlab.net mailing list.
This change includes a new playbook entry at https://github.com/m-lab/ops-tracker/wiki/Alerts-&-Troubleshooting#pipeline_dailydiscussaccesszeroormissing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/903)
> Add alert for queries from discuss@ users

- config/federation/prometheus/alerts.yml
After removing the v1 gardener deployments, I found that an alert checks whether these deployments are running.
This change removes the alert that is now obsolete.
Part of:
* https://github.com/m-lab/etl/issues/1074
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/904)
> Remove v1 gardener alert

- config/federation/prometheus/alerts.yml
After deleting the annotation-service from all projects, the `ETL_AnnotationDownOrMissing` alert is now obsolete. This change removes it.
Part of:
* https://github.com/m-lab/etl/issues/1074
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/905)
> Remove alert for annotation service

- config/federation/prometheus/prometheus.yml.template
This change updates set of federated metrics scraped from the `data-processing` cluster to include the downloader metrics.
This is part of:
* https://github.com/m-lab/etl/issues/1074
* https://github.com/m-lab/downloader/pull/44
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/907)
> Add downloader metrics to data-processing cluster

- .travis.yml
This PR removes a warning about `io/fs` not existing in Go < 1.16 that appeared in build outputs while installing promtool.
Unfortunately it seems the prometheus repository does not have a /v2 folder, so `go install ...@v2.x.x` does not work. I kept the installation as it was (repository download + manual git checkout of the desired tag), disabling modules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/908)
> Update go version in .travis.yml to 1.18

- k8s/prometheus-federation/deployments/script-exporter.yml
Script exporter generating `script_success` metric https://prometheus.mlab-sandbox.measurementlab.net/graph?g0.expr=script_success&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=6h.
This is part of https://github.com/m-lab/prometheus-support/issues/912.
Original PR where the "locate-platform" target was added: https://github.com/m-lab/prometheus-support/pull/714.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/913)
> Target the original 'locate' service in script-exporter

- .travis.yml
The prometheus-support travis build is chronically delayed by the steps to download a pinned version of promtool. This change uses a pinned version of a docker image which should be available for download faster than git+build.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/915)
> Use promtool from docker image

- config/federation/bigquery/bq_annotation.sql
- config/federation/prometheus/alerts.yml
After migration to the v2 data pipeline and the retirement of the annotation-service, the `DataPipeline_(Asn|Geo)AnnotationRatioTooLowOrMissing` alerts needed to be updated for v2 data type annotations. This change adds two additional annotated data types. Since uuid-annotations are collected at measurement times, and bq processing is delayed 2days, this alert should represent a failure of the pipeline rather than a data loss. Other alerts should cover incomplete uuid-annotation data volume from the node.
This change also extends the alert threshold time from 30min to 60min to allow GKE to restart pods and for the bq-exporter to rerun queries to report metrics. Previously, the 30min threshold has caused false positives due to firing prematurely.
--- …
> Add other datatypes and set longer annotation threshold

- config/federation/grafana/dashboards/Ops_Tactical_SRE_Overview.json
The panel was no longer correctly separating physical from virtual nodes. This PR should fix the panel by selecting on virtual or physical by using the `mlab/type` node label.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/917)
> Fixes the "Cluster Versions" panel in the SRE Overview dashboard

- config/federation/grafana/dashboards/Pipeline_Overview.json
This change updates the `Pipeline: Overview` dashboard to remove the v1 and annotation service panels. In their place the dashboard now features a top level "overview" panels, expected to be the most common view, and two rows for detailed metrics from the parser and gardener.
Part of:
* https://github.com/m-lab/etl/issues/1084
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/918)
> Update Pipeline: Overview dashboard

- config/federation/grafana/dashboards/Pipeline_Overview.json
While monitoring the etl deployment in production I discovered that many panels failed to load. Root cause is suspected to be due to a deleted data source (even though no panel referenced that data source).
This change is an export from mlab-oti, with included changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/919)
> Remove legacy datasource variable

- config/federation/prometheus/alerts.yml
The alert `GardenerFailureRateTooHighOrMissing` fired in staging after a routine change merge and deployment. This coincides with the recent deployment of the pcap parser to 100%, which slows average processing rate.
`gardener_jobs_total` was absent for about 18min (16:20 to 16:38) after deployment. Because this restarts the process all previous metrics are reset to zero. The alert threshold was 10min. Now, with pcap processing, the average time between jobs is about 12.5 min/job (1440 min/day / 116 jobs/day) (though may be higher or lower).
This change splits the two alerts, preserving 10m for failure rates and increasing the absent check to 30m.
--- …
> Split GardenerFailureRateTooHighOrMissing into two alerts

- config/federation/grafana/dashboards/Ops_Tactical_SRE_Overview.json
This change adds a new panel to the Ops Tactical SRE Overview dashboard. The new panel pins a time range for the last 30days with the average daily alert rate received by the alertmanager github receiver.
This change is part of an effort to ensure that we monitor the average alerts / day and focus on keeping this rate below 1/day.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/923)
> Add average alerts last 30days

- config/federation/grafana/dashboards/K8s_SiteOverview.json
- config/federation/grafana/dashboards/K8s_WorkloadOverview.json
- config/federation/grafana/dashboards/NDT_Client_Rates.json
- config/federation/grafana/dashboards/NDT_Client_Rates_Quantiles_Heatmaps.json
This PR updates these three dashboards:
* K8s: Workload Overview
* k8s: Site Overview
* NDT: Client Rates, Quantiles over time, & Heatmaps
For the SiteOverview and ClientRates dashboards, the main difference is the addition of a new "Type" selector at the top. When you select "physical" then the "Site" selector will only contain physical sites, and when you select "virtual" it will only container virtual sites. When both are selected you get all sites.
For the WorkloadOverview dashboard there were [updates that needed to happen to the underlying recording rules](https://github.com/m-lab/k8s-support/pull/701/commits/d3f891b0fc6a4a51f2e541b474e7c7b622b3fd3b) that drive the dashboard. The queries had to change according to allowing switching on site type. This dashboard also has a new select …
> Updates several dashboards to allow switching on site type

- config/federation/grafana/dashboards/K8s_CoreOS_Overview.json
This new dashboard gives us some insight into the operation of CoreDNS on the platform.
Sandbox dashboard can be viewed here:
https://grafana.mlab-sandbox.measurementlab.net/d/X9kdIfR4z/k8s-coredns-overview?orgId=1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/926)
> Adds a new 'k8s: CoreDNS Overview' dashboard

- config/federation/prometheus/alerts.yml
Sometimes nodes experience transient issues that resolve themselves
after a while. We currently have nearly 600 production nodes, and there
is no need to fire an alert when one is down for only 1h.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/927)
> Lets a node be down for 1d before firing an alert

- config/federation/prometheus/alerts.yml
In recent weeks some alerts have fired unnecessarily due to a long bigquery-exporter query frequency and a short alert wait time. This change increases the wait time for this condition to allow the bqx time to run the query again before this alert fires. Ideally, the bqx would be updated to run on restart or config reload, rather than strictly on 3h intervals.
Example alerts misfiring:
* https://github.com/m-lab/dev-tracker/issues/725
* https://github.com/m-lab/dev-tracker/issues/726
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/928)
> Increase alert wait time to 3h for bqx frequency

- config/federation/grafana/dashboards/K8s_EtcdOverview.json
In the [k8s v1.21.0 changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md) I noted that one particular metric was changing names:
> Rename metrics etcd_object_counts to apiserver_storage_object_counts and mark it as stable. The original etcd_object_counts metrics name is marked as "Deprecated" and will be removed in the future. (https://github.com/kubernetes/kubernetes/pull/99785, [@erain](https://github.com/erain)) [SIG API Machinery, Instrumentation and Testing]
The CS in this PR seems large, but almost all of it is nothing more than Grafana updating the JSON model a good deal since when the dashboard was first created. The meaningful change is using the metric `apiserver_storage_objects` instead of the now deprecated `etcd_object_counts`.
---
This …
> Updates EtcdOverview dashboard to use the new name for a metric

- k8s/prometheus-federation/deployments/prometheus.yml
Tested by looking at the contents of the target file for `-project=mlab-ns`.
```
/aeflex-targets $ cat aeflex-locate.json
[
{
"targets": [
"35.222.117.74:9090"
],
"labels": {
"__aef_instance": "aef-locate-20220728t204839-qv9x",
"__aef_max_total_instances": "20",
"__aef_project": "mlab-ns",
"__aef_public_protocol": "tcp",
"__aef_service": "locate",
"__aef_version": "20220728t204839",
"__aef_vm_debug_enabled": "false"
}
},
{
"targets": [
"34.134.93.211:9090"
],
"labels": {
"__aef_instance": "aef-locate-20220728t204839-878j",
"__aef_max_total_instances": "20",
"__aef_project": "mlab-ns",
"__aef_public_protocol": "tcp",
"__aef_service": "locate",
"__aef_version": "20220728t204839",
"__aef_vm_debug_enabled": "false"
}
}
```
Note: The "App Engine Deployer" role will need to be added to the …
> Add a new service discovery container using -project=LOCATE_PROJECT

- config/federation/grafana/dashboards/K8s_SiteOverview.json
The dashboard has a few panels that make use of metrics from the
prometheus-federation cluster. Previously it was using a static
datasource UID, which was only valid for the prometheus-federation
cluster in mlab-sandbox. With this commit, we can properly select the
right datasource at the top and all panels should work as expected in
all projects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/932)
> Adds a new GKE Datasource variable to SiteOverview

- config/federation/grafana/dashboards/Pipeline_Overview.json
This change adds a new panel for "Gardener Errors" to the third row of the "Gardener" row.
While working on code coverage improvements, I discovered gardener has two metrics for warning and error events. This change adds a panel to report these metrics.
* gardener_warning_total
* gardener_fail_total
This may be helpful in diagnosing transient or chronic error conditions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/933)
> Add Gardener errors panel

- config/federation/grafana/dashboards/Pipeline_Overview.json
This change adds a new time series to the gardener error panel added in https://github.com/m-lab/prometheus-support/pull/933. The new time series matches the gardener jobs total error rate used in the `GardenerFailureRateTooHighOrMissing` alert.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/934)
> Add gardener_jobs_total error rate to error panel

- config/federation/grafana/dashboards/NDT_GlobalTestRate.json
This change adds a metric from the Locate v2 API to the "NDT: Global Test Rates" dashboard.
Since the Locate v2 metrics are from a second data source, this change includes a new variable definition to select project with hidden datasource variables for `$prometheusPlatform` and `$prometheusFederation`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/935)
> Add mixed data source for global test rates with locate queries

- config/federation/prometheus/alerts.yml
Due to https://github.com/m-lab/dev-tracker/issues/729 archive files are not preserved in archive-mlab-oti bucket after transfer to the archive-measurement-lab bucket any more. And, the current alert `GCSTransfers_ArchiveFilesDoNotMatchOrMissing` asserts that the same number of files are in both archive-mlab-oti and archive-measurement-lab buckets. Because the new transfer policy violates the alert constraint, it fired: https://github.com/m-lab/dev-tracker/issues/740
This change updates the alert to a simpler `GCSTransfers_ArchiveFilesMissing` daily check for the presence of archive files in the archive-measurement-lab bucket. The `increase()` function will apply to all unique combinations of datatype labels. The `and` clause additionally filters datatypes that have no data transferred …
> Update GCS transfer alert to ignore archive-mlab-oti

- k8s/prometheus-federation/deployments/oauth2-proxy.yml
- k8s/prometheus-federation/services/grafana-tls-oauth.yml
- k8s/prometheus-federation/services/prometheus-tls-oauth.yml
This change migrates the oauth2-proxy from using the google provider (with domain access control, e.g. *@measurementlab.net) to using github organization membership (e.g. users within github.com/m-lab ).
This means that members of M-Lab staff will be able to access Grafana with the same email address registered with their github account. And, this address will be the one used to assign privileges in Grafana. Because individual's github and prior Grafana emails may differ, the default permission may be `Viewer` in Grafana and will need to be updated by someone with elevated privileges.
This change requires registering a new "Oauth App" within the M-Lab github organization https://github.com/organizations/m-lab/settings/applications - We will need to create two more for the staging and …
> Use GitHub provider with oauth2-proxy for prometheus & grafana

- .travis.yml
The prometheus-support repo is one of the remaining services deployed via travis (soon to be replaced by cloudbuild in https://github.com/m-lab/prometheus-support/pull/938)
This change updates the deployment rules to trigger on `main` instead of `master`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/941)
> Deploy main branch

- IPV6_MONITORING.md
- config/cluster/prometheus/prometheus.yml.template
- config/federation/alertmanager/config.yml.template
- config/federation/prometheus/prometheus.yml.template
- k8s/data-processing/deployments/prometheus.yml
- k8s/prometheus-federation/deployments/alertmanager.yml
- k8s/prometheus-federation/deployments/blackbox.yml
- k8s/prometheus-federation/deployments/gcs-exporter.yml
- k8s/prometheus-federation/deployments/prometheus.yml
This change continues work to update github branches to use `main`. This change updates links in configuration to use the main branch where appropriate.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/942)
> Update links referencing main branch

- k8s/prometheus-federation/deployments/github-receiver.yml
Issues created by the alertmanager github receiver from prometheus alerts automatically add the 'in progress' label. However, this is confusing and we use this label as part of no other automation. This change removes this label.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/943)
> Remove "in progress" label

- k8s/prometheus-federation/deployments/mlabns-stackdriver.yml
- k8s/prometheus-federation/deployments/stackdriver.yml
This PR is meant as a temporary workaround for this issue:
https://github.com/m-lab/prometheus-support/issues/896
Once an official release of stackdriver_exporter has been made that includes a bug fix which was affecting us, then we should revert the image location to the official repository.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/944)
> Use a custom image location for stackdriver_exporter

- config/federation/prometheus/alerts.yml
The alert `MlabNS_TooManyServiceErrors` will generate a page to platform operators. However, there is currently no alert for the case when the metric that that alert relies on is missing. This PR adds a new alert to warn us when that metric is missing. This could happen, for example, when the `mlabns-stackdriver` deployment isn't working for some reason, like [a bug in the service](https://github.com/m-lab/prometheus-support/issues/896).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/946)
> Adds alert for when mlab-ns resp code metric is missing

- k8s/prometheus-federation/deployments/cadvisor.yml
- k8s/prometheus-federation/deployments/node-exporter.yml
There were already tolerations for node-exporter and cadvisor to allow
them to run on the static-outbound-ip nodes. This commits adds another
toleration to each so that they can run on prometheus pool nodes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/949)
> Adds tolerations to run on prometheus pool nodes

- config/federation/grafana/dashboards/Locate_Service.json
This PR adds two time series to keep track of the number of port checks and Kubernetes API requests performed by the Heartbeat Service. It also adds a new histogram for Kubernetes request latency.
https://grafana.mlab-sandbox.measurementlab.net/d/8O9tInk4k/locate-service?orgId=1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/950)
> Add HBS monitoring panels

- config/federation/grafana/dashboards/K8s_SiteOverviewTerse.json
- k8s/prometheus-federation/deployments/grafana.yml
https://grafana.mlab-sandbox.measurementlab.net/d/082q1knVz/k8s-site-overview-terse?orgId=1
The inspiration for this dashboard was to be able to view basic resource information about all virtual sites at one time. However, it could easily be used to compare and contract any number of virtual and/or physical sites, and view the data on the same page.
This PR also updates Grafana to v9.1.5. The motivation for the upgrade was an apparent bug in the older version for "Timeseries"-style panels using a stacked display with the Y axis set to 100%. The hover tooltip was displaying raw values with a literal `%` symbol at the end, instead of nicely formatted values. I couldn't find the particular issue or bug report, but upgrading Grafana fixed it.
- - - …
> Adds new "terse" site overview dashboard

- apply-global-prometheus.sh
- cloudbuild.yaml
Currently, the secret is deployed as part of the github-maintenance-exporter build. This commit creates the secret as part of the prometheus-support build, after which the GMX build can be nothing but running unit tests, and migrated to Cloud Build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/952)
> Create k8s Secret for GMX Github webhook

- config/federation/prometheus/prometheus.yml.template
The new label will contain the fqdn of the experiment being tested, e.g.,:
```
fqdn="ndt-mlab2-abc01.mlab-oti.measurement-lab.org"
fqdn="wehe-mlab4-lol02.mlab-staging.measurement-lab.org"
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/954)
> Adds new "fqdn" label to script-exporter metrics

- config/federation/grafana/provisioning/datasources/data-processing_mlab-oti.yml.template
- config/federation/grafana/provisioning/datasources/data-processing_mlab-sandbox.yml.template
- config/federation/grafana/provisioning/datasources/data-processing_mlab-staging.yml.template
- config/federation/grafana/provisioning/datasources/platform-cluster_mlab-oti.yml.template
- config/federation/grafana/provisioning/datasources/platform-cluster_mlab-sandbox.yml.template
- config/federation/grafana/provisioning/datasources/platform-cluster_mlab-staging.yml.template
- config/federation/grafana/provisioning/datasources/prometheus-federation_mlab-oti.yml.template
- config/federation/grafana/provisioning/datasources/prometheus-federation_mlab-sandbox.yml.template
- config/federation/grafana/provisioning/datasources/prometheus-federation_mlab-staging.yml.template
This change specifies the scrape interval for prometheus data sources so that we can take advantage of https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/957)
> Specify the prometheus scrape interval

- config/federation/grafana/dashboards/Prometheus_SelfMonitoring.json
Since prometheus appears to garbage collect its storage every week, the existing "Filesystem Available Estimate" panel includes unrealistic and confusing jumps during these garbage collection events.
This change updates the time range for the linear prediction to include 10d, to smooth out the large discontinuity. The result is that the prediction should be smoother and more representative of a real prediction.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/956)
> Smoother predictions for disk utilization

- config/federation/grafana/dashboards/GCP_Billing.json
https://grafana.mlab-sandbox.measurementlab.net/d/a5mC51ZMk/gcp-billing
This PR takes the "GCP Billing" dashboard that @stephen-soltesz created with the following changes
* moves it from the "soltesz" folder to the "General" folder
* cleans it up (to my personal tastes)
* resizes numerous panels
* removes legend from some panels
* changes hover tip to show "All" and sort desc
* Sets data type to "Currency: US Dollars"
* removes "stacked" graph display from most panels
* renames panels slightly
* removes any comments from BigQuery queries
* reduces default range from 14d to 7d
* various other tweaks I can't think of now
* adds a new panel for estimated GCE egress traffic costs per day
- - - …
> Promotes "GCP Billing" dashboard to GA, with some modifications

- config/federation/grafana/dashboards/K8s_SiteOverview.json
- config/federation/grafana/dashboards/K8s_SiteOverviewTerse.json
https://grafana.mlab-sandbox.measurementlab.net/d/rJ7z2Suik/k8s-site-overview?orgId=1
This commit started as nothing more than looking into fixing the "Memory" panel, which was showing something fairly off of what `top` on the machine was showing. This was fixed, but while in the dashboard I realized that a few other things were broken or needed updating:
* The "pod" select box had no values. Fixed.
* I migrated all legacy "Graph (old)" panels to the new "Timeseries" type.
* Limited the "Pod CPU Usage" panel to only display timeseries where the value is greater than 1%.
* Set hover tip on various panels to sort descending.
* Updatesj "go routine counts" panel to have hover tip display "<container> (<pod>)" instead of "<deployment> <container>".
* Removes "- RSS" from "Go RSS" panel hover …
> Fixes and improvements to SiteOverview dashboard

- config/federation/grafana/dashboards/Ops_Tactical_SRE_Overview.json
For some metrics, the "machine" label value ends up being "prometheus-platform-cluster", which represents the machine where the exporter is running, and not the actual machine represented by the metric value. In this case, the "node" label should more reliably give us the value we are looking for.
The impetus for this PR came from the Ops Tactical meeting this morning where the SRE Overview dashboard was showing that the "prometheus-platform-cluster" node was in lame-duck mode, which doesn't make sense, and I had no recollection of having added a lame-duck taint to that node. Upon closer inspection, it turns out the lame-duck was actually for mlab1-tlv01, but for the above reason was display the Prom node. This PR should prevent that from happening again.
- - - …
> Changes table display value from "machine" to "node"

- config/federation/grafana/dashboards/Locate_Service.json
https://grafana.mlab-sandbox.measurementlab.net/d/8O9tInk4k/locate-service
This PR adds 3 new panels to the dashboard. One for /health checks (Health Checks) and two for Prometheus health collections (Prometheus Health Collections and Prometheus Health Collection Request Time). 
It also moves the "Health" row to the top.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/959)
> Add Prometheus and health panels to Locate dashboard

- config/federation/bigquery/bq_annotation.sql
This change is an update in response to the ["unsafe UUIDs" incident][1] 2022-11-30. Between 2022-11-08 and 2022-11-30 the NDT server was started without the `-uuid-prefix-file` flag which resulted in UUIDs with the "unsafe" string while other sidecar data (e.g. annotation) used the correct UUID. This mismatch results in the two datatypes failing to join.
The `bq_annotation.sql` query and corresponding [alert][2] should have discovered this case but failed due to the exclusion of all rows with "null" annotations, which caused the "total" count to only match the rows with non-null annotations (which defeats the purpose of this metric).
This change corrects the queries to count the true "total" rows so that the alert denominator is correct.
[1]: …
> Use LEFT JOIN to include NULL values

- config/federation/prometheus/alerts.yml
This change lowers the threshold for successful network annotations based on observation of actual annotation success rates. The lower threshold in practice was previously missed due to https://github.com/m-lab/prometheus-support/pull/961
This change will prevent alerts firing for expected conditions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/962)
> Lower alert threshold for network annotations

- config/federation/grafana/provisioning/datasources/prometheus-federation_mlab-oti.yml.template
- config/federation/grafana/provisioning/datasources/prometheus-federation_mlab-sandbox.yml.template
- config/federation/grafana/provisioning/datasources/prometheus-federation_mlab-staging.yml.template
Add a 60s timeout for requests to Prometheus datasources.
Not sure what the default was, but it was causing one of the mlab-ns queries in the Locate Service dashboard to time out with this message:
[Example](https://grafana.mlab-oti.measurementlab.net/d/8O9tInk4k/locate-service?orgId=1&refresh=5m) of the above.
Data source documentation can be found [here](https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources).
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/964)
> Increase Prometheus request timeout

- k8s/prometheus-federation/deployments/stackdriver.yml
For some reason, with metrics-interval=1m, stackdriver_exporter was not ingesting any metrics for container logs. The default for this flag is 5m, and removing the flag resolved the issue of alerts firing in staging about container logs missing in Stackdriver for a bunch of nodes.
This behavior of stackdriver_exporter has apparently impacted others. And based on what some have said in [one particular issue](https://github.com/prometheus-community/stackdriver_exporter/issues/26#issuecomment-407110782), setting the flag to a higher value shouldn't impact the results:
> You should be able to set the interval to something like 6 hours and it won't break the other services because it only uses the latest metrics, so you'll just be pulling more data than necessary but it shouldn't break the …
> Removes the flag --monitoring.metrics-interval

- k8s/prometheus-federation/deployments/github-receiver.yml
This change updates the alertmanager-github-receiver to the latest version, the last update was from June 2020.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/966)
> Update build of alertmanager-github-receiver

- config/federation/prometheus/alerts.yml
When a node is lame-ducked, Vector might not even be scheduled on that node, and no logs with show up in Stackdriver. Don't fire the alert for missing logs in Stackdriver when a node is lame-ducked.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/967)
> Suppresses Stackdriver log alert when node is lame-ducked

- config/federation/prometheus/alerts.yml
This PR adds a new alert for the rate of Locate V2 request errors.
A description for the alert has also been added under https://github.com/m-lab/ops-tracker/wiki/Alerts-&-Troubleshooting#locate_toomanyerrors.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/968)
> Add an alert for Locate V2 request errors

- config/federation/script-exporter/script_exporter.yml
This PR implements a workaround for the script-exporter pods' memory exhaustion issue we have noticed in staging. It's possible for the wehe-cmdline client to take > 1 minute to fully complete a test now.
This changes the script to a much simpler `curl`, which will have exit code zero when the server is reachable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/969)
> Replace wehe client with curl in script-exporter config

- config/federation/script-exporter/script_exporter.yml
This required `wehe-` to work as intended.
https://prometheus.mlab-sandbox.measurementlab.net/graph?g0.expr=script_success%7Bservice%3D%22wehe_client%22%7D%20%3D%3D%201&g0.tab=1&g0.stacked=0&g0.show_exemplars=0&g0.range_input=1h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/970)
> Fix wehe URL in script-monitoring config

- config/federation/script-exporter/script_exporter.yml
After the v0.2.6 update to wehe that reduced the traceroute timeouts, the script-exporter RAM usage appears back to workable levels.
This change reverts the script exporter configuration change to continue running the e2e test, to match configurations in production.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/971)
> Revert wehe e2e test

- config/federation/grafana/dashboards/Ops_Tactical_SRE_Overview.json
- config/federation/prometheus/alerts.yml
This new alert and dashboard panel are based on a new [log-based metric in each project](https://console.cloud.google.com/logs/metrics?project=mlab-sandbox), named "platform_cluster_oom". The Logging query for the log-based metric is:
```
resource.type="generic_node"
resource.labels.location="<project>"
jsonPayload.message:"Out of memory"
```
Log-based metrics are 1m samples that reflect the delta from the previous sample. For this reason, the new resources do not do any sort of aggregation or rate calculations, but instead just use the raw values returned by the metric (`stackdriver_generic_node_logging_googleapis_com_user_platform_cluster_oom`).
The alert is very sensitive, as OOM events shouldn't really every happen.
The new "OOM Events" panel on the SREOverview dashboard replaces the …
> Adds OOM alerts and new OOM panel on SRE Overview dashboard

- k8s/prometheus-federation/deployments/kubeip.yml
We had a disk pressure issue on the static-public-ip nodes, which caused script-exporter to be evicted. It is not possible to resize the disks of an existing node pool. The only way to achieve this is to create a new node pool with the desired configurations and then migrate your workloads to this new node pool. I created a new node pool in mlab-oti named static-external-ip and migrated the workloads to this new node pool. This change configures kube-ip to be sure that those nodes get static IPv4 addresses. Meanwhile I have manually updated the kube-ip deployment in production with the change in this commit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/973)
> Updates name of node pool for kube-ip

- k8s/prometheus-federation/deployments/script-exporter.yml
Debug logging is only useful when you are debugging, and we are not debugging script-exporter. Furthermore, the log is appended to on every test, and eventually the logs get big and fill up the root filesystem.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/974)
> Turn off debug logging for script-exporter

- k8s/prometheus-federation/deployments/script-exporter.yml
This change updates the version of script exporter to include fixes in the script-exporter container. This change restores the `LOGX_DEBUG` variable explicitly setting it to "false".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/975)
> Update script exporter

- config/federation/grafana/dashboards/Locate_Service.json
This PR adds a stacked area chart and a histogram showing the distribution of server selection ranking under the Rollout section.
https://grafana.mlab-sandbox.measurementlab.net/d/8O9tInk4k/locate-service?orgId=1&refresh=5m
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/976)
> Add visualizations for ranked server selection

- cloudbuild.yaml
Also, make Go and Prometheus versions env variables in the build step so that they aren't hard-coded in the script.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/977)
> Updates Go to 1.20.2 in Cloud Build config

- config/federation/bigquery/bq_daily_archive.sql.template
- config/federation/bigquery/bq_gardener.sql.template
- config/federation/bigquery/bq_gardener_historical.sql.template
- config/federation/bigquery/bq_gardener_parse_time.sql.template
This change modifies queries to use annotation2 and hopannotation2 datatypes in preparation for processing reannotated or renamed annotation archive types. Once the data pipeline is processing these datatypes, there should be no functional changes.
This change is part of the [Correcting Network Annotations](https://docs.google.com/document/d/1Aro-2G0pGBNfR5sweUcioraik3PXdZRwphwcZzkovB0/edit) design.
This change is part of steps to repair:
* https://github.com/m-lab/data-annotations/issues/34
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/978)
> Rename annotation tables

- config/federation/grafana/dashboards/Archive_Repacker_Annotations.json
This change adds a basic "Archive Repacker (Annotation)" dashboard for monitoring the progress and success of the reannotator and renamer jobs.
The sandbox deployment is visible: https://grafana.mlab-sandbox.measurementlab.net/d/m4-GH51Vx/archive-repacker-annotations?orgId=1&var-datasource=Data%20Processing%20%28mlab-sandbox%29
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/979)
> Add basic annotation repacker dashboard

- config/federation/grafana/dashboards/Pipeline_Overview.json
This change updates the `Pipeline: Overview` dashboard to include references to the experiment name with the datatype name where available. (Many metrics do not have the experiment label available https://github.com/m-lab/etl-gardener/issues/422 )
This change is part of changes to introduce data from wehe into the pipeline.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/980)
> Use experiment/dataset where available

- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
This PR adds 3 new alerts to monitor the autoloader.
I have also updated the ops-tactical [wiki](https://github.com/m-lab/ops-tracker/wiki/Alerts-&-Troubleshooting#pipeline_autoloaderdownormissing) with troubleshooting information.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/983)
> Add alerts for the autoloader

- config/federation/grafana/dashboards/NDT_Metro_Performance_Distributions.json
- config/federation/grafana/dashboards/NDT_Site_Performance_Distributions.json
The [Plotly Grafana panel type](https://grafana.com/grafana/plugins/ae3e-plotly-panel/) supports any visualization supported by the Plotly javascript library. The combination of the BigQuery datasource with the Plotly panel type means that we could support visualizations directly from BigQuery using any javascript Plotly library.
This change adds two new dashboards using this combination to visualize PDFs (or CDFs) of NDT7 download (and upload) performance metrics.
* [NDT: Metro Performance Distributions](https://grafana.mlab-sandbox.measurementlab.net/d/ZCG2vk8Vk/ndt-metro-performance-distributions?from=now-14d&to=now)
* [NDT: Site Performance Distributions](https://grafana.mlab-sandbox.measurementlab.net/d/ZeMq_Ya4k/ndt-site-performance-distributions?orgId=1)
- - - …
> Add Plotly dashboards for NDT performance distributions using BigQuery datasource

- config/federation/grafana/dashboards/NDT_Metro_Performance_Distributions.json
- config/federation/grafana/dashboards/NDT_Site_Performance_Distributions.json
This change adds a hidden `${prometheus}` datasource variable so the `site` and `metro` variable lookup can refer to a local instance of the prometheus datasource, which varies per project.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/985)
> Add prometheus variable

- config/federation/grafana/dashboards/GCP_Billing.json
This change updates the set of `project` variable values from a static list to the result of a dynamic BigQuery query.
The static list was missing a partnership project. So, a dynamic query ensures that all known GCP projects are available for selection.
```
SELECT project.id
FROM `mlab-oti.billing.unified`
WHERE project.id IS NOT NULL
GROUP BY project.id
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/987)
> Discover projects with BQ query

- config/federation/grafana/dashboards/GCP_Billing.json
This change fixes a missed variable rename. The variable query to identify GCP projects uses a named BQ datasource, but it was renamed to `$bqSource` in https://github.com/m-lab/prometheus-support/pull/988 -- panels that reference a datasource variable are updated automatically if the variable is renamed, but evidently references in variable definitions are not.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/989)
> Update variable reference to ${bqSource}

- config/federation/grafana/dashboards/Locate_Service.json
This PR adds a new "Memorystore" row containing histograms showing the duration of requests from the Locate to Memorystore.
- [PUT requests](https://grafana.mlab-sandbox.measurementlab.net/d/8O9tInk4k/locate-service?orgId=1&refresh=5m&var-datasource=Prometheus%20%28mlab-sandbox%29&var-platformdatasource=Platform%20Cluster%20%28mlab-sandbox%29&var-bigquerydatasource=BigQuery%20%28mlab-sandbox%29&var-experiment=ndt&var-metro=All&viewPanel=48)
- [GET requests](https://grafana.mlab-sandbox.measurementlab.net/d/8O9tInk4k/locate-service?orgId=1&refresh=5m&var-datasource=Prometheus%20%28mlab-sandbox%29&var-platformdatasource=Platform%20Cluster%20%28mlab-sandbox%29&var-bigquerydatasource=BigQuery%20%28mlab-sandbox%29&var-experiment=ndt&var-metro=All&viewPanel=49)
Happy to go over these over GVC …
> Add new panels to show Memorystore request duration

- config/federation/alertmanager/config.yml.template
The alert messages in slack are meant to contain two distinct URLs.
* a link to the wiki alert description (working)
* a link to the alert definition with an edit link (broken)
Due to the template syntax using `{{ end  -}}`, all whitespace between the end of the wiki link and the start of the edit link was removed, making them appear to be a single URL, which was incorrect. This change removes the syntax that removes all whitespace, which preserves two separate links.
Correct behavior verified in the #alert-sandbox messages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/993)
> Fix format for edit link

- k8s/prometheus-federation/deployments/bigquery-exporter-3h.yml
- k8s/prometheus-federation/deployments/bigquery-exporter-5m.yml
This change corrects a configuration error that used the same pod spec labels and selectors for two distinct configurations: bigquery-exporter-3h and bigquery-exporter-5m. This configuration error merges the logs from both deployments in GCP cloud console - making diagnostics harder.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/995)
> Add distinct pod labels for 3h and 5m configs

- config/federation/prometheus/alerts.yml
This change adds a new alert for missing metrics needed to calculate the discard rate per machine / site.
A recent configuration error went undetected for about six weeks. The root cause was another query in the bigquery exporter failing to run due to an underlying schema change.
This implies multiple flaws in the bigquery exporter:
* does not run subsequent queries if one fails -- I didn't think this was possible, but this seems to be.
* the bqx does not export summary metrics to generalize alerts on bqx errors or diagnose issues via a dashboard.
* the bqx does not export summary metrics to see / diagnose especially poor performing queries.
- - - …
> Add new alert for missing metrics

- config/federation/grafana/provisioning/datasources/grafana_bigquery_mlab-oti.yml.template
- config/federation/grafana/provisioning/datasources/grafana_bigquery_mlab-sandbox.yml.template
- config/federation/grafana/provisioning/datasources/grafana_bigquery_mlab-staging.yml.template
- k8s/prometheus-federation/deployments/grafana.yml
The `doitintl-bigquery-datasource` plugin [was deprecated](https://github.com/doitintl/bigquery-grafana) in Dec 2022. This PR installs the official Grafana BigQuery plugin and sets up datasources for every project. 
A subsequent PR will migrate the dashboards that are currently using the doitintl plugin to this new one.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/999)
> Move from doitintl BigQuery plugin to the Grafana official one

- config/federation/grafana/dashboards/Locate_Service.json
This PR migrates the Locate Service monitoring dashboard to the new BQ datasource plugin (#999). It's important to note that the `$__timeFilter(date)` previously used in the query does not work with grafana-bigquery-datasource if `date` is of type `DATE`. In such cases, it must be replaced by an equivalent filter using the `$__from` and `$__to` macros (returning the timestamp as milliseconds). For example:
```WHERE date BETWEEN EXTRACT(date FROM TIMESTAMP_MILLIS($__from)) AND EXTRACT(date FROM TIMESTAMP_MILLIS($__to))```
This PR may also serve as an example of how to migrate other dashboards in the future.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1001)
> Update Locate Service dashboard to use the new BQ datasource plugin

- config/federation/prometheus/alerts.yml
We recently stopped pushing experiment logs to GCP:
https://github.com/m-lab/k8s-support/pull/849
Vector should still be pushing logs from some containers like node-exporter, cAdvisor, flannel, etc. However, it would appear that these container produce very few logs and trigger this alert.
Vector is also still pushing kernel logs over above a certain level. Again, it seems that a good chunk of machines do not push kernel logs frequently enough to make a reliable alert.
All this said, we have observed that Vector sometimes gets into an error state with regard to GCP, which has previously only been visible because of the alert being removed by this commit. We need to figure out a way to alert when Vector cannot push logs to Stackdriver, but does not exit or produce anything but a log …
> Removes ContainerLogsMissingInStackdriver alert

- config/federation/prometheus/alerts.yml
This PR adds a new alert for 2% of /nearest requests taking longer than 1 second.
Part of https://github.com/m-lab/locate/issues/149
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1015)
> Add alert for Locate request latency

- config/federation/grafana/dashboards/Revtr_Sidecar_Monitoring.json
This PR adds [a dashboard](https://grafana.mlab-sandbox.measurementlab.net/d/e4l4LjWIk/revtr-sidecar-monitoring?orgId=1) to monitor the revtr-sidecar deployment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1017)
> Add revtr-sidecar monitoring dashboard

- config/federation/prometheus/alerts.yml
The GardenerHistoricalThroughputIsStalled alert fired on Aug 15 2023 and again Nov 12 before clearing automatically both times. These dates correspond to times when historical processing reset to the start of the historical data in 2016. However, historical processing resets occur monthly (as of today), but the alert does not fire every time.
After a historical reset, there is no ndt7 data between 2016-2020. It takes the pipeline about 1.3days until the data prior to 2020 (when ndt7 is introduced again) is fully processed. The issue with the alert appears to be once ndt7 begins being processed again (`increase(gardener_jobs_total{status="success", daily="false"}[1d]) > 0`) but `bq_gardener_historical_throughput` is still zero. This metric comes from the 3h bigquery exporter, so may be …
> Wait longer before firing GardenerHistoricalThroughputIsStalled alert

- config/federation/grafana/dashboards/Alert_DownloaderIsFailingToUpdate.json
- config/federation/grafana/dashboards/GCP_Billing.json
- config/federation/grafana/dashboards/K8s_SiteOverviewTerse.json
- config/federation/grafana/dashboards/NDT_CanaryValidation.json
- config/federation/grafana/dashboards/NDT_EarlyExit.json
- config/federation/grafana/dashboards/NDT_Metro_Performance_Distributions.json
- config/federation/grafana/dashboards/NDT_Site_Performance_Distributions.json
- k8s/prometheus-federation/deployments/grafana.yml
For the most part, the only dashboards that were broken were ones relying on the doitintl BigQuery plugin and/or the ae3e Plotly Panel plugin. There were a few other small breakages that I took care of too.
NOTE: I _only_ modified/fixed provisioned dashboards. Any adhoc dashboards in sandbox that people have created and use regularly may still be broken. The most common fixes are:
* Modify any datasource variable to use the newer Google BigQuery plugin from Grafana.
* For BigQuery panels, make sure that "Format" for each query panel has an appropriate value (e.g., Table, Time Series).
* In the "Script" section of Plotly Panel configurations remove the `.buffered` field from data sources, since it no longer exists.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …
> Upgrade to Grafana v10.2.2 & fix broken dashboards due to upgrade

- config/federation/grafana/dashboards/K8s_EtcdOverview.json
- config/federation/grafana/dashboards/K8s_MasterCluster.json
These dashboard were still referencing the old API nodes names which included the string "master". That naming was replaced by "api" some time ago, but there dashboards were never updated.
https://grafana.mlab-sandbox.measurementlab.net/d/milv1PgZz/k8s3a-etcd-overview?orgId=1
https://grafana.mlab-sandbox.measurementlab.net/d/K8-zAIuik/k8s3a-api-cluster?orgId=1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1020)
> Fixes API and etcd node dashboards

- config/federation/grafana/dashboards/NDT_EarlyExit.json
This PR adds 2 new panels showing the weekly test count and data volume for IST tests.
- [Test count](https://grafana.mlab-sandbox.measurementlab.net/d/W8JPPzzIz/ndt3a-early-exit?orgId=1&viewPanel=15).
- [Data volume](https://grafana.mlab-sandbox.measurementlab.net/d/W8JPPzzIz/ndt3a-early-exit?orgId=1&viewPanel=16).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1021)
> Add new panels showing weekly test count and data volume

- config/federation/prometheus/alerts.yml
For what seems like years, the `GardenerFailureRateTooHighOrMissing` will fire periodically and then clear. https://github.com/m-lab/dev-tracker/issues/744 This occurs regularly with the historical reprocessing. This change modifies the alert threshold to greater than 3 failures for more than 24h.
The primary observation is that the total number of failed jobs (not the rate) that trigger this alert is rarely above 3. While any failure is cause for concern (the data has not changed, so it's either random or static failure), until we can investigate the root cause and distinguish between failures that are due to some random event or the same file every time, we can prevent the alert from firing for less critical conditions.
I was surprised to see that the failures occur before the …
> Update limit for GardenerFailureRateTooHighOrMissing to prevent false alarms

- config/federation/grafana/dashboards/GCP_Billing.json
The GCE network egress dashboard panel stopped showing data after 2023-12-15. Looking more closely this is because the SKU for network egress (used to filter results) has changed names. This change adds both terms to the query.
Patterns previously matching:
* 'Network Internet Egress %'
Are now matched using:
* 'Network Internet Data Transfer Out %'
Historical data remains unchanged, so both expressions are needed in the query.
https://grafana.mlab-sandbox.measurementlab.net/d/a5mC51ZMk/gcp-billing?orgId=1&refresh=5m&viewPanel=31
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1024)
> fix(dashboard): Include new name for GCE egress in query

- config/federation/grafana/dashboards/BigQuery_NDT7_Metrics.json
This change adds a dashboard to our set of supported dashboards so that two often referenced panels are always available.
The most important panels are:
* percentage of tests targeting virtual servers
* counts of tests by client_name -  showing relative distribution and scale of various client integrations
* counts of daily tests by country and gcp region
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1026)
> Add ndt7 metrics dashboard

- README.md
- config/federation/grafana/dashboards/MLABNS_6_HourClients.json
- config/federation/grafana/dashboards/MLABNS_PrometheusQueries.json
- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
- generate-prometheus-targets.sh
We haven't used experiment names or DNS names of "ndt.iupui" or "ndt-iupui" or "neubot.mlab" or "neubot-mlab" in a very long time. And, recently we even removed the experiments of those names from experiments.jsonnet in site. This PR remove all references to those old names  and replaces them, where appropriate, with just "ndt' and "neubot".
One of the primary changes in this PR is to remove "iupui" and "mlab" from the `--select` flag of mlabconfig.py, such that it generates blackbox_exporter and script_exporter targets with the proper names, which should clear a staging MlabNS_NdtMetricsMissing alert we got for missing metrics.
Though they aren't used any longer, and are probably broken in several ways, I also went ahead and removed references to those old experiment names from a couple …
> Eliminates all usage of "ndt.iupui" and "neubot.mlab"

- config/federation/prometheus/alerts.yml
This PR adds the `severity: page` label to the `Locate_TooManyErrors` alert following the discussion at the team meeting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1030)
> Make Locate_TooManyErrors a pageable alert

- config/federation/grafana/dashboards/Cloud_Storage_Usage.json
This PR adds a new [dashboard](https://grafana.mlab-sandbox.measurementlab.net/d/d8145875-e912-484e-b8f2-b77f63bd28a3/cloud-storage-usage?orgId=1) to track Cloud Storage usage.
Happy to talk through it if it's helpful :).
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1031)
> Add Cloud Storage Usage dashboard

- k8s/prometheus-federation/deployments/gmx.yml
This brings in the new feature of periodically pruning retired sites from maintenance.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1032)
> Updates GMX to v1.5.0

- config/federation/grafana/dashboards/Cloud_Storage_Usage.json
This PR adds a new Cost / Hour [panel ](https://grafana.mlab-sandbox.measurementlab.net/d/d8145875-e912-484e-b8f2-b77f63bd28a3/cloud-storage-usage?orgId=1&viewPanel=5)to the Cloud Storage Usage dashboard.
Notably, yesterday, there was an increase in Coldline Class A operation costs in staging (`mlab-oti.billing.unified` joins staging and production data). The cost increase happened because of the addition of the Lifecycle Management Rule to move data older than 12 months in archive-mlab-staging to Coldline storage ([tracking](https://github.com/m-lab/dev-tracker/issues/783)).
The staging cost to move ~130M objects was $4,631.
There are 530M objects in archive-measurement-lab for which the same rule will be applied when it's added, meaning we can expect the move costs in measurement-lab to …
> Add storage cost panel

- config/federation/prometheus/alerts.yml
The downloader used to download databases about every 8h. We have reconfigured it to only download about every 24h. Additionally, there is no need for this alert to be super sensitive. It is okay if annotations happen with databases that are only a couple days old. However, if downloader can't download all the files for more than 3d, then fire an alert.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1035)
> Changes downloader alert to fire after 72h, not 21h

- config/federation/grafana/dashboards/BigQuery_Usage.json
This PR adds a new [BigQuery Usage](https://grafana.mlab-sandbox.measurementlab.net/d/f4efc343-661f-4899-a00f-a4ffeb294e5d/bigquery-usage?orgId=1) dashboard to version control. The sandbox version is being used for analyses.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1036)
> Add BigQuery Usage dashboard to main version control

- config/federation/bigquery/bq_billing.sql
- config/federation/prometheus/alerts.yml
This PR adds metrics and an alert to monitor BigQuery usage cost increases (2x the monthly average).
Similar work was done to monitor GCS costs (https://github.com/m-lab/prometheus-support/pull/1033).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1037)
> Add BigQuery billing metrics and alert

- config/federation/grafana/dashboards/GCP_Billing.json
This PR adds a legend with mean costs per service to the "Cost per service (per day) (measurement-lab)" [panel](https://grafana.mlab-sandbox.measurementlab.net/d/a5mC51ZMk/gcp-billing?orgId=1&refresh=5m&from=now-8d&to=now-1d&viewPanel=11) in the GCP Billing dashboard.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1038)
> Add legend to GCP Billing 'Cost per service' panel

- k8s/prometheus-federation/deployments/prometheus.yml
v2.31.1 was released in late 2021! I gave a quick look over the changeslogs for each minor version update, and I didn't see anything that would obviously affect our deployment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1041)
> Updates Prometheus version from v2.31.1 to v2.51.2

- config/federation/grafana/dashboards/Packet_Testing.json
This PR adds a new [dashboard](https://grafana.mlab-sandbox.measurementlab.net/d/d341c044-4e2c-4904-b05f-98e8bf1bbf32/packet-testing?orgId=1) to visualize packet testing results. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1042)
> Add initial dashboard to visualize packet testing results

- config/federation/prometheus/alerts.yml
This PR modifies the `Locate_TooManyErrors` to have an error threshold of 0.5%. The previous threshold (0.1%) was too sensitive.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1043)
> Modify Locate_TooManyErrors threshold

- config/federation/grafana/dashboards/Packet_Testing.json
This PR adds a new [panel](https://grafana.mlab-sandbox.measurementlab.net/d/d341c044-4e2c-4904-b05f-98e8bf1bbf32/packet-testing?orgId=1&viewPanel=11) to the Packet Test dashboard with PDFs for performance distribution comparisons of the full test vs. shorter versions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1044)
> Add panel to Packet Test dashboard with PDFs for performance distribution comparisons

- config/federation/prometheus/alerts.yml
This PR reduces the sensitivity of the `ParserFailureRateTooHighOrMissing` alert. The alert recently [fired](https://prometheus.mlab-oti.measurementlab.net/graph?g0.expr=(sum(rate(etl_task_total%7Bstatus!%3D%22OK%22%2C%20cluster%3D%22data-pipeline%22%7D%5B1h%5D))%20by%20(table)%20%2F%0A%20%20%20%20%20%20sum(rate(etl_task_total%7Bcluster%3D%22data-pipeline%22%7D%5B1h%5D))%20by%20(table))%20%3E%200.01%0A%20%20%20%20%20%20OR%20absent(etl_task_total%7Bcluster%3D%22data-pipeline%22%7D)&g0.tab=0&g0.display_mode=lines&g0.show_exemplars=0&g0.range_input=12h) because of an ephemeral event that lasted ~20 mins (could be caused because of a pod restart).
- - - …
> Reduce sensitivity of Parser alert

- config/federation/bigquery/bq_sidecar.sql
- config/federation/prometheus/alerts.yml
- k8s/prometheus-federation/deployments/bigquery-exporter-24h.yml
- k8s/prometheus-federation/deployments/bigquery-exporter-3h.yml
On 2024-07-22, [we discovered](https://docs.google.com/document/d/1PBht5HR3fu4-vyjavEiwJVrsLEJvtA713vZwY91Dt2A/edit) that MIG deployments were failing to start scamper1 traces from traceroute-caller due to the unknown MIG IP address. We did not detect this because we have no monitoring tracking whether sidecar data is collected for a primary measurement service. By adding monitoring, this type of error will not go unnoticed again. And this creates a framework for adding additional sidecar types if desired.
See: https://prometheus.mlab-sandbox.measurementlab.net/graph?g0.expr=bq_sidecar_scamper1_matching%20%2F%20bq_sidecar_ndt_total%20%3C%200.90&g0.tab=1&g0.display_mode=lines&g0.show_exemplars=0&g0.range_input=1h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …
> Add bqx query and alert for missing NDT/scamper1 data

- config/federation/grafana/dashboards/K8s_SiteOverview.json
- config/federation/grafana/dashboards/K8s_Topk_Machine_Pod_Resources.json
Related to https://github.com/m-lab/k8s-support/pull/900
I have never really used the process count panel of the Site Overview dashboard, and I believe that the "K8s: Topk Machine & Pod Resources" dashboard is very old and unused. In any case, removing these the process count panel from these dashboards doesn't really change the base intent of either.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1051)
> Removes process count panels from two dashboards

- config/federation/grafana/dashboards/Pipeline_SLIs.json
This PR updates the default data source in the ["Pipeline: SLIs"](https://grafana.mlab-sandbox.measurementlab.net/d/q4MrNzh7k/pipeline3a-slis?orgId=1) dashboard to be mlab-oti. I was investigating an alert earlier and ended up accidentally looking at sandbox data, when the majority of the time these dashboards are looked at is for production insights.
The time range is also updated from `now-2d` to `now-7d` to get a wider perspective.
The number of changes looks a little more significant only because the dashboard hasn't been updated in a long time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1054)
> Set mlab-oti as the default for the Pipeline dashboard

- config/federation/grafana/dashboards/Packet_Testing.json
This PR adds a PDF visualization of the throughput distribution of BBR-terminated tests compared to full-length ndt7 tests.
[Panel](https://grafana.mlab-sandbox.measurementlab.net/d/d341c044-4e2c-4904-b05f-98e8bf1bbf32/packet-testing?orgId=1&viewPanel=11).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1055)
> Add visualization of BBR-terminated test trials

- config/federation/grafana/dashboards/Wehe_access_envelope.json
- config/federation/script-exporter/script_exporter.yml
This PR removes ndt5 testing from our script_exporter deployment. We decided that:
* An ndt5 e2e test is not representative of the platform today, since the overwhelming majority of tests are now ndt7.
* ndt-server is mature and stable enough to not require continuous e2e testing.
However, Wehe testing remains. This PR also adds a new "E2E Success Rate" panel to the "Wehe Access Envelope" dashboard. The dashboard is probably not a 100% fit for this new panel, since the e2e success rate isn't necessarily related to the access envelope, but it's the only sensible place I could find to put a panel having solely to do with Wehe.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/promethe …
> Removes ndt5 e2e testing from script_exporter

- config/federation/grafana/provisioning/datasources/autojoin_mlab-autojoin.yml.template
- config/federation/grafana/provisioning/datasources/autojoin_mlab-sandbox.yml.template
- config/federation/grafana/provisioning/datasources/autojoin_mlab-staging.yml.template
This change adds new datasources for the Autojoin cluster instance of Prometheus. These datasources will make it possible to create dashboards with metrics collected directly from the Autojoin platform.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1058)
> Add datasources for autojoin cluster

- config/federation/grafana/dashboards/Packet_Testing.json
This PR adds a [panel](https://grafana.mlab-sandbox.measurementlab.net/d/d341c044-4e2c-4904-b05f-98e8bf1bbf32/packet-testing?orgId=1&viewPanel=16) to display the throughput distribution using the snapshot after the BBR pipe full signal. The "cumulative" line shows the throughput from the beginning of the test until the selected snapshot. The "current" line shows the throughput from the snapshot right before (pipe full signal) until the selected snapshot.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1061)
> Plot distributions of throughput using snapshot after first BBR pipe full signal

- config/federation/bigquery/bq_billing.sql
We want to start alerting on Compute Engines costs, and this is the first step by getting metrics about Compute Engine costs into Prometheus.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1062)
> Adds Compute Engine costs to the bq_billing query results

- config/federation/prometheus/alerts.yml
As an example, the current daily average for the past 30 days is $11,318. On October 9th, due to the Exactly Labs bug, the Compute Engine costs were $16,965. Using >50% as the threshold would have _just_ caught the Exactly Labs bug (11318 * 1.5 = 16977). Lowering the threshold to >25% would have triggered a false alarm on a few occasions over the past month due to normal variation in Compute Engine costs. We could probably get away with maybe a >40% threshold, but >50% seemed like a nice round number and will catch the more serious increases after a couple days.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1063)
> Adds an alert for when GCE costs are >50% of montly average

- config/federation/script-exporter/script_exporter.yml
- k8s/prometheus-federation/deployments/script-exporter.yml
This resolves an issue where the version of java the Wehe client is build with is different and incompatible with the version of java installed in the container image.
This PR also increases the script-exporter timeout for the Wehe client from 50s to 55s. For some reason almost all Wehe e2e tests in sandbox are taking >50s, while in production almost all of them complete in 15 or 20s. There are still some timeouts, even at 55s, but most of them seem to be completing, which is better than where we are today. Meanwhile, I have a question about this out to Derek Ng in the #mlab-wehe-shared Slack channel.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1065)
> Updates script-exporter container image version to v0.2.12

- config/federation/script-exporter/script_exporter.yml
Changes wehe e2e test from using applemusic to amazon I noticed that many e2e tests in sandbox were timing out at 50s from the timeout setting configured for the wehe_client script. But in production the tests were completing in around 10 or 15 seconds.
I turned on debug logging for wehe-cmdline.jar and noticed that for some odd reason there was a 20s delay when sending packet number 13 our of 15. And this happens twice during the test, making the test very long.
Looking at the wehe-cmdline repository, I noticed that a new version was released just a couple months ago which updated all the replay files. Inspecting the applemusic replay file (which is JSON), I noticed that the timestamp field of the 13th packet in the array has a value of ~20s, which I think explain why there is always a …
> Change wehe e2e tests to use the amazon replay instead of applemusic

- config/federation/grafana/provisioning/datasources/grafana_bigquery_mlab-collaboration.yml.template
This change adds a new datasource for mlab-collaboration. While the Grafana instance runs in mlab-sandbox, it is helpful to localize all billing for mlab-collaboration to that project by allowing queries to be run in this project also.
This is in service of estimating total costs for https://github.com/m-lab/hermes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1067)
> Add new datasource for mlab-collaboration

- config/federation/grafana/dashboards/Autojoin.json
This change adds a new dashboard for viewing the operating status and data for an autonode.
NOTE: a new autonode site will not be available to this dashboard until the etl-schema repo has been re-deployed because the `autoload_v2_ndt.ndt7_union` view is not updated automatically. See:
* https://github.com/m-lab/autoloader/issues/38
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1070)
> Add dashboard for Autojoin status

- apply-global-prometheus.sh
This change fixes a bug that removes the mlab-autojoin datasources from deployments to the mlab-oti project. Simply, the change removes templates only if they are not in mlab-oti and not in mlab-autojoin.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1071)
> Allow mlab-autojoin to match in mlab-oti

- config/federation/grafana/dashboards/Autojoin.json
The original dashboard included BigQuery datasource variables but individual panels were not referencing this variable. As a result, panels did not work correctly across projects. This fix updates all panels to refer to the datasource variable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1072)
> Select datasource variable in all panels

- config/federation/prometheus/prometheus.yml.template
Locate filters on this label, and without it will fail to notice BYOS nodes where e2e tests are failing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1074)
> Adds "fqdn" label to script_success metrics

- config/federation/grafana/dashboards/Autojoin_SiteOverview.json
The dashboard has many of the same features/panels as the Site Overview dashboard we use for the platform cluster, minus kubernetes things. This new dashboard leverages mostly the new node_exporter container on Autojoin machines.
https://grafana.mlab-sandbox.measurementlab.net/d/deeyimsfzkwe8c/autojoin3a-site-overview?orgId=1&var-datasource=P60A8177CFC1B8B4B&var-gkedatasource=xIXR1_LMz&var-org=mlab&var-site=All&var-machine=2248791f
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1076)
> Adds new Site Overview dashboard for Autojoined machines

- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
The Locate Service filters on label "fqdn" when looking to see whether e2e testing to a machine is failing. This PR adds that label Autojoin e2e testing so that Locate can effectively stop serving a machine where e2e testing is not working.
Additionally, in anticipation of moving M-Lab-managed VMs to leveraging the Autojoin system, this PR adds a new alert that will fire when Autojoin is less than 10d away from removing a DNS entry for an M-Lab-managed VM. This should give operators plenty of lead time to resolve the issue. In any case, by the time this alert may fire, other k8s alerts for the node should have already fired.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/promethe …
> Adds "fqdn" label to script_exporter e2e metrics + new alert

- config/autojoin/prometheus/alerts.yml
- config/autojoin/prometheus/prometheus.yml.template
- config/autojoin/prometheus/rules.yml
This is almost identical to a simlar alert we have in k8s-support to monitor Pusher data volume:
https://github.com/m-lab/k8s-support/blob/main/config/prometheus/alerts.yml#L582
I don't know if 70% is the right threshold here, but it can serve as a start. When I ran the query manually in production, it did correctly show that the alert would have fired right after the incident began. What I don't know yet is whether 70% is too sensitive for the byos platform.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1078)
> Adds new alert for when Jostler data volume is too low in autojoin

- config/federation/grafana/dashboards/Autojoin_SiteOverview.json
Previously, if an org had more than one machine, the panel on each row would be displaying the test rate for all machines, not just the machine for that row.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1080)
> Filters tests/min panel in AutoJoin:SiteOverview on machine

- k8s/autojoin/deployments/bigquery-exporter-3h.yml
- k8s/prometheus-federation/deployments/bigquery-exporter-24h.yml
- k8s/prometheus-federation/deployments/bigquery-exporter-3h.yml
- k8s/prometheus-federation/deployments/bigquery-exporter-5m.yml
- k8s/prometheus-federation/deployments/bigquery-exporter-discuss.yml
There were quite a few changes since the last release in 2021, but no new version was ever released.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1082)
> Updates bigquery-exporter container image to v1.2.0

- config/federation/grafana/dashboards/Autojoin_SiteOverview.json
The panels were not correctly filtering on org name, so if for any reason the same machine name belonged to two orgs, then the panel would not display properly. This shouldn't normally happen, but, for example, I accidentally created an org with the wrong name, the ISP brought up the machine, then I realized my mistake and created a new org with the right name, and the ISP brought that one up. We then had metrics for the same machine name, but two different orgs. For some reason this bug is affecting the "mlab" org too, and this should fix that also.
https://grafana.mlab-sandbox.measurementlab.net/d/deeyimsfzkwe8c/autojoin3a-site-overview?orgId=1&var-datasource=P9963F0EC00120018&var-org=garuda&var-machine=All
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …
> Fixes a small bug in the Autojoin_SiteOverview dashboard

- config/federation/grafana/dashboards/Autojoin_SiteOverview.json
Matching on the org now allows for dashes in the name, which will catch names like "google-oim".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1085)
> Modifies the "org" variable regexp on the AutoJoin:SiteOverview dashboard
