m-lab/prometheus-support

- README.md
- apply-cluster.sh
- config/federation/prometheus/prometheus.yml
- k8s/federation/prometheus.yml
Pending investigation of how to best monitor scraper, we need to disable federation collection entirely.
> Disable federation

- k8s/mlab-sandbox/scraper-cluster/deployments/kube-state-metrics.yml
- k8s/mlab-sandbox/scraper-cluster/deployments/prometheus.yml
- k8s/mlab-sandbox/scraper-cluster/persistentvolumes/persistent-volumes.yml
- k8s/mlab-sandbox/scraper-cluster/persistentvolumes/storage-class.yml
- k8s/mlab-sandbox/scraper-cluster/roles/rbac-prometheus.yml
- k8s/mlab-sandbox/scraper-cluster/services/prometheus.yml
This adds prometheus configuration for mlab-sandbox.
This configuration is subject to change, but the initial version is based on mlab-staging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/62)
> Add scraper-cluster configuration for sandbox.

- README.md
- k8s/mlab-sandbox/prometheus-federation/deployments/prometheus.yml
This change updates the README to use the correct k8s and config paths for services.
> Update README & fix a typo

- .travis.yml
- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml
- k8s/mlab-oti/downloader/deployments/kube-state-metrics.yml
- k8s/mlab-oti/downloader/deployments/prometheus.yml
- k8s/mlab-oti/downloader/persistentvolumes/persistent-volumes.yml
- k8s/mlab-oti/downloader/persistentvolumes/storage-class.yml
- k8s/mlab-oti/downloader/roles/rbac-prometheus.yml
- k8s/mlab-oti/downloader/services/prometheus.yml
- k8s/mlab-sandbox/downloader/deployments/kube-state-metrics.yml
- k8s/mlab-sandbox/downloader/deployments/prometheus.yml
- k8s/mlab-sandbox/downloader/persistentvolumes/persistent-volumes.yml
- k8s/mlab-sandbox/downloader/persistentvolumes/storage-class.yml
- k8s/mlab-sandbox/downloader/roles/rbac-prometheus.yml
- k8s/mlab-sandbox/downloader/services/prometheus.yml
- k8s/mlab-staging/downloader/deployments/kube-state-metrics.yml
- k8s/mlab-staging/downloader/deployments/prometheus.yml
- k8s/mlab-staging/downloader/persistentvolumes/persistent-volumes.yml
- k8s/mlab-staging/downloader/persistentvolumes/storage-class.yml
- k8s/mlab-staging/downloader/roles/rbac-prometheus.yml
- k8s/mlab-staging/downloader/services/prometheus.yml
I'm sure that this could be done better, don't hesitate to tell me how. But it should sufficiently monitor the downloader service and make those stats appear in prometheus/grafana.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/76)
> Configs for downloader monitoring

- config/federation/prometheus/prometheus.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/86)
> Adds a block to configure the Prom cluster to scrape the snmp-targets.

- k8s/mlab-oti/prometheus-federation/deployments/prometheus.yml
- k8s/mlab-staging/prometheus-federation/deployments/prometheus.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/96)
> Adds Prom configs to scrape snmp_exporter targets for mlab-staging.

- k8s/mlab-oti/prometheus-federation/deployments/grafana.yml
- k8s/mlab-staging/prometheus-federation/deployments/grafana.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/97)
> Update grafana deployment to use OAuth login in staging & prod.

- config/federation/prometheus/alerts.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/114)
> Adds a new AlertManager alert for the snmp_exporter service.

- config/federation/prometheus/alerts.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/117)
> One billion

- config/federation/blackbox/config.yml
These new modules are required by the new Prom targets created by [m-lab/operator/pull/163](https://github.com/m-lab/operator/pull/163).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/119)
> Adds two new blackbox_exporter modules.

- config/federation/prometheus/alerts.yml
Was great, is no longer required
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/125)
> Remove the onebillion alerts

- config/federation/prometheus/alerts.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/140)
> add new alert

- config/federation/prometheus/rules.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/154)
> Fix typo for 98th percentile rules.

- .travis.yml
This is a small PR which takes care of a number of small issues I noticed in the Travis build of this repo. The fixes are adequately explained, I think in each commit message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/169)
> A handful of misc fixes and enhancements in build process ... no-op on running code 

- config/federation/prometheus/prometheus.yml.template
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/170)
> Fixes a syntax error in specifying PROJECT.. use template variable substitution.

- k8s/prometheus-federation/deployments/prometheus.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/175)
> Adds path and URL for k8s service discovery for NDT queueing check targets.

- config/federation/prometheus/alerts.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/182)
> Update link to use JSON dashboard for alert

- config/federation/grafana/dashboards/Pipeline_PT.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/184)
> Add json file for PT pipeline

- config/federation/prometheus/rules.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/185)
> Adds 4 new Prom recording rules to record switch packet discard metrics.

- config/federation/prometheus/alerts.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/191)
> Adds two new alerts for the script_exporter and its metrics

- config/federation/prometheus/alerts.yml
Once merged, this should resolve #194.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/195)
> Updates dashboard URL for annotation of the ScriptExporterMissingMetrics alert

- config/federation/bigquery/bq_ipv6_bias.sql
- config/federation/bigquery/bq_ndt_server.sql
- config/federation/bigquery/bq_ndt_tests.sql
This change updates the query dataset name for the NDT tables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/207)
> Update dataset name for NDT tables

- config/federation/prometheus/alerts.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/224)
> Adds an alert for the collectd-mlab service.

- config/federation/prometheus/alerts.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/226)
> Adds camel-case to CoreServices_ alert classifier.

- k8s/prometheus-federation/deployments/github-receiver.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/247)
> Update github receiver version

- k8s/prometheus-federation/deployments/mlabns-stackdriver.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/256)
> Add instance RAM & Datastore metrics for mlab-ns

- k8s/prometheus-federation/mlab-sandbox.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/260)
> Increase sandbox resource alloc for prometheus

- config/federation/grafana/dashboards/Ops_OamOverview.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/275)
> Adds a new dashboard to monitor the OA&M VMs (eb, dns, mirror).

- config/federation/vms/legacy-targets/vms_ndt_cloud.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/288)
> Add fastss metrics

- config/federation/vms/legacy-targets/vms_ndt_cloud.json
This adds test nodes for monitoring ndt-cloud and tcp-info.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/289)
> Add testing nodes for tcp-info monitoring

- config/federation/prometheus/alerts.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/315)
> Adds a conditional for SnmpScrapingDownAtSite with gmx_site_maintenance.

- config/federation/grafana/dashboards/Pipeline_Gardener.json
This changes starts/completes to +/-, and color codes them by type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/333)
> tweak start/complete graph

- config/federation/grafana/dashboards/Pipeline_Gardener.json
https://snapshot.raintank.io/dashboard/snapshot/JyodoYYHeB4ORSbJlDJqJZ3N72wkPLUc?orgId=2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/337)
> add sawtooth task date graph

- config/federation/grafana/dashboards/Pipeline_Gardener.json
Argh.  I merged the wrong branch.
This is the branch that actually works. (I think).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/339)
> Sandbox sawtooth

- config/federation/grafana/dashboards/Prometheus_SelfMonitoring.json
Small patch to the Prometheus_SelfMonitoring.json dashboard.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/349)
> Report the minimum uptime

- config/federation/grafana/dashboards/Pipeline_Batch.json
Also adds descending sort to some of the panels.
I'm inclined to do that on all panels.  Thoughts?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/352)
> fix bug in backend error panel

- config/federation/grafana/dashboards/Pipeline_Batch.json
- config/federation/grafana/dashboards/Pipeline_Batch_Throughput.json
- config/federation/grafana/dashboards/Pipeline_NDT.json
This PR updates the URLs used in several dashboards to use public cloud console links.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/355)
> Update cloud console links

- config/federation/grafana/dashboards/Pipeline_Gardener.json
This change adds the year to the Files/Hour panel legend.
This change updates the legend to include the year like the other panels near it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/359)
> Add year to legend format

- config/federation/grafana/dashboards/Ops_PodOverview.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/364)
> Added per-site and per-node GMX status and per-node lame duck status.

- config/federation/grafana/dashboards/Pipeline_Annotation_Service.json
See https://grafana.mlab-sandbox.measurementlab.net/d/000000020/pipeline-annotation-service?orgId=1
Compare to staging to see changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/370)
> Simplify CPU panel

- k8s/prometheus-federation/deployments/prometheus.yml
Closes #372.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/373)
> Removed reset-perms on container's initialization

- config/federation/grafana/dashboards/NDT_Median_Rates.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/375)
> Add 99.9th percentile panels to NDT median rates dashboard

- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
This PR adds the scrape configuration for rebot's metrics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/381)
> Added rebot as scrape target.

- README.md
- config/federation/prometheus/prometheus.yml.template
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/385)
> Revert "Use snmp service running on gke cluster"

- config/federation/grafana/dashboards/Pipeline_Batch.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/392)
> small tweaks, mostly on cpu panel

- k8s/prometheus-federation/deployments/grafana.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/398)
> Update Grafana to v5.4.3

- config/federation/grafana/dashboards/K8s_MasterCluster.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/403)
> Removes the 'Copy' suffix from the name of the K8s_MasterCluster dashboard

- config/federation/grafana/dashboards/Pipeline_Annotation_Service.json
- config/federation/grafana/dashboards/Pipeline_Gardener.json
This change updates the Annotation Service dashboard so that we can delete copies in sandbox & staging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/405)
> Update Annotation & Gardener dashboards

- k8s/prometheus-federation/deployments/prometheus.yml
This deploys the fix from https://github.com/m-lab/gcp-service-discovery/pull/28
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/409)
> Update service-discovery tag for bug fix

- config/federation/grafana/dashboards/K8s_MasterCluster.json
As well as adding a few other fixes and improvements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/419)
> Fixes an issue with the master variable

- config/federation/bigquery/bq_mlabns_ratelimit.sql
- config/federation/grafana/dashboards/MLABNS_Ratelimit.json
- k8s/prometheus-federation/deployments/bigquery-exporter.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/429)
> Add sql to calculate the counts that rate limits are triggered

- config/federation/grafana/dashboards/MLABNS_Ratelimit.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/431)
> remove hard coded project name from dashboard json file

- config/federation/prometheus/alerts.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/432)
> low the triggering bar for annotation rate too low to 98% from 99%

- k8s/prometheus-federation/deployments/prometheus.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/438)
> Update version of gcp-service-discovery

- config/federation/grafana/dashboards/Pipeline_Batch_Throughput.json
This adds a datasource variable, so we can use the same dashboard to look at any project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/443)
> Add datasource to PipelineBatchThroughput

- config/federation/prometheus/alerts.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/446)
> Add absent() check for bq exporter.

- config/federation/bigquery/bq_ipv6_bias.sql
- config/federation/bigquery/bq_ndt_annotation.sql
- config/federation/bigquery/bq_ndt_geohash_client.sql
- config/federation/bigquery/bq_ndt_geohash_server.sql
- config/federation/bigquery/bq_ndt_server.sql
- config/federation/bigquery/bq_ndt_tests.sql
- config/federation/bigquery/bq_ndt_worldmap_server.sql
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/447)
> Use canonical NDT views in measurement-lab for BQ exporter queries

- apply-global-prometheus.sh
- k8s/prometheus-federation/deployments/rebot.yml
This PR adds a Rebot deployment and corresponding configuration in `apply-global-prometheus.sh`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/450)
> Add Rebot deployment + configuration.

- k8s/prometheus-federation/deployments/rebot.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/451)
> Add https:// and imagePullPolicy: Always.

- config/federation/bigquery/bq_ndt_annotation.sql
- config/federation/prometheus/alerts.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/453)
> Add alert for ASN annotation rate

- k8s/prometheus-federation/deployments/reboot-api.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/465)
> Update reboot-api deployment to v0.1.1.

- k8s/prometheus-federation/deployments/grafana.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/467)
> Upgrades Grafana from v5.4.3 to v6.2.0.

- k8s/prometheus-federation/deployments/github-receiver.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/470)
> Update alertmanager-github-receiver to v0.8.

- k8s/prometheus-federation/deployments/gmx.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/471)
> Upgrades GMX's image version from v0.1.2 to v0.2.0.

- k8s/prometheus-federation/deployments/prometheus.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/472)
> Update gcp-service-discovery to v1.5.0

- k8s/prometheus-federation/deployments/snmp-exporter.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/477)
> Updates snmp_exporter from v0.13.0 to v0.15.0.

- config/federation/prometheus/alerts.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/479)
> Adds an absent() alert for etcd metrics. This should resolve #475.

- IPV6_MONITORING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/481)
> Update IPV6_MONITORING.md adding a specific image version

- config/federation/grafana/dashboards/MLABNS_Stackdriver.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/485)
> Break out 4xx and 5xx errors into different lines

- k8s/prometheus-federation/deployments/reboot-api.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/493)
> Update reboot-api to v0.1.2

- config/federation/grafana/dashboards/K8s_WorkloadOverview.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/526)
> Reenables a panel query that was accidentally disabled.

- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
Should complete https://github.com/m-lab/dev-tracker/issues/269
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/527)
> Add alerts for collectd on platform-cluster.

- config/federation/grafana/dashboards/K8s_SiteOverview.json
- config/federation/prometheus/alerts.yml
Also, remove the "for: 2m" directive so this alert fires immediately once the condition is met.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/538)
> Change sum_over_time period to 24h to reduce flapping

- k8s/prometheus-federation/deployments/gmx.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/546)
> Updates GMX version to v1.0.1 and adds new --project flag.

- k8s/prometheus-federation/deployments/gmx.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/555)
> Updates GMX to v1.1.0

- k8s/prometheus-federation/deployments/gmx.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/560)
> Bumps GMX version to 1.2.0.

- config/federation/grafana/dashboards/K8s_SiteOverview.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/576)
> Include site in row title

- config/federation/grafana/dashboards/K8s_TCPInfo.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/579)
> Add tcpinfo dashboard

- README.md
This should resolve issue #575.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/586)
> Adds new section to README for how to delete provisioned datasources.

- k8s/prometheus-federation/deployments/bigquery-exporter.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/599)
> Adds new NDT S2C/discards query to bq-exporter config flags.

- k8s/prometheus-federation/deployments/gmx.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/609)
> Updates GMX to version v1.2.1.

- config/federation/prometheus/alerts.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/621)
> Add SLO alert for daily gcs transfers to public archives

- config/federation/prometheus/alerts.yml
This PR fixes a typo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/622)
> Fix typo "PlatformClustser"

- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
Intended to resolve issue #619.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/628)
> New alert when there are too many kubelet/kernel versions in cluster for too long.

- config/federation/grafana/dashboards/Ops_SwitchOverview.json
Update panels to use the selected datasource and enables the shared crosshair.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/634)
> Use selected datasource in Ops: Switch Overview

- config/federation/grafana/dashboards/Ops_Tactical_SRE_Overview.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/637)
> Only report alerts from the last week

- config/federation/grafana/dashboards/Download_Bandwidth.json
- config/federation/grafana/dashboards/NDT_Download_Speeds.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/638)
> Add download bandwidth dashboard

- generate-prometheus-targets.sh
Additionally, the sandbox and staging URLs will use only "flat" (dashed) names, since all v2 siteinfo outputs uses nothing but dashed names.
Out puts for production should remain as they are today.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/640)
> Generates project-decorated Prom targets for sandbox and staging

- config/federation/grafana/dashboards/NDT_Download_Speeds.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/646)
> Update titles and lables for NDT: Download Speeds

- config/federation/grafana/dashboards/K8s_Topk_Machine_Pod_Resources.json
Part of https://github.com/m-lab/dev-tracker/issues/580
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/657)
> Add new dashboard for topk machine & pod resources

- k8s/prometheus-federation/deployments/switch-monitoring.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/665)
> Bump switch-monitoring version to v0.1.1

- k8s/prometheus-federation/deployments/gmx.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/670)
> Updates GMX to v1.3.1, which includes v2 name compatibility fixes.

- config/federation/grafana/dashboards/K8s_SiteOverview.json
* v2 node name fixes
* Load1 panels were showing all nodes, not just that section's node.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/679)
> A number of small fixes to the k8s:SiteOverview dashboard

- config/federation/grafana/dashboards/Alert_ScriptExporterDownOrMissing.json
- config/federation/prometheus/alerts.yml
This change updates the operational alerts for the new script-exporter. This also adds a new dashboard for this alert.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/687)
> Update script-exporter alert and add alert dashboard

- config/federation/prometheus/alerts.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/709)
> Clarify how to investigate GCSTransfers alerts

- k8s/prometheus-federation/deployments/reboot-api.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/715)
> Bump reboot-api to v0.5.1

- k8s/prometheus-federation/deployments/rebot.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/726)
> Bump Rebot to v0.2.0

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/728)
> Enable data-processing cluster prometheus deploy

- k8s/prometheus-federation/deployments/reboot-api.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/729)
> Bump reboot-service to v0.5.2

- config/federation/grafana/dashboards/Pipeline_Gardener.json
this adds a couple more panels that integrate info about the parsers.
Also adds some panel links (in the info hover in upper-left corner) for the parser related panels.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/738)
> Sandbox gardener more panels links

- config/federation/prometheus/alerts.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/743)
> Makes RAM alert aware of GMX mode.

- k8s/prometheus-federation/deployments/bigquery-exporter-3h.yml
- k8s/prometheus-federation/deployments/bigquery-exporter-5m.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/755)
> Add separate 3h instance for expensive queries

- k8s/prometheus-federation/deployments/bigquery-exporter-3h.yml
- k8s/prometheus-federation/deployments/bigquery-exporter-5m.yml
These are relatively inexpensive in sandbox, but much more expensive in staging and prod.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/756)
> move two more expensive queries to 3h period

- config/federation/prometheus/alerts.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/762)
> Adds link to alert description on how to resize Prom VM's disk.

- config/federation/prometheus/alerts.yml
https://github.com/m-lab/prometheus-support/issues/769
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/770)
> lower the alert bar for gardener slow processing

- config/federation/grafana/dashboards/Pipeline_Batch.json
- config/federation/grafana/dashboards/Pipeline_Gardener.json
Small fixes to visibility.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/777)
> Small fixes to Pipeline dashboards

- config/federation/grafana/grafana.ini
This change should permit us to give access to the Wehe team.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/779)
> Adds domain northeastern.edu to permitted domains for Grafana login

- k8s/prometheus-federation/deployments/rebot.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/784)
> Update rebot to v0.2.1

- config/federation/grafana/provisioning/datasources/platform-cluster_mlab-oti.yml.template
- config/federation/grafana/provisioning/datasources/platform-cluster_mlab-sandbox.yml.template
- config/federation/grafana/provisioning/datasources/platform-cluster_mlab-staging.yml.template
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/795)
> Update URLs for the platform-cluster prometheus datasources

- k8s/prometheus-federation/deployments/script-exporter.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/807)
> Updates script-exporter-support image version to v0.2.2

- config/federation/grafana/dashboards/MLABNS_Stackdriver.json
While preparing the data-annotation issue for https://github.com/m-lab/data-annotations/issues/25 I needed to manually edit the panel. This change incorporates my changes by pulling out module_id and adding the 2xx label to 2xx values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/806)
> Differentiate 2xx values and label by module_id

- k8s/prometheus-federation/deployments/script-exporter.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/813)
> Updates script_exporter image to version v0.2.6

- k8s/prometheus-federation/deployments/script-exporter.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/814)
> Bumps script_exporter container image to v0.2.7

- config/federation/grafana/dashboards/Pipeline_Overview.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/818)
> Sandbox pipeline overview

- config/federation/grafana/dashboards/Ops_SwitchOverview.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/819)
> Add uplink speeds variable, so we can look at either 10g or 1g

- k8s/prometheus-federation/deployments/script-exporter.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/823)
> Bumps script-exporter Docker image version to v0.2.9

- config/federation/grafana/dashboards/Exp_Scamper_Detail.json
This dashboard has basic metrics to track trace volume, latency, and success rate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/828)
> Add preliminary scamper detail dashboard

- k8s/prometheus-federation/deployments/prometheus.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/832)
> Bumps version of gcp-service-discovery to v1.5.1

- config/federation/bigquery/bq_gardener.sql.template
- config/federation/bigquery/bq_gardener_parse_time.sql.template
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/841)
> Add hopannotation1 to existing bigquery exporter queries

- config/federation/bigquery/bq_gardener.sql.template
- config/federation/bigquery/bq_gardener_parse_time.sql.template
Revert "Add hopannotation1 to existing bigquery exporter queries"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/842)
> Remove hopannotation1 from bigquery exporter queries until there are data in the table

- config/federation/grafana/dashboards/Stats_Pipeline_AnnotationExportMonitoring.json
Link to dashboard: https://grafana.mlab-sandbox.measurementlab.net/d/XokjBPKnj/annotation-export-monitoring?orgId=1&var-datasource=Data%20Processing%20(mlab-sandbox)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/857)
> Display hopannotation1 data in Annotation Export Dashboard

- config/federation/prometheus/alerts.yml
Update the alerts link so they point to the right dashboard.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/871)
> Update Pipeline dashboards

- config/federation/grafana/dashboards/NDT_Client_Rates_Quantiles_Heatmaps.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/887)
> Selects on site rather than metro in dropdown

- config/federation/grafana/dashboards/Pipeline_AlternativeSLIs.json
- config/federation/prometheus/prometheus.yml.template
Graph in sandbox https://grafana.mlab-sandbox.measurementlab.net/d/q4MrNzh7k/pipeline-slis?orgId=1&from=now-1h&to=now&viewPanel=26
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/890)
> Add tests/hour failure graph

- k8s/prometheus-federation/deployments/gmx.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/924)
> Bumps GMX image version to v1.4.0

- config/federation/grafana/dashboards/Locate_Service.json
https://grafana.mlab-sandbox.measurementlab.net/d/8O9tInk4k/locate-service?orgId=1&var-datasource=Prometheus%20(mlab-sandbox)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/930)
> Add initial dashboard for Locate service

- config/federation/grafana/dashboards/Autoloader.json
- config/federation/grafana/dashboards/Pipeline_Autoloader.json
Happy to discuss interactively https://grafana.mlab-sandbox.measurementlab.net/d/OKQmdgs4k/autoloader?orgId=1 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/982)
> Add a new dashboard for the autoloader

- config/federation/grafana/dashboards/Locate_Service.json
Panels:
- [Ratio](https://grafana.mlab-sandbox.measurementlab.net/d/8O9tInk4k/locate-service?orgId=1&refresh=5m&viewPanel=50)
- [Percentile](https://grafana.mlab-sandbox.measurementlab.net/d/8O9tInk4k/locate-service?orgId=1&refresh=5m&viewPanel=52)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/998)
> Display ratio and percentiles in /nearest duration panels

- config/federation/grafana/dashboards/NDT_EarlyExit.json
- [Download speed](https://grafana.mlab-sandbox.measurementlab.net/d/W8JPPzzIz/ndt-early-exit?orgId=1&viewPanel=14)
- [Bytes sent](https://grafana.mlab-sandbox.measurementlab.net/d/W8JPPzzIz/ndt-early-exit?orgId=1&viewPanel=13)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1012)
> Add PDF comparisons for Early Exit dashboard

- config/federation/grafana/dashboards/NDT_EarlyExit.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1013)
> Change unit from bytes to MB

- config/federation/grafana/dashboards/MSAK_Monitoring.json
- k8s/prometheus-federation/deployments/grafana.yml
https://grafana.mlab-sandbox.measurementlab.net/d/b00a7fe1-6ceb-449c-b438-a00576e222c2/msak-monitoring?orgId=1&refresh=5s&var-datasource=hW1JkhyGk
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1027)
> Add MSAK monitoring dashboard

- README.md
- config/federation/grafana/dashboards/MLABNS_6_HourClients.json
- config/federation/grafana/dashboards/MLABNS_PrometheusQueries.json
- config/federation/prometheus/alerts.yml
- config/federation/prometheus/prometheus.yml.template
- generate-prometheus-targets.sh
This reverts commit ab4be663d787dbfff37890307a774553b9847fe3.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1029)
> Revert "Eliminates all usage of "ndt.iupui" and "neubot.mlab" (#1028)"

- config/federation/bigquery/bq_billing.sql
- config/federation/prometheus/alerts.yml
This PR adds BigQuery exporter metrics and an alert to monitor Storage costs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1033)
> Add storage billing metrics and alerts

- config/federation/prometheus/alerts.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1053)
> Update delay to 1h to avoid brief outages

- config/federation/grafana/dashboards/Autojoin_SiteOverview.json
https://grafana.mlab-sandbox.measurementlab.net/d/deeyimsfzkwe8c/autojoin3a-site-overview?orgId=1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-support/1079)
> Adds a tests/min panel to the Autojoin:SiteOverview dashboard
